### ISSUE TITLE
UserVoice Idea: Another Job Scam

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#1023]
Dr. from Whitestein Technology sent me an email stating I would be a great fit!  After setting up Google Hangout to do a video interview he asked for my email address....um you already sent me an email saying that I was a good fit for the company.  I continued the conversation asked him where was he from and does he work for this company.  He replied that he was in Baltimore and he worked for this company.  I did and image search and Dr. Pritt was using Prof.Dr. Atta ur Rahman photo from PAKISTAN!! He said he didnt understand...so i sent the link of the picture he used and his account was deleted I think.
Anyways...here is his information:
Dr. Pritt from Whitestein Technoloy
Email: Paul Pitt <dr.paulpitt@gmail.com>
Email I was considered: VA JOB PORTAL <jamesmorris@riseup.net>

Hope this helps...I dont feel comfortable knowing that my life history was reviewed and It just made it a bit easier to become a victim. 

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11384052-another-job-scam

**Comment by koconnor719** [comment]
Thank you for your feedback. It is unfortunate that anyone would try to take advantage of a Veteran. We have a blog post to help warn Veterans about protecting themselves from phishing attacks "Veterans Employment Center Website: False Claim of Breach" at http://www.blogs.va.gov/VAntage/23299/veterans-employment-center-website-false-claim-of-breach/ . We love your idea about linking to it from the VEC so that Veterans who are posting their resumes to various sites will know how to protect themselves and we are already in the process of adding that to vets.gov.

vets.gov team
