### ISSUE TITLE
UserVoice Idea: Landing Page Usability Suggestions

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#1058]
Couple of usability suggestions.
(1) When you hover over the light bulb in bottom right corner, provide feedback (like alt text) to tell user what this is, so they don't have to click it to find out.
(2) Provide better guidance on which items are clickable, in addition to just slight color change. For example "Disability Benefits" and Education Benefits" boxes should have some visual indicator such as an arrow or other icon that is clear that this is a function.
(3) The "How can we help?" box sort of looks like a ransom note, as opposed to a clean header.
p.s., I like the direction of this, but wanted to point out a couple things that jumped out at me.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11489181-landing-page-usability-suggestions

**Comment by koconnor719** [comment]
posted response and assigned to mary ann for user testing and research on the feedback forum item # 1.  i agree we need to improve this feature.

Thank you for your feedback. Our user research team has been conducting testing with Veterans on the "feedback forum" feature (the light bulb) and will making improvements based on that research in the near future. We agree with you, that making it easy for users to provide feedback on vets.gov is very important. We will have our designers and researchers look into the other items you suggest as well to see what Veterans think!  Thank you.

vets.gov team

**Comment by dannychapman** [comment]
Great point re: the big blue boxes. I will see what I can work up for these.

**Comment by maryannbrody** [comment]
Re: Point 1 -- Good point. I've wondered this too. I think we can probably make the sticky version of the icon a little bigger with text since hovering text wouldn't be as effective on mobile -- [users would have to click to see the text, and we'd rather they click to get straight to user voice]. "Provide feedback on the site." I think we can just do this - no need to do any testing. 

@dannychapman thoughts about something like this (conceptually)?
![image](https://cloud.githubusercontent.com/assets/12674895/12522397/6e6999ea-c11e-11e5-8918-478646780faf.png)

 
Re: Point 2 -- For whatever it's worth, I've yet to see a user not click on the big blue boxes -- every person I've watched knew right away they were clickable. But -- @dannychapman we could maybe add an active state and a focus state, a la: https://playbook.cio.gov/designstandards/buttons/


Re: Point 3 -- Noted, and I'll be watching behavior on this one. It looks clickable to me, but I haven't seen anyone try to click it yet. Let's keep an eye on this.

**Comment by dannychapman** [comment]
@maryannbrody Agreed re: active and focus states. I've added an issue for this #1115

For the feedback button, we'll have to see what options there in terms of styling  / adding content with Uservoice for the feedback title. Only negative I see with that approach is how much it will cover the content as you scroll. We could consider something fancy, like having the additional feedback text appear after a few seconds of no scroll / interaction.

**Comment by koconnor719** [comment]
@maryannbrody can we close this issue given above?  can you provide suggested response that i can post pls:)

**Comment by maryannbrody** [comment]
Closing, started a new issue for user voice icon #1122
