### ISSUE TITLE
CareerScope Link 

### ISSUE THREAD

**Issue by rickleegit** [department-of-veterans-affairs/vets-website#1188]
This may have been intentional, but wanted to mention it because it is the most clicked outbound link from the Comparison Tool.

The CareerScope page (https://www.vets.gov/education/tools-programs/careerscope/) does not include a link to CareerScope (http://www.benefits.va.gov/gibill/careerscope.asp) and (https://va.careerscope.net/gibill)

**Comment by emilyville** [comment]
Good catch. Let's add a green button link in the gray bar similar to some other ones, and like we have planned for the gi bill page to the gi tool.

Now that I'm looking I'm not sure that linking to page is correct since it has similar content. Can we link to the tool, @rcarthur? I don't see it at first glance.

**Comment by mollyblake** [comment]
I don't see why we can't link to the tool.  The careers and employment section will have to link to the tool as well. You don't need a special logon. @rcarthur , do you agree?

**Comment by koconnor719** [comment]
what is status of this? is it being worked in the "Careers and Employment" content and design work? @gnakm

**Comment by gnakm** [comment]
@koconnor719 Yes. I just opened an issue in veterans-employment-center. @emilyville I will add the green button!

**Comment by rcarthur** [comment]
Dusting off my memory of the conversation with SME at the time.....the word was that Career Scope needed to be done in conjunction with a counselor during an in person appointment.   Now that we're redoing the site in Careers and Employment, this does not seem to be the case.  Molly is our content point for this.

**Comment by gnakm** [comment]
@rickleegit @emilyville @mollyblake Could we clarify what this "tool" is? I just want to make sure I'm on the same page. Would it help to make a new page and have a button that links to that? 

Also, we should talk about designing pages that may have multiple green buttons. 
We can talk about this with @dannychapman in the IA meeting tomorrow.

**Comment by mollyblake** [comment]
@gnakm The career scope tool is an involved assessment/questionnaire that generates a report. The report details twelve interest areas, your level of interest and the activities associated with each. For example: because I 'liked' a lot of artistic activities I should look at jobs such as editor, graphic designer, writer, painter etc.  It also looks at aptitude for tasks like general learning.

**Comment by mollyblake** [comment]
@gnakm @emilyville Should be housed on the page with the Onet profiler tool.

**Comment by koconnor719** [comment]
@rickleegit  what is status of this given careers and employment has launched?

**Comment by koconnor719** [comment]
@gnakm is this closed?  we have this page: https://www.vets.gov/education/tools-programs/careerscope/ but it doesn't seem to have a link to the actual career scope?  just the link to the "report interpretation guide"?   should there be a link to career scope somewhere--seems odd there isn't:)

**Comment by gnakm** [comment]
@koconnor719 Thanks for bringing this up again and sorry for losing tabs on this. 
It seems like what we were going for according to @mollyblake is that we will put a link for the CareerScope on the [Interest Profiler page](https://www.vets.gov/employment/job-seekers/interest-profiler/), which it did but we should still put a button for CareerScope on the CareerScope page

@emilyville Kind like what you mentioned above, what about something like this? I didn't know what else to call it. Also, seems like since we made the two buttons on the GI Bill page, we're sort of decided that the buttons should be in the grey action bar on top. What about doing this (image below) for now and when we make template changes, we make GI Bill buttons (and all the buttons) more consistent. 
![careerscope](https://cloud.githubusercontent.com/assets/13420618/15301042/c2bad882-1b79-11e6-882e-a5a9ab007aa8.png)

**Comment by emilyville** [comment]
Works for me @gnakm!

**Comment by gnakm** [comment]
Changed and merged! #2364
