### ISSUE TITLE
UserVoice does not send notifications on issue comments

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#1203]
Is it possible to add a notification to the GitHub issue when a user comments on an issue they have already created with UserVoice?  Right now, I don't believe this happens and it means that @koconnor719 has to manually inspect whether Veterans have followed up on their feedback or have additional questions after she has responded to the initial inquiry.  

And @koconnor719 also manually posts what her response in UserVoice was in the GitHub issue, but if UserVoice responses were automatically added to GitHub, this would save her a step there as well. Worth investigating I think.

**Comment by koconnor719** [comment]
Good idea!!



Sent with Good (www.good.com)


-----Original Message-----

**Comment by koconnor719** [comment]
christine, i believe you are talking to user voice regarding the explorer 11 issue--can you ask them about alex suggestion above?

@emilyville @MarinaMartin

**Comment by MarinaMartin** [comment]
The Github/UserVoice integration is set up via Zapier.

**Comment by koconnor719** [comment]
awesome! let me know when ready to test! @cfeeney-va

**Comment by koconnor719** [comment]
@cfeeney-va can you pls post an update to the status of this issue in a comment.

**Comment by koconnor719** [comment]
@cfeeney-va is this done? can you pls. update status.

**Comment by cfeeney-va** [comment]
Working on it now; have to get uservoice password from marina again

**Comment by cfeeney-va** [comment]
this functionality didn't seem to exist in the trial version of zapier i was looking at; marina is getting me the info for our actual zapier account and i'll see if we have access to more

**Comment by cfeeney-va** [comment]
Couldn't find support for this on the zapier site or any other resources that would accomplish it.  Emailed zaiper support to see if this is functionality that they currently have.

**Comment by cfeeney-va** [comment]
This isn't possible :/  Email from zapper support:


Unfortunately, we don't currently support a "create comment on an issue" action in GitHub, which your workflow would require. Sorry for the bummer news there! While that's not something we can support right now, I've added a feature request for this action to our in-house wishlist. Since we receive dozens of feature requests every day, I can't give an ETA for this development, but we will let you know via email if and when we're able to make this change!
