### ISSUE TITLE
Crisis line content page

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#1312]
request from VA leadership (M. Eutitis) to have a page of content for the crisis line to help explain to Veterans when it's appropriate to call this line (70% of calls are not suicide related). anticipating a short paragraph of new content with a link to the existing chat feature. contact for content is Julian Mullaine Julianne.Mullane@va.gov 

can someone reach out to julianne to get this page started when you have time:) @mollyblake @maryannbrody @mariana-almeida

**Comment by mollyblake** [comment]
@koconnor719 I will reach out to her and set something up. FYI @rcarthur @maryannbrody

**Comment by mariana-almeida** [comment]
I would reinterpret the issue as the following: we have a crisis line phone number in full and without context on the home page. The phone number doesn't appear clickable, which it is. When you click it you get all the context of when to call, options like chat, etc. I believe we should develop a page that explains all that the [destination page](https://www.veteranscrisisline.net/) does.

I would propose the following edit: 

Present text: 
Veterans Crisis Line 1-800-273-8255 (Press 1)

**Proposed edit.** 
Veterans Crisis Line: **call, chat, or text 24/7**

I would like "call, chat, or text 24/7" underlined to show it's a hyperlink if possible. 

Looking for feedback on original rationale for putting the phone number sans context on the homepage. May we go ahead and change this?

**Comment by koconnor719** [comment]
The crisis line people are going to provide us text for this page.


Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by mariana-almeida** [comment]
Kelly, I omitted a crucial "**NOT**" from my original statement. Apologies! Here's the edit: "I believe we should NOT develop a page that explains all that the destination page does."

Instead, we can just make the ask clearer -- not to call right away but to go see to the web page and view the caveats of when to use this phone number -- what's available on the crisisline.net site. 

Basically, I wouldn't recommend that we develop this page just yet. Is it meant to be our topic eventually?? If so, then I would reconsider.

**Comment by koconnor719** [comment]
Can we sync on the context for this Monday:)

Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by mariana-almeida** [comment]
Ok, sounds good. I'll connect with you then. Have a good weekend!

**Comment by mariana-almeida** [comment]
I chatted with Julianne to discuss. She agreed to the following change to the yellow rectangle near our footer: 

Present text:
Veterans Crisis Line 1-800-273-8255 (Press 1)

Proposed edit.
Veterans Crisis Line: call, chat, or text 24/7

I would like "call, chat, or text 24/7" to be underlined to show it's a hyperlink if possible.

This should go into our content change request excel, but what is the process for making this change (who do I ask, etc.) @emilyville?

**Comment by emilyville** [comment]
Currently the whole thing is a link, like a button that goes to https://www.veteranscrisisline.net. I really like this about it because it makes it really easy on mobile to click anywhere on the yellow. If we're not adding any more link destinations, making the text the links (which is what I think is bring proposed?) actually diminishes how easy this is to use. 

I think changing the text is totally fine, but I think we should just leave everything else as is, unless...

If it's the case we're sending folks to different places, please provide those...?
Veterans Crisis Line: [call](link?), [chat](link), or [text 24/7] (<---- not link)

Also please assign to me when we have this info and I will triage.

**Comment by koconnor719** [comment]
Let's add this to list when u r here next week. Sr va person is requesting a change so if we don't think that's good experience in happy to just say no😀



Sent with Good (www.good.com)


-----Original Message-----

**Comment by mariana-almeida** [comment]
Change text to:

"Veterans Crisis Line: call, chat, or text 24/7" 

@emilyville has reviewed it and agrees.Link goes to the website generally, not indiv links. 

@gnakm - do you have any mock ups of this UI element that is more like a button? I am concerned it doesn't look clickable, and will be confusing. It was confusing with a phone number in it, and might still be even though it won't have a phone number in it. Making it look more like a button will help! Would you have time to dig that up or create something new?

**Comment by mariana-almeida** [comment]
Pinging @gnakm to see if there is a button-like element that we can creare for this content, rather than a simple flat rectangle. Let me know if you want more details. I'd like to close this out by midweek, if possible.

**Comment by koconnor719** [comment]
We need a mockup first for approval before any change is made in production.  Do you have the content?

Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by gnakm** [comment]
@koconnor719 Just talked to @mariana-almeida. I'm put together a mockup by end of the day today for the new and improved button. I'll re-tag everybody on this issue. Once we all agree, let's show it to the appropriate person for approval and then make the global change.

**Comment by gnakm** [comment]
Here is the modified Crisis Line Button.

![crisis line desktop](https://cloud.githubusercontent.com/assets/13420618/13928206/286100fc-ef6b-11e5-8a37-03164750598a.png)

<img width="207" alt="screen shot 2016-03-21 at 1 43 40 pm" src="https://cloud.githubusercontent.com/assets/13420618/13928440/fe2679f6-ef6b-11e5-9003-75b058d5ba38.png">


The idea is to have it consistent with our existing buttons
Close to the height of our apply buttons
<img width="270" alt="screen shot 2016-03-21 at 1 40 50 pm" src="https://cloud.githubusercontent.com/assets/13420618/13928268/58378d5a-ef6b-11e5-8196-e67ee28d18a0.png">

Darker hover state color
#FF9F00
<img width="146" alt="screen shot 2016-03-21 at 1 43 58 pm" src="https://cloud.githubusercontent.com/assets/13420618/13928321/8992c9f0-ef6b-11e5-907b-6bea6870ae68.png">

Also I made it two lines instead of one mainly because both lines have about the same length.
It also makes the button look more prominent. 
If we want it all on one line, we can:
![Uploading Screen Shot 2016-03-21 at 1.50.26 PM.png…]()

@kelly @emilyville @mollyblake @mariana-almeida  Let me know what you think!

**Comment by koconnor719** [comment]
@mariana-almeida was there add'l content from julianne? that was the initial request to add content about when to call the crisis line--not changing the button?  but maybe they changed their mind. also, i'm pretty sure we need the phone number listed there so Veterans can see it right away right? i don't think we should bury the phone number a click in? can we set up a 5 min call on this when you have time.

**Comment by Drakenhart** [comment]
As someone who has had to use crisis lines in the past, not having the number visible up front is seriously problematic. When you are in a crisis, a real one, any barrier to help is a major issue. I've gone to sites, spotted the number and called it from my home phone.

A number that is clickable (and -actually triggers the phone portion to activate- ) when on mobile is even faster.

Seconds can make a difference.

**Comment by koconnor719** [comment]
@mariana-almeida closing this issue b/c i think you are tracking it on your own PM tool since the scope of this request has changed.  we can factor in the helpful feedback above to our approach:)
