### ISSUE TITLE
breadcrumb fix on Careers and Employment page

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#1416]
On this page:
https://vets-website-pr-1304.herokuapp.com/employment/job-seekers/employment-support/
... there are piano keys. When I click any of the piano keys, I go to a page that is missing Veteran Employment Support in the breadcrumbs. 

So, for instance, this page:
https://vets-website-pr-1304.herokuapp.com/employment/job-seekers/alternative/
... has the following breadcrumbs (that are missing Veteran Employment Support following Job Seekers):
Employment > Job Seekers > Alternative ways to start your career

**Comment by webinista** [comment]
There's a huge roadblock to doing this: the breadcrumbs plugin assumes there will never be more than 3 levels of breadcrumbs.

The breadcrumbs plugin uses the structure of the URL to do two things:
1. To function as the titles of the breadcrumbs if those titles haven't been set in `_config.yml`
2. To determine _how many_ breadcrumb segments there should be.
- There will only ever be as many breadcrumbs as there are URL segments.
- The last breadcrumb is always the page title.

In other words, https://vets-website-pr-1304.herokuapp.com/employment/job-seekers/alternative/ has three URL segments:

1. /employment/
2. /job-seekers/
3. /alternative/

So that page has three breadcrumbs: _Employment > Job Seekers > Alternative ways to start your career_. 

If we want to add a 4th breadcrumb, I think our only option is to move those files to another directory. Instead of `/employment/job-seekers/alternative/` it would be `/employment/job-seekers/veteran-employment-support/alternative/`.

There may be another option that I haven't thought of yet. But that's the quickest option I can think of that also has the lowest risk of creating additional problems.

**Comment by emilyville** [comment]
hmmmmm... this is a good discussion to have. I _do_ think we might need a 4th breadcrumb, in the future, for some stuff. 

Let me think on it. also I don't think we're keeping this particular page in the new IA.

**Comment by emilyville** [comment]
After a discussion with @mariana-almeida and looking over our new IA for this section - I think we can punt on adding a fourth breadcrumb. One day we will discuss navigation at more length, but until we have some new awesomeness, I think what we have will work without significantly degrading the user experience. :hammer:

**Comment by mariana-almeida** [comment]
@bethpotts The page you just pointed out is not needed, per my recent IA work. (This one: https://vets-website-pr-1304.herokuapp.com/employment/job-seekers/employment-support/ )

Most of the content became part of the Job Seekers landing page (AKA subway map). I hope this makes sense. 

I think this specific content will need to be fit into other pages if it's not there already: 

"Or if you are considering pursuing education, licensure, or certifications, VA can help guide you through the process." <-- should be added to the end of the subway map where talk about continue to grow your skills.

"If you own your own business or want to start a company, VA, the Small Business Administration Boots to Business program" <--- Make sure this is in the grow your own business area. 

and organizations like Syracuse University’s Institute for Veterans and Military Families offer mentorship, counseling, and training. <----Make sure this is in the Military spouses and families page. 

@rcarthur FYI.

**Comment by rcarthur** [comment]
Looks like this issue was overtaken by events.  

@mariana-almeida - I will double check that the info is reflected on the appropriate pages within the new IA.

**Comment by emilyville** [comment]
I am closing - I think this has been addressed.
