### ISSUE TITLE
VEC repo pages

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1496]
Emily - 
These three pages are ones that reside in the VEC repo, which we can't see right now but need to be able to.....

1) Flow our prepared content toward
2) Conduct a check to make sure the links function correctly
3) Conduct a proof. 
4) Link to these pages  

My understanding is that there maybe some trickiness in this maneuver and I believe that you said that we should send you the documents - just in case there were too many obstacles to the content team members doing this ourselves.  We are happy to do it if it's easier though.  So, I'm including the most recent copy files below.  

**BTW, the copy that we wrote was prepared to go alongside the tool or frame it at the head of each page. **

**Skills Translator **
[Jobs_SkillsTranslator_20160229_SME Edits (1).docx](https://github.com/department-of-veterans-affairs/vets-website/files/188527/Jobs_SkillsTranslator_20160229_SME.Edits.1.docx)

**Resume Builder **
[Jobs_ResumeBuilder_20160302_concurrence_edits_incorp.docx](https://github.com/department-of-veterans-affairs/vets-website/files/188528/Jobs_ResumeBuilder_20160302_concurrence_edits_incorp.docx)

**Job Search**
[Jobs_JobSearch_20160312_link_corrections.docx](https://github.com/department-of-veterans-affairs/vets-website/files/188529/Jobs_JobSearch_20160312_link_corrections.docx)

Let us know how you'd like us to work through these.  

Thanks!!

**Comment by ayaleloehr** [comment]
You should be able to do all of your issues numbered 1 through 4 based on the instructions I sent last night

**Comment by rcarthur** [comment]
Thanks Alex.  Your note on slack was extremely good - we are able to see the actual pages up on staging and think that we know how to link.  That's all fine.....but we can't seem to find the actual files in the repo that we need to be able to do this work.  They are not in this repo---
https://github.com/department-of-veterans-affairs/vets-website/tree/jobs-employment-v2/_employment

If you have time, could you please send us an actual links where we can access these three pages?  Emily said that they would be hard for us to find - and she was right. 

Thanks so much for your help and understanding with this.

**Comment by ayaleloehr** [comment]
Got it. That makes sense. Thanks for clarifying @rcarthur! Those files are in the veterans-employment-center repo, so yes, they would have been almost impossible to find without knowing that! 

They can be found here: [skills translator](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/master/app/views/skills/index.html.erb), [resume builder](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/master/app/views/veterans/new.html.erb), and [job search](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/13c873c8e53cc4121b96f1a746b7a00b2347c1f5/app/views/static_pages/_jobsearch.html.erb).  

For what it's worth, I don't think there is really any content on the job search page currently, as it just looks like [this](https://www.vets.gov/veterans-employment-center/search_jobs).

Those pages I linked to all HTML, not markdown, so not sure of your team's comfort level there. I'm going to leave @emilyville assigned as I think this is her realm that I'm stepping into, but @emilyville you and I should probably have a conversation to get more clear about who has final responsibility for each piece of this, as otherwise something is likely going to fall through the cracks!

**Comment by rcarthur** [comment]
Awesome, thanks!!  We'll wait for word from you or Emily before diving into them.  HTML will take us a while.

Regarding the job search one, the file below has content that we had written/rewritten to go above the actual tool.  Some info that might be helpful to jobseekers as they search.

**Comment by emilyville** [comment]
awesome. I'm on it. Thanks @rcarthur and @ayaleloehr 

I'll start working through this and likely ping you with questions as I go.

**Comment by emilyville** [comment]
this is "done" enough. I'll make a new issue to assess how to integrate this copy into these pages. As is is not idea.
