### ISSUE TITLE
Featured Jobs on Job Search Page

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1576]
@alex,
Regarding the Featured Jobs on the Job Search page, is it possible to include some of the jobs that pop up in the feed at the bottom of this page...... http://vaforvets.va.gov/

Not saying that our feed needs to include all of the VA for Vets jobs....but it would be good for them to get some visibility here. 

cc:  @mariana-almeida @gnakm

**Comment by ayaleloehr** [comment]
@rcarthur be sure to use `@ayaleloehr` for me and not `@alex`.  

Those jobs at the bottom of the VA For Vets feed are just from USA Jobs. We also pull from USA Jobs, so those jobs will already be in our search results. Looking at http://vaforvets.va.gov/ it also looks like all those jobs all expired on 3/24, whereas ours are updated nightly and we remove the expired ones, so I think we have this one covered.  

If you agree with the above, please close this issue.  Otherwise let me know if you have other questions on this!

**Comment by emilyville** [comment]
Assigning to @rcarthur to close or follow up on.

**Comment by rcarthur** [comment]
@ayaleloehr  10-4 on that.  The "featured jobs" on the page previously had all been for "Truck Driver" so we figured that we had better flag it.  As long as we are considering the special "Non-Competitive Appointment" jobs on vaforvets then we are good.

**Comment by emilyville** [comment]
K, sounds like we're all in agreement. closing!
