### ISSUE TITLE
Shortened copy for Job Search page

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1581]
Shortened copy as follows [fyi @mariana-almeida @gnakm @bethpotts @mollyblake @kellyskennedy 

Above the job search tool:
Search the Veterans Job Bank to find the right position for you.

Middle Content:
Three tips to get the most out of the job search tool:  
1.   Make your search as broad as possible. 
2.   Check a variety of geographical areas.
3.   Use the [Skills Translator tool](https://vets.gov//employment/job_seekers/skills-translator) to find a civilian job description to match your military specialty.

Below the Tool (but above the "Featured Jobs"):
Get [one-on-on assistance](https://vets.gov/employment/job_seekers/one-on-one), and explore other ways to look for a job. Consider applying for a [federal job](https://vets.gov/employment/job_seekers/federal-employment), Veteran Administration job (http://vaforvets.va.gov/) or start [your own business](https://vets.gov/employment/job_seekers/start). Other paths include additional education, certifications, and apprenticeships.

**Comment by gnakm** [comment]
So interesting how filled the page feels with minimal content!
Here is a preview of how this may look. For example 2, I simplified the copy even more so that the links are scannable but I'm okay with either or. I just was playing around with it. As a Veteran recently said, white space is key! So spacing is going to play a big role to prevent the page from feeling cluttered. @emilyville have you had any thoughts on the widgets? I honestly don't remember if we decided on making them links or putting them in a box. Maybe we can recap tomorrow?

@mariana-almeida @rcarthur Thoughts?
1
![example 1](https://cloud.githubusercontent.com/assets/13420618/14098573/759ab094-f54b-11e5-895c-a5e1a1d8879e.png)
2
![example 2](https://cloud.githubusercontent.com/assets/13420618/14098574/759d3d14-f54b-11e5-830b-f25189907549.png)

**Comment by mollyblake** [comment]
Can we change "check a variety of geographical areas" to something different?  Check implies that you check a box. And really, you just input areas in the search tool box.  What's the functionality of that WHERE box?   Should you put more than one city in there?  @ayaleloehr @emilyville

**Comment by gnakm** [comment]
Let's go with this. It's more in scale. @emilyville @rcarthur Curious do we have copies that go with the linkedin, coursera, and resume builder widgets? Or did we decide that they're just going to be links (or blocks)?
![example 1](https://cloud.githubusercontent.com/assets/13420618/14146233/e8afa08e-f664-11e5-98f6-8f6c6bffd60a.png)

**Comment by gnakm** [comment]
@mollyblake 

- What about "Find a variety of geographical areas?"
- The where box really means location but I think it's consistent with the "what." Unless you have a suggestion to change both though I highly suggest that we make that soon. 
- There should only be a one city input. All of the job search engines I have used allows 1 location unless you have an advanced search that goes side by side with a spectrum of broad and specific searches but I think keeping our job bank very simple is the way to go :smiley: 

My question is -- did we have copy to go with the linkedin, coursera, and resume builder widgets or are we just linking them?

**Comment by mariana-almeida** [comment]
A couple of comments: 

1) This isn't accurate for what the Military Skills Translator does: "3. Use the Skills Translator tool to find a civilian job description to match your military specialty." It's not about job descriptions. It's about translating your military skills into language hiring managers will understand. 

2) One-on-one assistance needs another noun or descriptor. "One-on-one Assistance to discover employment opportunities" or "One-on-one Job Assistance"

3) I prefer "Additional Resources" instead of "learn more".

**Comment by gnakm** [comment]
@emilyville Here is the finalized copy:


Search the Veterans Job Bank to find the right position for you.

**Three tips to get the most out of the job search tool:**

1. Make your search as broad as possible. 
2. Explore a variety of geographical areas.
3. Use the Skills Translator tool translate your military skills into language hiring managers will understand.

**Additional Resources**
[One-on-one Job Assistance](https://vets.gov/employment/job_seekers/one-on-one)
[Apply for Federal Jobs](https://vets.gov/employment/job_seekers/federal-employment)
[Veteran Administration Job](http://vaforvets.va.gov/)
[Start your own business](https://vets.gov/employment/job_seekers/start)


Linkedin, Coursera and Resume Builder will now become piano keys. woohoo!

**Comment by rcarthur** [comment]
Thumbs up!

**Comment by emilyville** [comment]
this is done in https://github.com/department-of-veterans-affairs/veterans-employment-center/pull/253

**Comment by emilyville** [comment]
Closing out this issue, but will need to open a new one for review once it's up.
