### ISSUE TITLE
Employer Landing Page Content

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1591]
Employer Landing Page content is here:
https://github.com/department-of-veterans-affairs/vets-website/blob/jobs-employment-v2/_employment/employers.md

@mariana-almeida @mollyblake

**Comment by emilyville** [comment]
Just following up to clarify - this needs to be copy added to the employer landing page other than the one you're linking to, in the instance that we send employer landing page to VEC. 

Tagging @ayaleloehr for awareness. At this point it's seeming cleaner to put all employer pages in VEC because then we won't run into the issue where you are logged in and navigate away within the employer section but cannot log out because you're in vets-website.

**Comment by rcarthur** [comment]
Yes, the employer landing page here: https://staging.vets.gov/employment/employers  
...doesn't reflect the IA or the content that we've prepared.

**Comment by emilyville** [comment]
@rcarthur sounds like on staging it's still redirecting to VEC one. I really hope we can get you all on a local version some day so you can see these things more easily!

@gnakm is going to take a pass at combining new and old and we will update today or tomorrow. Stay tuned, and we have your content for it!

**Comment by emilyville** [comment]
tagging @gnakm and @cfeeney-va to close when this is done!

**Comment by gnakm** [comment]
related to 
Show employer progress #267
Employer log in take 2 #271
