### ISSUE TITLE
Switch find/favorite veterans into VEC from vets-website

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#1632]
This page:  
https://vets-website-pr-1600.herokuapp.com/employment/employers/find-candidates/
https://github.com/department-of-veterans-affairs/vets-website/blob/jobs-employment-v2/_employment/employers/find-candidates.md

...should be a tool....and I'm pretty sure that it already exists somewhere after you log in (but log in is not working for me right now).

**Comment by emilyville** [comment]
@rcarthur @gnakm @mariana-almeida -

I have a hunch this is the same thing as what is currently called in VEC "Favorites"? If so, this is likely something we've missed until now and needs to be revisited as we have done with commitments, job search, skills translator, and resume builder. 

OR - Since there is not much going on on this page you linked to, do you simply want to use the existing one as is? 

And @rcarthur please escalate if your log in is not working to @ayaleloehr or @cfeeney-va . You should be able to log in through linkedin or google pretty easily.

**Comment by rcarthur** [comment]
@emilyville yes, no need to alter the page that already exists.  https://employment.vets.gov/employment/veterans

Best to keep it simple.  

I was able to log in today NP.  Thanks!

**Comment by emilyville** [comment]
Awesome! I am going to change the title of this issue reflect that. 

the things that need to happen are
- remove this page in vets-website
- update all links to it to go into VEC for 
  - /employment/veterans and/or /employment/favorites 
- and add them to the rakefile

@ayaleloehr I think they will be...
/employment/veterans
and/or 
/employment/favorites

Anything else we need to do to make this change?

**Comment by ayaleloehr** [comment]
@emilyville only comment is that `/employment/veterans` takes you to the "search for veterans" page whereas `/employment/favorites` takes you to the "see your favorited veterans" page. I don't really think there should be any links from vets-website to these pages, as they only show up if you're logged in. I think the links from vets website should go to `employment/employers` which will then let employers log in and search for Veterans or find ones they have favorited?

**Comment by emilyville** [comment]
@ayaleloehr that sounds right. In that case it's just deleting this page that needs to happen and keeping its presence about the same in employment section - but I'll need to compare it with the ia doc to be sure.
