### ISSUE TITLE
Purpose of Callout Boxes

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#1751]
Purpose of Callboxes:
ex.
Ways to Prepare
Who this effects
Before you start

https://employment.vets.gov/employment/job-seekers/less-than-one-year/

**Comment by gnakm** [comment]
@emilyville Would love feedback!

**Comment by emilyville** [comment]
I think that's a good start - we use them much more freely elsewhere, but it makes sense to break it down that way going forward. 

For example, I like this, but it doesn't fit that mold: https://www.vets.gov/disability-benefits/apply-for-benefits/
Applies halfway - but not for "Here’s what happens once you’ve filed your claim" section


It would be great to get more specific than the playbook's:
Callout Box

> Callout boxes are used to highlight content areas and make pages easier to scan.

**Comment by gnakm** [comment]
Closing this because we have come to a consensus about how to use callout boxes.

**Comment by emilyville** [comment]
Adding on (since I think @gnakm were typing at the same time and I already wrote it!) I think our templates are accounting for an upgrade in how to show important information with more fidelity. 

I don't think we'll be placing effort in going backwards and removing call out boxes, however we have heard in usability testing that users are skipping over content in blue boxes thinking it's an ad.
