### ISSUE TITLE
Need side call out box for VR&E benefit

### ISSUE THREAD

**Issue by rcarthur** [department-of-veterans-affairs/vets-website#2048]
https://vets-website-pr-1801.herokuapp.com/disability-benefits/claims-process/claim-types/predischarge-claim/

@mariana-almeida 

Need a side box with the following language:
"[Vocational Rehabilitation and Employment(VR&E)](/vre) services may be available to you while you're waiting to be discharged. To access VR&E programs, you may be screened via the Integrated Disability Evaluation System (IDES) by your physician. The first step is to file a predischarge disability claim."

The title of this box should be "Seriously Disabled?"  (instead of "Questions")

This call out box should look like the one on this page - and should be on the upper right part of the page:
https://www.vets.gov/disability-benefits/conditions/exposure-to-hazardous-materials/agent-orange/c-123/

**Comment by rcarthur** [comment]
https://vets-website-pr-1801.herokuapp.com/disability-benefits/claims-process/claim-types/predischarge-claim/

@kantrowitz  - is it possible to justify the tex in the call out box to that it doesn't look quite so ragged.

**Comment by mariana-almeida** [comment]
@rcarthur I would not recommend right justify because it messes with readability of text. The text in the box looks long. Here's my edit: 

"After you've filed your predischarge disability claim, learn about which Vocational Rehabilitation and Employment (VR&E) services may be available to you while you're waiting to be discharged. 

To access VR&E programs, you may be screened via the Integrated Disability Evaluation System (IDES) by your physician."  <-- I'm still not clear about the need for this sentence, Ric. Can we abandon it?

Question to Ric - what is a servicemember eligible for? what section should they read after they have done the disability predischarge claim?

After we're done deciding on this box, we need to remove this from intro paragraph (blue font area) because it's not duplicative: "You may be screened via the Integrated Disability Evaluation System (IDES) process for access to Vocational Rebilitation and Employment (VR&E) programs before you separate."

**Comment by rcarthur** [comment]
@kantrowitz  - do you have this for action?

**Comment by kantrowitz** [comment]
Circling back around to this later today.

On Thu, Apr 21, 2016 at 3:06 PM, Ric Arthur <notifications@github.com>
wrote:

> @kantrowitz <https://github.com/kantrowitz> - do you have this for action?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/vets-website/issues/2048#issuecomment-213072220>
>



-- 
Tiby Kantrowitz
tiby@thesocompany.com
201-401-0133

**Comment by kantrowitz** [comment]
Please take a look and tell me what you think.

**Comment by kantrowitz** [comment]
Let me know when/if to remove this: After we're done deciding on this box, we need to remove this from intro paragraph (blue font area) because it's not duplicative: "You may be screened via the Integrated Disability Evaluation System (IDES) process for access to Vocational Rebilitation and Employment (VR&E) programs before you separate."

**Comment by mariana-almeida** [comment]
Yes, you can remove it. Did you get my latest text changes? Here they are once more:

I think we need to break up that text even more - here's my attempt with numbering.

In the box:
1) [Apply for disability benefits] (disability-benefits/apply-for-benefits/), even before you're discharged.

2) Consider [applying to Vocational Rehabilitation and Employment (VR&E)] (/vre/apply-vre/) services immediately, so you can discover any helpful vocational services  available to you while you're waiting to be discharged. 

@rcarthur I think we need to delete this part: "Note that to access VR&E programs, you may be screened via the Integrated Disability Evaluation System (IDES) by your physician." It lacks context...

**Comment by kantrowitz** [comment]
@mariana-almeida
