### ISSUE TITLE
Veteran Crisis Line (VCL)

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#2082]
Mockup per call w/ VCL team to add 2 links to vets.gov homepage. goal is to enable Veterans to easily text and chat from both desktop view and mobile.

1. link to text:(https://www.veteranscrisisline.net/App_Themes/DefaultTheme/Images/TextTermsOfService/TextHelpButton.png)

https://www.veteranscrisisline.net/TextTermsOfService.aspx

2. link to chat: https://www.veteranscrisisline.net/ChatTermsOfService.aspx?account=Veterans%20Chat

right now, on mobile you can't get to the content page for Veteran crisis line (https://www.veteranscrisisline.net)--you can only click on yellow box and you get the phone number.

also, VCL has requested that the link be moved to top of page or someplace more prominent on page if possible.  pls. consider in context of other homepage changes we are making based on Veteran research:) note: nothing has been committed to them in terms placement.

@emilyville

**Comment by maryannbrody** [comment]
Hey @gnakm -- do you have time to take this on? We can chat about the actual best solutions for implementation and UX -- and then just need a simple mockup to show to the stakeholders. Aiming to get it wrapped up by next week if we can just to get it off the list. 

cc @emilyville

**Comment by Drakenhart** [comment]
@gnakm, @emilyville, @maryannbrody 

Could we  out here is cyber space get a peek at it as well if you get good feedback? I'm sure many of us have to figure out where to put it as well and that would be very helpful! :)

**Comment by gnakm** [comment]
@koconnor719 This actually came up in our design session this week and I would like to take this on. @maryannbrody I could mock some ideas up and check in with you tomorrow and early next week (or chat first doesn't matter).

**Comment by gnakm** [comment]
@koconnor719 Please check out these mockups. The idea is for the expandable box to be anchored to the bottom of the page so that no matter where you are, it will always be available. 

![closed](https://cloud.githubusercontent.com/assets/13420618/14998571/8cd42ea2-1152-11e6-9eb9-20df0e3f66c9.png)
![expanded](https://cloud.githubusercontent.com/assets/13420618/14998573/8f2cfa9e-1152-11e6-9ee1-4cae1fbf7a1d.png)


Mobile Version
![mobile closed](https://cloud.githubusercontent.com/assets/13420618/14998449/f5ba1a86-1151-11e6-91be-de8e0208bcb8.png)


![mobile expanded](https://cloud.githubusercontent.com/assets/13420618/14998450/f8b72c92-1151-11e6-9e78-e03f6ba14dae.png)

**Comment by koconnor719** [comment]
looks great!  do you want to do a quick call w/ VCL people to show them?  i can set up for next week:)

**Comment by gnakm** [comment]
@koconnor719 Sounds good to me!

**Comment by emilyville** [comment]
I think we can close this as an issue, no? We need to do the work - but I suspect that will be something we need to break out into a smaller project.

**Comment by koconnor719** [comment]
sounds good!  we're already scheduled to meet w/ them wed!  thx. you guys are fast!
