### ISSUE TITLE
Playbook header is white

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#2220]
Please close if I'm missing something or this is intentional, but it seems odd to me that the header on the Playbook page is white, while it's blue everywhere else?

**Comment by emilyville** [comment]
This is intentional, pretty much #allthethings about the playbook are different. I will close for now, but one day we may treat the playbook more independently so it's less odd that it is different. 

I know @plusjeff has feels as well about this being not-veteran content on vets.gov. I'm actually of the mind this might be the best use case for a playbook.vets.gov.

**Comment by emilyville** [comment]
tagging @gnakm @angel for fun.
