### ISSUE TITLE
Facility Locator external link images are off

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#2267]
Looks like this in production currently:

![screen shot 2016-05-05 at 3 17 42 pm](https://cloud.githubusercontent.com/assets/4719765/15054292/9a36e99e-12d4-11e6-9a5a-c644b2c20d9b.png)

**Comment by webinista** [comment]
Adjusted the padding on those links so that it now looks like this: 

![with-external-arrows](https://cloud.githubusercontent.com/assets/354277/15054772/f518611a-12bd-11e6-9b81-b72ec068572d.png)

I know that isn't the originally-specced design, but the arrow is how we've been handling external links. @gnakm @emilyville care to weigh in here?
