### ISSUE TITLE
Add application name to auth logs and statsd for USiP monitoring

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/vets-website#22884]
As an engineer I would like to be able to identify issues with our USiP clients as quickly as possible.

In order to accomplish this I would like to capture statsd and logs that accurately reflect the authentication return rate of our USiP clients. The current logging and monitoring capabilities do not capture the application name included in the authentication request or return. We have a statsd called `api_auth_unified_callback` and `api_auth_unified_new` which do not seem to accurately reflect the authentication success or return. I do not know exactly why these numbers are not accurate.

**Comment by joeniquette** [comment]
You can find the current widget for this here: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?from_ts=1670498990245&to_ts=1670513390245&live=false&tile_focus=4221402593186009

**Comment by bramleyjl** [comment]
Can I get some more clarification on this? I did a [PR in June](https://github.com/department-of-veterans-affairs/vets-api/commit/5fd1d2333ca53d6fd488583db6b120b77371b86d) that added the USiP authentication & callback StatsD logging & includes the application as passed through the `application` param from the frontend.

My logging addition only covered SSOe, so that can be expanded to SiS.

**Comment by alyssagallion** [comment]
Joe looking for production logs today to build out DataDog component. Will close after.

**Comment by joeniquette** [comment]
confirmed new USiP stats are present. There does appear to be one number that is incorrect, the mobile one. Im going to close this ticket and create a new one if the issue is a bug. Its possible the timing window of the measure is off.
