### ISSUE TITLE
Design suggestion: Adding box-shadow to card text

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/vets-website#2309]
This may all be moot since it will change eventually, but: adding a slight `box-shadow` to the card text boosts legibility IMO. I don't want to just add it though without some sort of design review / approval. (You may need to click through to compare.

**With box-shadow** 
![screen shot 2016-05-06 at 12 38 22 pm](https://cloud.githubusercontent.com/assets/354277/15084367/cd663dc0-1387-11e6-9a80-3ea0a5f9cb31.png)

**Without**

![screen shot 2016-05-06 at 12 41 14 pm](https://cloud.githubusercontent.com/assets/354277/15084379/df1480b8-1387-11e6-8378-8bab8b59d20e.png)

**Comment by gnakm** [comment]
@webinista I see what you mean.

I am personally not a big fan of drop shadows and I don't think this will necessarily enhance legibility. This has never been said out loud but I'm assuming that vets.gov was going for a flat design style. If it's easier on the eye, we can play with longer subtle shadows (this may cause more overhead) @emilyville your thoughts?

**Comment by Drakenhart** [comment]
What should boost legibility more is a bit more letter spacing (see classic typography rules) to give the letter forms breathing room for the eye. 

The box shadow on the letters, especially as small as they can get, creates a subtle "strobe" effect. It's an optical illusion, but it causes the letter forms to pulse slightly due to the photons coming at the eye the way they do. Because it is screen based (direct light) and not print based (reflected light), the eyes have more work to do. This is more true with people who have poor vision. 

Does it make them "pop", yes. Does it make them more "noticeable", yes. But, if you consider a site that may have many cards on it (say more then 5), this effect of over-working the eye is increased.
