### ISSUE TITLE
Linked item displaying below bullet

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#2319]
https://www.vets.gov/employment/employers/support-veteran-employees/

Not totally sure what's causing this - something to do with starting a new list item with an external link?
![screen shot 2016-05-09 at 4 39 09 pm](https://cloud.githubusercontent.com/assets/1307774/15131443/c98ba31e-1604-11e6-8256-7436d290996b.png)

**Comment by webinista** [comment]
It's a CSS bug that's mostly caused by `display: inline-block` on the link, and the fact that the link text wraps.

**Comment by webinista** [comment]
@emilyville @gnakm here are two options for solving:

1. Removes `display: inline-block` so that the external link icon always sits after the link. Notice that the position of the bullet is _inside_ the list item, and the list item text wraps around the bullet.

<img width="789" alt="screen shot 2016-05-10 at 3 46 02 pm" src="https://cloud.githubusercontent.com/assets/354277/15164860/8bd022b2-16c6-11e6-898d-8cb13c3cc220.png">

2. Removes `display: inline-block` so that the external link icon always sits after the link. Also changes the `list-style-position` to it's default position (`outside`).

<img width="764" alt="screen shot 2016-05-10 at 3 46 22 pm" src="https://cloud.githubusercontent.com/assets/354277/15164859/8bcf3118-16c6-11e6-9d37-451ec4b504f4.png">

I'll deploy whichever you choose.

**Comment by emilyville** [comment]
@webinista let's go with the second one!

**Comment by Drakenhart** [comment]
@emilyville @webinista 

Just a side note:

I'm not sure what else CSS you folks have that may be interfering with this issue, but I've run into a similar issue before with a span-tag divided link. 

Maybe for future reference (?) instead of removing the css, we changed it to `display: inline` and it aligned properly. ^.^

**Comment by emilyville** [comment]
Thanks @drakenhart! We'll keep it in mind!
