### ISSUE TITLE
Card / type change leading change?

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#2373]
I'm wondering if we merged a few things simultaneously and our leading got a little snug in the cards?

Before:
![screen shot 2016-05-17 at 9 58 00 pm](https://cloud.githubusercontent.com/assets/1307774/15347904/a05ddc60-1c7a-11e6-97bf-fa76c2b509da.png)

After:
![screen shot 2016-05-17 at 9 57 51 pm](https://cloud.githubusercontent.com/assets/1307774/15347905/a05efdde-1c7a-11e6-8631-aa0500a028a1.png)

**Comment by Drakenhart** [comment]
The titles look fine, but the description text may not do so well with the leading reduction. I also like the increased padding, it gives better visual breathing room.

One curiosity: Why would you want to snug up the leading on the smaller text?

Veterans come from all walks of life, and age as anyone else does. The larger portion of the population (until they age out) are older veterans who may have weaker vision due to age and/or other complications due to their service. (Glaucoma for example). Even younger vets will eventually grow older and all of our body parts start having issues over time, including our eyes.

A good test of this (a trick I learned years ago from a professor):
* if you have glasses, take then off and move two-arms lengths away. 
* if you don't have glasses, squint a bit and move the same distance away as above.

Can you read it? If not it may need a touch more leading and/or size increase.

**Comment by angel** [comment]
@Drakenhart thanks for your feedback and tips! I think this was a bug. We're loosening back the line-height of the headings and keeping the leading of the smaller text as is. You can find the pull request [here](https://github.com/department-of-veterans-affairs/vets-website/pull/2374).
