### ISSUE TITLE
VEC 1:1 Assistance Content seems incorrect

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#2428]
The first  link on this page (to Veteran Employment Specialists) https://www.vets.gov/employment/job-seekers/one-on-one/ is supposed to provide Veterans with 1:1 assistance, but i think this link is wrong:

" Veteran Employment Specialists from the Veteran Employment Services Office (VESO) can help you find jobs in your area." this link goes to VA for Vets page--which is target to hiring mangers--not Veterans??  http://vaforvets.va.gov/hr/RVECS/Pages/default.asp (Veteran Employment Specialists
If you’re a federal hiring manager or HR representative with a position that needs to be filled quickly, VESO’s Veteran Employment Specialists (VESs) can work with you to find Veteran talent that meets your qualifications. Located in regions (VISN's) across the country, VESs can help you recruit the most qualified Veterans to your organization.)  

seems like we are taking Veterans in a loop that is not helpful and does not provide them w/ 1:1 assistance.   what is correct content for this?  i know VEC has 1:1 assistance resources for Veterans?

**Comment by mariana-almeida** [comment]
This is from User Voice? Sounds like a web person wrote it. :)

In any case, I think this is a valid critique. The link we used can be improved. 

We can use this one: http://vaforvets.va.gov/JobSeekers/Pages/default.asp (not this one: **http://vaforvets.va.gov/hr/RVECS/Pages/default.asp) I will start pull request.

**Comment by koconnor719** [comment]
i wrote it.

**Comment by rcarthur** [comment]
@mariana-almeida and @koconnor719  -  The link is actually "right." The stakeholder reviewed this in staging and asked only that this link be surfaced in a more prominent position.  

In the process of content creation, I noted to stakeholder that their site was very confusing for the exact reasons you mention, Kelly.  Apparently, Veteran Employment Specialists referenced on the VESO page are technically for **both** Vets and employers. (Hover over the "Stakeholders" tab on this page: http://vaforvets.va.gov/JobSeekers/resources/Pages/Training-and-Resources.asp - and you find the link to the same page.)

We asked the Stakeholder in early March for an updated list of counselors so that we could build a info page and link to that instead of their page but stakeholder did not supply this list and we ran out of time to find the final solution. Recommend we revisit this request with stakeholder and build that page. 

On a side note, Veteran Employment Specialists were inputed to @rickleegit as candidates for possible inclusion into the Facility Locator tool.  

BTW, this is a very small program - according to the VA for Vets page there are only 23 VES to service all of the Vets and concerned employers across the country.

**Comment by koconnor719** [comment]
thx @rcarthur !  this seems super confusing for Veterans looking for 1:1 assistance and feels like we are taking them in an endless loop of pages that aren't relevant to them. we have this as it's own piano key so it's highlighted on our site as Veteran 1:1 assistance--which doesn't seem like a good user experience. i'll leave to the content team and user research @maryannbrody  to review and figure out if it needs changing.

**Comment by rcarthur** [comment]
@mariana-almeida @maryannbrody @koconnor719  I'm adding this to a running list of pending Careers and Employment content revisions to discuss, including a couple notes that came out of the VR&E concurrence process. I'm also going to ping Dominic Ramirez at VA for Vets because I think they are in the midst of a re-design of their pages.

**Comment by rcarthur** [comment]
Update: I'm talking to the stakeholder webmaster to see if he can make any tweaks during the re-design that he's doing to make it smoother.

**Comment by koconnor719** [comment]
@rcarthur  what is the status of this issue?  is it closed yet?  unclear from thread above what the current status is but it's been open for a while.  what is next step--or if it's closed on our end--let's close it.  thanks:)

**Comment by rcarthur** [comment]
@koconnor719 - The problem was that the info was unclear on the va.gov site
(our page was correct) I worked with stakeholder - Dom Ramirez at VA for
Vets to fix the issue by adjusting content on his end.

Problem is solved. I will close out the issue.

**Comment by koconnor719** [comment]
Awesome!  ty:)

Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by rcarthur** [comment]
@maryannbrody Mary Ann - Please closeout issue. This was resolved (as of 2 JUN) through coordination with Va for Vets webmaster who altered language (on my request) to read:

"Veteran Employment Specialist are available by region to provide one-on-one assistance to Veterans looking for work and employers looking to hire."

on this page:
http://vaforvets.va.gov/hr/RVECS/Pages/rvecs-map.asp

Thanks so much!!

**Comment by koconnor719** [comment]
Great I'll close ty!!!!



Sent with Good (www.good.com)


-----Original Message-----
