### ISSUE TITLE
VEC resources title

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#2429]
on this page, is the title "Questions" accurate for the Coursera and LInkedIn resources?  why is it called "questions"--both of the links go to the actual Coursera and LInkedIn pages--they don't answer questions? shouldn't this be called Free Resources or something other than "questions"? not sure whom to assign this to for review and modification.  @gnakm 
https://www.vets.gov/employment/job-seekers/

![screen shot 2016-05-30 at 7 14 52 pm](https://cloud.githubusercontent.com/assets/13770771/15659594/fb864f58-269a-11e6-951e-60397e745408.png)

**Comment by gnakm** [comment]
@koconnor719 FYI @webinista  and I are on this.

**Comment by emilyville** [comment]
Is this from user voice - and If so can you tag the user voice issue?

**Comment by koconnor719** [comment]
Sure I'll try to get to this later.. The title is inaccurate since the links have nothing to do w questions



Sent with Good (www.good.com)


-----Original Message-----

**Comment by Drakenhart** [comment]
We had the same issue on our project and just re-titled it based on what the page needed. (If it was a list of resources that other design patterns just didn't fit, for example - we called it "Resources"). 

Sometimes it was an informational, non-global, alert-call out in regards to security as well that needed to be up higher on the page due to the sensitivity of the on-page information.
