### ISSUE TITLE
Remove "how we can we help"

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#2536]
Since launch in Nov 2015, we have contintued to get feedback from Veterans and other users that the "How can we help" yellow box at top of our site is very confusing example feedback #2535  ).  users think it's clickable (it's not).  it takes up valuable real estate on page; not clear what value this provides to users coming to the homepage?  it's also one of the most prominent things on the homepage given it's placement on the page, size, and that it's highlighted in yellow, but Veterans can't "do" anything with it..so it's not really aligned w/ the mission of the site.

can we pls. remove this--or  test this w/ Veterans?  there are other more valuable things we can put toward the top of the homepage (e.g., Veterans Crisis Line #2535 )).

it also appears that 1/3 of our homepage is just header..with the only "doable" thing for a veteran is search.

@gnakm @maryannbrody 

![screen shot 2016-07-03 at 1 04 45 pm](https://cloud.githubusercontent.com/assets/13770771/16546635/09b46198-411f-11e6-9d0d-fd965667b622.png)

**Comment by koconnor719** [comment]
@maryannbrody is there a schedule of research of when stuff like this will be reviewed?  :)

**Comment by maryannbrody** [comment]
Hi, @koconnor719 - We chatted about this a little bit last week, but I wanted to follow up. We are talking about potentially doing some A/B testing on VCL. Since the questions we have are really about placement (that is, is it getting seen at the bottom, or should it be on the top?), we'll get the right information using analytics and A/B testing. We don't have a plan to do an entire session to evaluate the link, but in our next site-wide usability test, we can make this a priority. @MissPaaj and I are meeting this week to talk about the research calendar for the next couple of months. We have a number of competing priorities, so it will just be a matter of making sure this fits in on a planned test for something else!

Here's the schedule (it will be updated later this week): https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Research/0.-Research-Process-Admin/Research%20Process.md

cc/ @staceylanger

**Comment by koconnor719** [comment]
This is not VCL?  :)  this is about the header on our site that says �how can we help� and it�s not clickable?  it�s super confusing I think.


Kelly O�Connor
VA Digital Service
kelly.o�connor@va.gov
202-299-4436

**Comment by maryannbrody** [comment]
@koconnor719 - this is changing with the updated homepage design. We should be able to close this.

**Comment by emilyville** [comment]
Closing for new design with different heading.
