### ISSUE TITLE
[508] Address issues from 08/01/2016 Scan

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2633]
Use the file below to work through 508 compliance issues:

[08_01_16_vetsdotgov_508.xls.zip](https://github.com/department-of-veterans-affairs/vets-website/files/394270/08_01_16_vetsdotgov_508.xls.zip)

**Comment by bshyong** [comment]
I'll get on this. By any chance do we have a list of the URLs that are flagged? I went through the spreadsheet and there are a few standards that might be difficult to track down, for example: 

![image](https://cloud.githubusercontent.com/assets/303289/17370334/81647888-5950-11e6-8175-df724f5c8ff1.png)

**Comment by crwallace** [comment]
@bshyong -- This is a better document with all of the URLs.

[08_03_16_vetsdotgov_508_violation.xls.zip](https://github.com/department-of-veterans-affairs/vets-website/files/399770/08_03_16_vetsdotgov_508_violation.xls.zip)

These are all of the actual violations that we need to address right now, but we also have potential violations that I would love if @melwoodard would take a look at and provide some feedback about addressing.

Potential violations ---> [08_03_16_vetsdotgov_508_potential_violation.xls.zip](https://github.com/department-of-veterans-affairs/vets-website/files/399776/08_03_16_vetsdotgov_508_potential_violation.xls.zip)

**Comment by bshyong** [comment]
Thanks for the resources. 

Question:
For fixes that require content, is it okay to take my best guess or do we need people to double check content?
e.g. image alt attributes, tooltips

**Comment by melwoodard** [comment]
@bshyong I took a pass through the violations, here's what I think we can improve on the visual side:

1. Change text link color from #0071BC to #0058A6
2. Change buttons with a background-color of #0071BC to #205493 (about 25% of buttons already use this color). FYI, looks like most buttons are <a> elements, but a few came up in Employment (Skills translator, Résumé builder) that are <span> or <input> elements. The only exception I think you should leave as-is for now is the search field button in the site header since the darker color gets muddy against the header background.

**Comment by bshyong** [comment]
Thanks for this @melwoodard. I'll make those changes

**Comment by Drakenhart** [comment]
@melwoodard @bshyong Might I suggest increasing the font size and boldness? It only fails if it is "normal text sized" but passed if the text is larger. Also a suggestion to add a bit more letter spacing between the letters as well.

That should solve that point for the search button in the header. :)

**Comment by melwoodard** [comment]
Thanks for the suggestions @Drakenhart! The text links are typically inline links in body paragraphs, so I think our best course of action there is the color change (it's quite minor), rather than break up the flow of a paragraph with bolder/larger link text.

Good point on the search button - the font-size here is actually smaller than what's in our guidelines for large buttons. @bshyong if you bump up the font-size on the search button to 1.9rem that may get us to compliance.

**Comment by bshyong** [comment]
I'm going to tackle vets.gov website changes in this PR, and open other ones in their respective repos.

**Comment by crwallace** [comment]
@bshyong -- For right now you also don't need check in with anyone about content changes. If I think its a major deal I will flag it in review.
