### ISSUE TITLE
Implement one consistent table style across the site

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#2692]

**Comment by melwoodard** [comment]
The [USWDS bordered table](https://standards.usa.gov/tables/) style should be used across vets.gov. This affects:

- [GIBCT Institution detail page](https://www.vets.gov/gi-bill-comparison-tool/institutions/profile?military_status=veteran&spouse_active_duty=no&gi_bill_chapter=33&cumulative_service=1.0&enlistment_service=3&consecutive_service=0.8&elig_for_post_gi_bill=no&number_of_dependents=0&online_classes=no&source=home&institution_search=31808047&facility_code=31808047&)
 - [ ] Benefits Calculator - table with $ totals
 - [ ] School Summary
 - [ ] Historical School Information
- [Survivors and Dependents' Assistance](https://www.vets.gov/education/gi-bill/survivors-dependent-assistance)
 - [ ] Compare DEA and Fry Scholarship Benefits table
- [Employer Commitments](https://www.vets.gov/employment/commitments)
 - [ ] Commitments table

**Comment by bshyong** [comment]
Update: I'm going to fix this issue and https://github.com/department-of-veterans-affairs/vets-website/issues/2693 in a single PR.

I did some investigating today and found out that the usage of Foundation in the `va_common` is clobbering a lot of the USDS styles. My plan of attack is to break out Foundation so that we can import Foundation styles selectively (and remove/comment out ones we don't need, e.g. tables). I'll publish a new version of the gem with those changes and then upgrade all of our existing apps.

**Comment by bshyong** [comment]
`va_common` has been updated and published—there are a couple PRs out in the wild across the various apps but once they are merged we should be good to go
