### ISSUE TITLE
to.be.true and to.be.false don't work in specs

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/vets-website#2796]
when i put
```
expect(true).to.be.false;
```
in a test it passes
@jbalboni mentioned he had the same problem

it's the same syntax as the examples in the chai documentation. also i went to a random already existing test and replaced trues with falses and vice versa and the test still passed.

anyone know why this is happening?

**Comment by jbalboni** [comment]
@lihanli I looked around a bit and I think it's because we're using [dirty-chai](https://github.com/prodatakey/dirty-chai) in places (everywhere?). It expects you to do something like `expect(true).to.be.false();`

This seems super confusing without some kind of linter rule enforcing the `()` on the end. @alexose, do you know the reasons behind using dirty-chai?

**Comment by jbalboni** [comment]
If I remove dirty-chai I don't get any new failing tests, which is a relief. And then things work as expected with the expect statements.
