### ISSUE TITLE
Review component

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#2824]
Similar to HCA review

**Comment by goldenmeanie** [comment]
HCA version has some unpredictable button behavior.
- Next button is not always visible
- Next button sometimes doesn't take you where you'd expect
- Edit button can disappear in some circumstances

**Comment by jbalboni** [comment]
I'm going to write out how I think this component should be working to get a better handle on where the weirdness might be:

Each page of the form has two state variables: complete and verified. Complete is set when all the fields are valid and you have moved to the next page of the form. Complete will be set to false if you click the Edit button for a particular part of the form. Verified is set when you click the Next button for that form page on the review page.

The editable form fields for a particular page are shown when the page is not complete. The table of field values is shown when a page is complete, not verified, and the previous page has been verified. Otherwise, nothing is shown.

The Edit button is shown when the page is complete or verified, unless the page is complete, not verified, and the previous page is also not verified.

**Comment by goldenmeanie** [comment]
Does HCA have the concept of complete and verified? My understanding was that it did not _require_ review but it was an option.

**Comment by jbalboni** [comment]
It does, but yeah, I don't think you have to verify everything. The form just needs to be valid. Same would apply to edu-benefits, too.
