### ISSUE TITLE
Confirmation Number - EDU

### ISSUE THREAD

**Issue by J-Quag** [department-of-veterans-affairs/vets-website#2902]
Want to see how we're going to do Confirmation numbers and if we can go back and see that information if necessary. 
(question coming from EDU)

**Comment by lihanli** [comment]
we can use the id from the table, or we can make a uuid and use that

**Comment by lihanli** [comment]
can someone contact VA and give them a confirmation number and get the information from just the number? or are they asked for the number plus like birthday or SSN or some other verifying information? if it's just the number we should add a uuid or use a uuid to replace the primary key. otherwise we can do something like vets-gov-22-1990-#{model.id}

**Comment by akainic** [comment]
Duplicate ticket
