### ISSUE TITLE
Address component changes

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#2980]
The Address component doesn't appear to handle partially filled in addresses if the address isn't required. Should update this to prevent that. So far, the json schemas we've been using require street, city, and country.

This will affect HCA potentially, since the component is shared.

We're also not sure about how the address component is handling foreign addresses and apo/fpo addresses: 
- Do we need to had some custom behavior for apo/fpo addresses?
- Do we need to replicate HCA's requirement that you select "Foreign Country" as a state for foreign addresses?

**Comment by jbalboni** [comment]
@markolson @lihanli Do you you guys have any background on the two bulleted questions above?

**Comment by lihanli** [comment]
i'm not sure what the VA requirements are. maybe one of the product people knows? https://github.com/department-of-veterans-affairs/edu-benefits-team/blob/master/README.md

**Comment by markolson** [comment]
I would probably not re-use the HCA component, to be honest, as it's tightly coupled with some of that requirements. I think we can shoot an email over to Shay Norton for clarification about the address. How does VONAPP currently handle foreign or non-state addresses?

**Comment by lihanli** [comment]
![vonapp](https://cloud.githubusercontent.com/assets/830084/18557976/279aeaba-7b3f-11e6-9a3f-9a0e5fbc2044.png)
vonapp has a location option which includes domestic/foreign/military overseas
if you select foreign then it adds a new country field

**Comment by jbalboni** [comment]
@markolson If we redid the Address component, would you want the address schema to be different, too? Or does what we have defined now work for domestic, foreign, and apo/fpo addresses?

**Comment by markolson** [comment]
I think my one concern is the difference between zipcode/postalcode province/state, but that's solvable with a simple `state || province`. I would like it to be as simple, and reflective as possible though, so maybe we can just go with `postalCode` and `stateOrProvince`?

**Comment by akainic** [comment]
Weighing in late here, but from a UX perspective I've been wanting to change HCA's Address component for awhile anyway. I don't think it's a good experience that the fields default to the foreign address fields (province and postal code) and then change to the domestic address fields (state and ZIP code) if you select "United States" as your country because this prevents the autofill from working.

<img width="582" alt="screen shot 2016-09-21 at 11 30 02 am" src="https://cloud.githubusercontent.com/assets/3886085/18717717/d033fed8-7fee-11e6-8002-d032a168d1b8.png">

<img width="587" alt="screen shot 2016-09-21 at 11 30 09 am" src="https://cloud.githubusercontent.com/assets/3886085/18717735/dff21ec2-7fee-11e6-8c4a-cbe1299879c4.png">

It seems like we can create a common Address component for both forms, the only difference being the education form allows you to also select a military base for the address. What if we have a dropdown that first asks you what country you're in, and based on that we show the relevant address fields? Would love @cweber and @goldenmeanie to weigh in as well.

**Comment by jbalboni** [comment]
Based on our (@cweber @goldenmeanie @akainic) conversation today, these are the likely changes:

1. Move country to the top of the address fields and default it to United States.
2. When a user enters a city of APO/FPO/DPO, restrict the state options to military base options (AE, AA, etc).
3. If the above doesn't work, added the military base options to the states dropdown.
4. Have a single set of fields regardless of the country: street (maybe street2?), city, state, postalCode, country.

**Comment by jbalboni** [comment]
@markolson Does number 4 above seem ok on the backend?

**Comment by akainic** [comment]
@jbalboni I'm a little nervous about filtering the dropdown list based on if the user enters APO/FPO/DPO, as that seems a little fragile. Do you imagine that before they enter a city the state list includes the military base options, and then if they enter APO/FPO/DPO it filters the list? Or the state dropdown options are changed entirely if they enter that for the city? I would prefer to include the military base options in the state dropdown from the beginning in case they enter lowercase or something else that doesn't pass our check. Thoughts?

**Comment by jbalboni** [comment]
I agree that we should include the military base options in the state list no matter what. We can try out filtering the list for API/FPO/DPO and see how we feel about it. It seems like a nice to have, rather than a requirement.

**Comment by markolson** [comment]
@jbalboni (4) works great for me
