### ISSUE TITLE
Add last updated to meta data for each content page on the site

### ISSUE THREAD

**Issue by dannychapman** [department-of-veterans-affairs/vets-website#3277]
Add meta data for last-updated for each content page on Vets.gov 
Ideally, this should use the article:modified_time - datetime Open Graph format. 

See: http://ogp.me/ for reference. 

Looks like the simplest way to accomplish this might be with metalsmith-updated?

**Comment by goldenmeanie** [comment]
Do you mean a meta tag or human visible in the page somewhere?

**Comment by dannychapman** [comment]
Meta for now.

**Comment by carlmjohnson** [comment]
One difficulty will be that as far as I know, git/Github has no concept of the date a file was modified (that's why it won't prompt you to commit if you change a file and then undo the change). To get around that, we'd need some meta data in the YAML front matter like `date: 2016-11-11` but the content people would be responsible for remembering to add it to pages and manually update it when they make changes. It can be done, but it's a complication.

**Comment by dannychapman** [comment]
I could also see that metal-smith updated might only take affect for changes generated when running locally. Perhaps we make it a manual part of the merge to master process?

**Comment by carlmjohnson** [comment]
The code for [metalsmith-updated](https://github.com/gchallen/code.metalsmith-updated) is interesting. How it works is by saving a secret file called .updated.json in the project and modifying it whenever it sees a new file or a file changes its contents. We could use it, but it would need to be part of the check in process in order to get accurate created/modified dates. We'd need a Github test that verifies that everything in the .updated-json is accurate and rejects commits that don't include it when it changes.

**Comment by dannychapman** [comment]
@carlmjohnson Sounds like it's worth a try. Thoughts?

**Comment by carlmjohnson** [comment]
I don't know who has permission to do Github hooks. @crwallace do you know who set up the other hooks for vets-website?

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
