### ISSUE TITLE
Update text on "Work in Progress" page

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#3282]
in anticipation of the Veteran's day launch, we need to update this link prior to Veterans Day "work in progress" to be more relevant.  presently it goes to a design page which doesn't really explain how it's a work in progress? and it seems to be targeted to front end coders?  i think this message needs to be targeting Veterans and stakeholders like VSOs coming to the site.

<img width="485" alt="screen shot 2016-10-06 at 10 45 43 am" src="https://cloud.githubusercontent.com/assets/13770771/19157066/10407e42-8bb2-11e6-9328-0bf4cfe6a5af.png">

goes here:

<img width="1394" alt="screen shot 2016-10-06 at 10 46 27 am" src="https://cloud.githubusercontent.com/assets/13770771/19157098/2b08f43e-8bb2-11e6-9633-3991d4b55997.png">

**Comment by koconnor719** [comment]
@maryannbrody @emilyville @staceylanger 

can we have language that highlights the following:

- the site is a work in progress; it is not yet 100% complete
- it's being built based on Veteran feedback
- vets.gov was launched in 11/2015 and we've been gathering Veteran feedback since then.
- we build a small portion / feature and then we go see what Veterans think
- our goal is to have all Veteran features and content on vets.gov by Spring 2017.

**Comment by maryannbrody** [comment]
@emilyville and I just chatted about this -- we're going to ask Anitra (USDS UX writer) to peek at this and get us a draft!

**Comment by emilyville** [comment]
Any update on this @maryannbrody or @AnitraAppa ? Would love to make this shorter or move it to the footer. cc @angel

**Comment by AnitraAppa** [comment]
Thanks for following up! Let me know if this works @emilyville @maryannbrody @koconnor719 

## **More to come**
We're building Vets.gov with lots of feedback from Veterans like you. To make sure these services are useful and accessible, we're adding new things one at a time. This allows us to see what you think before we add more. We hope to have all Vets.gov services and content up and running by Spring 2017. If you have feedback, please [let us know](https://veterans.uservoice.com/).

**Want to help?**
All of our front end design resources are open source and available on GitHub for improvement. 

---
Notes:
- Is there any more info we can share about the additional resources we plan to add to the site or do we want to keep that under wraps since it could all change/this is a work in progress disclaimer?
- If we keep this text at the top of this page, then I think it still makes sense to have a call out for developers, just made it shorter and separated it from the main message. If it's moving to the footer, let me know, will adjust. 
- Added link to the feedback forum, let me know if there's a different feedback option we want to highlight here.

**Comment by jcmeloni** [comment]
@koconnor719 @maryannbrody @emilyville @AnitraAppa is the content above the content you want to appear on the WIP page? I don't think there's been action to change it. LMK.

**Comment by koconnor719** [comment]
looks great to me!! one minor update--can we pls. include the feedback@va.gov email address for research here?  @maryannbrody i think that's a better call to action than the feedback forum--if they are a Veteran?  will defer to research team:)   thx @AnitraAppa

**Comment by maryannbrody** [comment]
Sounds great! @AnitraAppa -- the message is just that if people are interested in participating in a feedback session to make vets.gov as helpful and as easy to use as possible, they can email feedback@va.gov and a member of our research team may follow up about participating. 

Feel free to edit as you see fit! Thanks

**Comment by emilyville** [comment]
Any thoughts on keeping it in the header or making that copy shorter? I'd love to bump it down to the footer or somewhere lower on the page, potentially as an alert only on the homepage.

**Comment by AnitraAppa** [comment]
@koconnor719 @maryannbrody - Good call! Edited:

### More to come
To make vets.gov as useful and accessible as possible, we're building this site with lots of feedback from Veterans like you. We add new things one at a time to see what Veterans think before we add more. We hope to have all vets.gov services up and running by Spring 2017. If you have feedback, please email us at feedback@va.gov.

**Want to help?**
All of our front end design resources are open source and [available on GitHub](https://github.com/department-of-veterans-affairs/vets-website) for improvement.

---

Notes:
- Link "available on GitHub" to https://github.com/department-of-veterans-affairs/vets-website
- Lowercase "vets.gov" unless it's starting a sentence

**Comment by AnitraAppa** [comment]
@emilyville Just saw your other comment -- +1 to moving this down to the bottom of the page. If we want to make it shorter, I could take out the 2017 line, but I think the other copy should stay.

**Comment by AnitraAppa** [comment]
Edited - removed 2017 line:

### More to come
To make vets.gov as useful and accessible as possible, we're building this site with lots of feedback from Veterans like you. We add new things one at a time to see what Veterans think before we add more. If you have feedback, please email us at feedback@va.gov.

**Want to help?**
All of our front end design resources are open source and [available on GitHub](https://github.com/department-of-veterans-affairs/vets-website) for improvement.

---

Notes:
- Link "available on GitHub" to https://github.com/department-of-veterans-affairs/vets-website
- Lowercase "vets.gov" unless it's starting a sentence

**Comment by koconnor719** [comment]
Awesome! Ty😀



Sent with Good (www.good.com)


-----Original Message-----

**Comment by jcmeloni** [comment]
@emilyville @maryannbrody @koconnor719 Could someone confirm if this is to replace the Philosophy chunk, is an addon to that, or is an addition under the cards, or other?  Thanks!

**Comment by emilyville** [comment]
@jcmeloni let me take the ball on this and figure out what we should do here. Assigning to self.

**Comment by ayaleloehr** [comment]
Assigning @suzchap to decide if this should be worked on or closed.

**Comment by suzchap** [comment]
I am planning a bigger overhaul of the playbook so I don't want to do too much work on this right now so here's what I propose:

1. change the header's "work in progress" link to go to https://www.vets.gov/playbook/ (instead of https://www.vets.gov/playbook/design/) which matches the purpose of link better.
2. change "Building a single unified digital experience for all veterans." to "Building a single unified digital experience for all veterans, one piece at a time."
3. on https://www.vets.gov/playbook/, fix "accessibility guide" link at bottom of page to go to https://pages.18f.gov/accessibility/

I ran these by Mary Ann and Kelly plus Amy for wording help.

@ayaleloehr Are these things I should be able to change and submit as PR? If so, could you give me a quick tutorial?

**Comment by jcmeloni-usds** [comment]
@suzchap you should be able to do this.  I can also just do it if you want.  LMK.

**Comment by koconnor719** [comment]
sounds good!! the only other thing we talked about was having 1-2 sentence on how vets.gov is still a "work in progress" right?

**Comment by suzchap** [comment]
@jcmeloni thanks but I should know how to do this. I just need someone to show me. 

@koconnor719 Adding "one piece at a time" to the top sentence was Amy's temporary solution for this. Is it too subtle? I'll plan to do something more explicit in the next iteration I'm already working on if that helps.

**Comment by jcmeloni-usds** [comment]
@suzchap you bet. sorry i'm not in the office today. if you aren't shown before the next time you see me just grab me. sorry i can't screenshare.

**Comment by koconnor719** [comment]
@suzchap i think we may need a bit more than that?  veterans (like my dad) go to vets.gov and they don't understand what's happening b/c it's only partially done?  can we say a little more like we are currently in progress of moving things over and should be done by later 2017?  what do you think?  otherwise it just looks like a partial thing?

**Comment by suzchap** [comment]
@koconnor719 Ok, I'll take another pass at working this in. Thanks!

**Comment by koconnor719** [comment]
what do you think????

**Comment by koconnor719** [comment]
@suzchap i'm closing this as i think it's old and done:)

**Comment by koconnor719** [comment]
@suzchap can i just close this?

**Comment by suzchap** [comment]
I pulled the still relevant bits into a new issue for additional work. Closing this one now. 

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/4586
