### ISSUE TITLE
Question for Shay: incomplete HS graduation date

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#3293]
Question for Shay: For one applicant, the sample spool file has just a year listed for date of when they earned their high school diploma, but our form doesn’t allow only a year. Is this something we should allow?

**Comment by jbalboni** [comment]
@goldenmeanie @akainic  @cweber  Do we have a decision on this?

**Comment by cweber** [comment]
We have another issue to address this, but had it in the backlog. #3261

I didn't remember that VONAPP currently allows only year, or only month-year.

Our approach would only solve for not requiring day.

**Comment by akainic** [comment]
We should allow dates without day and month selected, unless it is the current month and current year?

**Comment by akainic** [comment]
Further clarification needed from Shay

**Comment by cweber** [comment]
From @J-Quag:

RE: HS Date question
Norton, Shay, VBAVACO 2:40 PM
**We usually just need the month/year**
They have to have the HS grad or equivalent before getting benefits.
A comment in VONAPP at one time was that the person applying didn't know the day.
I think we changed it to just require month/year or put in the help to use the first or last day of the month...

**Comment by cweber** [comment]
**usually** is a loaded term, but this is what we've heard from Shay several times.

We have a proposed solution that deals with implementing this in a technical way. (see #3261) That's the preferred method, so that we can stress out the least amount of people, but still collect the necessary information from those that need to provide more.

 - The other options are letting the edge cases slip through the cracks (resulting in development) and only displaying month/year
 - Displaying all fields, but not requiring the day field. (the subtly of required fields, especially in a fieldset like that makes me think this won't ease the stress for people that don't know their day.)

I'll email Shay to clarify one more time, but I think if we are able to take care of it he way we describe it in #3261, that would work.

**Comment by cweber** [comment]
Resolved!

**Front end**: Shay says month and year are fine.
**Back end**: "...VCEs are used to seeing the full date. Could we send the 1st of the month in the spool file?"

(Is there a label I can use to make sure @markolson and @lihanli add this to their to do?)

**Comment by goldenmeanie** [comment]
So. That's removing the day field, month/year only, right? 

I think we should only send the data entered. Manually adding the 1st seems as likely to create a problem as not in cases where the day would matter.

Do we have any numbers about how edgy this edge case is?

**Comment by cweber** [comment]
Removed myself as the assignee on this. We have the go ahead from Shay to display the date as month/year only.

**Comment by leannammiller** [comment]
@alexose - checking status on this

**Comment by leannammiller** [comment]
@alexose lil' poke for status on this

**Comment by jbalboni** [comment]
@leannammiller This is now done with #3592.
