### ISSUE TITLE
Login React app is doubling the size of our React app css files

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#3312]
Right now, the output css size for most of the React apps is about 1.2mb. This is really big and the culprit appears to be the addition of `require('../login/login-entry.jsx')` to the app entry files. If I remove that line, the css output for most of the apps goes down to around 650kb.

I think this is because the login entry page is requiring its own css file, which includes the style.sass file that all the other sass files also include. 

We should be able to fix this by including login.sass in style.sass, instead of importing it in the entry jsx files.

**Comment by jbalboni** [comment]
@bshyong or @crwallace, would this be something you could look into?

**Comment by ayaleloehr** [comment]
Related, with thoughts on de-duping FontAwesome and removing inline SVGs: https://github.com/department-of-veterans-affairs/messaging-fe/issues/94

**Comment by bshyong** [comment]
@jbalboni yikes I'll look at this today

**Comment by bshyong** [comment]
Some proposed solutions:

1.  Remove the common `style` import from `login.scss`. Change variable reference `$white` to hardcoded `#fff`. If you are requiring the Login component, also make sure to require the login scss. More flexible solution, but requires additional `require` statements
2. Import the `login` styles in the common `style` scss per @jbalboni suggestion. Straightforward solution, but it means that the `login` css is always included sitewide. This solution is the simplest if we expect the login styles to be needed on every page.

Unfortunately, Sass does not (yet?) have Less-style [reference imports](http://lesscss.org/features/#import-options-reference). Importing a scss file twice means that it _will_ appear twice in the compiled output. This is currently expected behavior in Sass, so we need to be careful about organization and make sure we aren't importing stylesheets multiple times.

I am leaning towards solution 2

cc @crwallace

**Comment by webinista** [comment]
Small nit-pick: `$white`/`#fff` should be `$color-white`, assuming that we're using USWDS variables.

**Comment by bshyong** [comment]
@crwallace ^ thoughts? looks like a simple fix and easy win to decrease build bloat
