### ISSUE TITLE
Blank records for Employment and Education should have placeholder text

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#3356]
Currently we allow users to submit blank entries for Employment and Education history. This is good. But we're also allowing users to add a new record without completing any data. 

- We should require at least one field to be filled before they add a new record. If not true, scroll up an display an error that says, "Fill out this record before adding a new one." (Or maybe just scroll up with no message?)
- If an entry is saved by adding a new one but has minimal content (none of the preview text), display placeholder text:
"This entry may be missing information"
- Format preview text to match Military History with 

**Name of School**
Dates attended

and 

**Main job**
When did you do this work?

![screen shot 2016-10-13 at 12 26 49 pm](https://cloud.githubusercontent.com/assets/417657/19357960/d0343d26-9141-11e6-915d-e96d2532dd2d.png)

**Comment by akainic** [comment]
I was able to fix the 2nd and 3rd issues, but the 1st one is tricky because we're having to handle 2 different sets of validation logic for 2 different situations:
1. A completely empty education period is invalid if trying to add another education period
2. A completely empty education period is valid if trying to proceed to the next page

The way we have built our validation logic makes it hard to separate these 2 concerns. I'm going to create a separate ticket for the 1st issue so we can refactor the way we're handling the validation logic since this is a bigger task.
