### ISSUE TITLE
New Vets.gov Homepage for 11/11

### ISSUE THREAD

**Issue by angel** [department-of-veterans-affairs/vets-website#3372]
Here's what the new homepage will look like. Please feel free to give any feedback below.

**Comment by emilyville** [comment]
FAQ:

**What popular links will be featured on the homepage?**
For now we're going with these - but they will hopefully change often, and they might even change before 11/11

**Comment by MarinaMartin** [comment]
💯

**Comment by melwoodard** [comment]
Curious if there's been any discussion around the treatment of the 3 stacked banners/navs at the very top of the page? They serve valuable functions, but visually feel like a lot to get through before you get to the meat of the site.

**Comment by goldenmeanie** [comment]
I appreciate the difficulty of doing this work so quickly. I appreciate the great care being taken to bring some new elements to the site while not making too abrupt a change. 

A few questions and observations, in no particular order:

1. What is the effect of logging in to the site? My perhaps outdated understanding is that each tool must be logged into individually. How does being logged in change the site for a visitor?
2. It seems like a high ratio of decorative to actionable screen real estate. Could you talk about what’s driving the relative scale and stack order?
3. I like the idea of bringing actions we know visitors are likely to be looking for to the front. Have you explored any approaches that surface these actions within the relevant cards? The card/tile approach seems to be supported by your research, maybe they can be enhanced rather than adding competing elements to the page? This might pay dividends later by reenforcing the categories.
4. The portraits are beautiful! Are the crops affected by screen size? They look more square in the smaller screen layout, do they scale smoothly or are they indexed to specific breakpoints? 
5. I wonder if a single-line tag line over the portraits might create less overlap with faces? As it wraps on smaller screens it might be worth moving the tag in-between the rows or below the images to fight the overlap?

It’s a challenge but this is a great team to meet it. Thank you for sharing, I’m looking forward to seeing this develop!

**Comment by emilyville** [comment]
I'm closing this and moving it here https://github.com/department-of-veterans-affairs/vets.gov-team/issues/346
