### ISSUE TITLE
Google Analytics integration

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#3406]

**Comment by goldenmeanie** [comment]
What needs to happen here?

**Comment by akainic** [comment]
I need to configure Google Tag Manager for education, might be able to ask for help from an analytics person for that

**Comment by ayaleloehr** [comment]
Dan and Bob from Ad Hoc should be able to help you here.

**Comment by leannammiller** [comment]
@akainic @goldenmeanie  - where do i find info about the questions we're asking of google analytics? bob wants me to work with someone named dan on this.

**Comment by akainic** [comment]
@leannammiller do you mean what should we be tracking in google analytics? I think that's a question Dan Hoicowitz should be able to answer, but quick thoughts I have on it are:
1. General arrivals and page view counts for each major stage of the application (landing, intro, submit)
2. How many people click on the submit button
3. How many successful/failed submissions there are
4. Where we're losing people along the way (drop-off rate at each page)

**Comment by leannammiller** [comment]
@akainic would you like me to take this off of your plate?

**Comment by robertfairhead** [comment]
@akainic i setup basic education application stats into google analytics this morning. i'll review with Dan at 11a.

@leannammiller let's talk later today and I can catch you up. Dan has an analytics template you can work through.

**Comment by robertfairhead** [comment]
@akainic from your list above items 1,2,4 we have setup via google tag manager. caveat on 2 is that any click on the submit button will be counted even if the form fails validation and doesn't send. onClick still fires on those cases.

for item 3, we can do it via tag manager but after investigating a little bit i think that's a bad idea. basically we'd have to monkey patch fetch() to add in the google datalayer pushes via tag manager. the better solutions are either:

A) add in the couple lines of code into the react app handlers (this is how HCA does it)
B) track the success/failure on the server side instead of via GA

if you want to go with option A, i put together the couple line PR for it or send the lines to Jeff for him to integrate.

**Comment by leannammiller** [comment]
@robertfairhead @dsh32va we will go with option A. Bob, do you mean that you wrote the code already?

**Comment by leannammiller** [comment]
if not, @akainic will do it.

**Comment by akainic** [comment]
Closed by #3462
