### ISSUE TITLE
Military addresses aren't correct

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/vets-website#3423]
(Get details from Stephanie...she'll be emailing what needs to appear on the screen for APO, etc.)

**Comment by plusjeff** [comment]
From Stephanie:

14. If the claimant's Location is Military Overseas:
a. APO/FPO - Select whether the claimant's address has an Army Post Office (APO) or Fleet
Post Office (FPO).
b. AE/AA/AP - Select whether the claimant's address is Armed Forces Americas (AA),
Armed Forces Europe (AE), or Armed Forces Pacific (AP).
c. Zip Code - Input the claimant's 5- or 9-digit Zip Code.

**Comment by cweber** [comment]
I didn't catch this on the call. Is this something that will need design eyes on it?

**Comment by akainic** [comment]
I think our Address field is correct, but we may need better description of how to enter military addresses, either through the labels or explanatory text above the component. I think that's where the confusion is coming from; Stephanie looked at the form and didn't see how to enter military addresses, even though our component is capable of it.

**Comment by cweber** [comment]
@J-Quag Do you know the answer to any of this?

@plusjeff, could you follow up with Stephanie since she emailed you that first part?

I think we should handle this be being inclusive with language on the field labels.
- [ ] _. **ADDRESS** This can handle whatever kind of unit information a military address may have. That seems like a broad enough label to stay as is.
- [ ] a. **CITY**APO/FPO also includes DPO, right? Is there a name for what these are? (See below)
- [ ] b. **STATE**: Is there a name for what AE/AA/AP are? e.g. MD/OR/WA are collectively called states.
- [x] c. Zip code/postal code should handle that

**Comment by plusjeff** [comment]
@J-Quag : Could you follow-up with Stephanie and bounce back to @cweber ?

**Comment by J-Quag** [comment]
So many emails to Stephanie and Shay this morning, would have been good to wrap those all into 1. 
 
 http://about.usps.com/publications/pub640/pub640_tech.htm

**Format:**
PFC John Doe 
123rd ENG 2nd PLT - B CO 
APO AE 09398-9998 

APO: Army Post Office;
FPO: Fleet Post Office;
DPO: Diplomatic Post Office

AE is used for armed forces in Europe, the Middle East, Africa, and Canada; 
AP is for the Pacific; and 
AA is the Americas excluding Canada.

When I get back from 810, I'll send an email over to Stephanie.

**Comment by goldenmeanie** [comment]
@J-Quag Caitlin was asking if there is a description in common usage that would let you ask for APO/FPO/DPO in the same way that if I ask "what state do you live in", you understand the menu of options.

**Comment by J-Quag** [comment]
In most apps at VA that I have seen, when asking to select address type it is split into 3 sections:  Domestic, Overseas, and Military. 
When one is selected the options for entering changes to only ask what is pertinent, rather than throwing it all into one address bucket and mixing overseas and military.

**Comment by cweber** [comment]
So I think this is worth watching for, but we have one adjustment to help with this that wasn't in the version being reviewed. (Or only remaining placeholder text helps to address this.)

This would also be something I'd like to test with actual veterans with military addresses to answer. We can work on getting this into one of the 'quick questions' research sessions that the research team is doing.

But for now, I think we've thought this through pretty well and should move on.

**Comment by goldenmeanie** [comment]
The premise of the current design is that people with military addresses are experts at dealing with how to get things mailed to them.
