### ISSUE TITLE
Detail page tweaks

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3456]
Could we make sure 
- [ ] the ordering of the different data fields match the mock below
- [ ] refill prescription link is a button

<img width="372" alt="screen shot 2016-10-19 at 5 06 52 pm" src="https://cloud.githubusercontent.com/assets/13420618/19537563/75bb8eda-961e-11e6-936c-fdba120d689e.png">

cc: @U-DON

**Comment by U-DON** [comment]
@gnakm So the quantity we get right now just the count. To clarify, we should always append 'CAP' to whatever count it is?

**Comment by gnakm** [comment]
@U-DON CAP and TAB stands for medication form (Capsules and tablets). I'm a little confused by your question.

**Comment by U-DON** [comment]
@gnakm The API doesn't explicitly tell us which form it is, aside from having it in the prescription name (from what I've seen so far anyway). When we get the quantity, it's just a number without 'CAP' or 'TAB' next to it. So anyway, I was just wondering if it's okay to leave off 'CAP' or 'TAB' next to the quantity.

**Comment by jcmeloni** [comment]
@gnakm @U-DON Sticking my nose in here because I have this stuff burned into my brain from working on a pharmaceutical app a couple years ago.  Quantity is typically just a number, or if it's not then it'll come from the prescription info (e.g. whatever comes out of the api) -- appending anything else to it would make pharmacists mad & be potentially confusing since it wouldn't match the actual medication label in real life.  The dosage form (e.g. cap, tab, etc) is part of a longer string that contains name, strength, dosage form, e.g. Acetaminophin 325MG TAB.  I would strongly recommend not displaying anything differently than a standard rx format because the wrath of pharmacists is strong!

**Comment by gnakm** [comment]
@U-DON 
I've seen industries have it both ways. 
I think since

- we won't always have the form and we should stick with what's consistent
- this hasn't been flagged as a patient safety issue

let's go quantity: # (no form)
