### ISSUE TITLE
Update browser notice to say v11 is the minimum version of Internet Explorer (IE)

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/vets-website#3492]
Previously, the minimum required version of IE was v9. IE11 is the new minimum, largely because < 2% of users come with IE9 or 10 and supporting those browsers would require a disproportionate amount of development effort.

More details in:
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/358

**Comment by crwallace** [comment]
@bshyong -- Can you work with @emilyville to figure out what this banner/copy should look like?

**Comment by emilyville** [comment]
@bshyong @crwallace Can you give me more context for what you have so far and what you still need?  I think this should likely be treated as an alert/warning in what @melwoodard is working on.

**Comment by emilyville** [comment]
Also tagging https://github.com/department-of-veterans-affairs/vets.gov-team/issues/365 since this is similar. Might be worth adding it in and tagging Anitra to look at copy.

**Comment by crwallace** [comment]
I know we had discussed something like this, however we thought the yellow was too harsh.

Can we get @bshyong a mockup to work from for this specific alert copy?

<img width="1548" alt="screen shot 2016-10-25 at 11 41 17 am" src="https://cloud.githubusercontent.com/assets/3453669/19927954/add2d706-a0d2-11e6-9fd0-9fe550b871ac.png">

CC: @melwoodard // @AnitraAppa

**Comment by AnitraAppa** [comment]
Hey there! Recommending:
"Your browser is out of date. To use this website, please <update your browser> or use a different device. If you're using Internet Explorer, try turning off Compatibility View."

Notes:
- I took out the "We're sorry" here because it can make people nervous about there being some kind of serious error on our part or something they can't remedy, when ideally this should be a quicker fix. Want to get to the solution as quickly as possible.
- Changed "does not support all required functionality" to "to use this website" to simplify and make it clear that they'll really want to update their browser or use another device to use this website at all

Let me know if that works! I can add it to the larger  department-of-veterans-affairs/vets.gov-team#365 issue as well.

**Comment by melwoodard** [comment]
I like your take @AnitraAppa. 

@crwallace what are the odds that a user could be in Compatibility View? Is it fairly common or rare enough that we can leave that out?

I think using our mellow yellow will help to soften this visually, and there should be an option to close/hide it too. Thoughts?

![browser-update](https://cloud.githubusercontent.com/assets/4106356/19939892/ff63d7b8-a0e7-11e6-84f1-357a6a9ca1f1.png)

**Comment by plusjeff** [comment]
@melwoodard : We'll never have someone in compatibility mode, since we include some code that switches it off. [See this.](http://stackoverflow.com/a/3449338). This means the message can be shortened by removing the Compatibility View note (yay!).

Curious: where does the `update your browser` link go?

**Comment by melwoodard** [comment]
Good question - there are a bunch of sites we can pick from to point users to, any recommendations?

Yay on less text! So this will read:

"Your browser is out of date. To use this website, please [update your browser] or use a different device."

**Comment by bshyong** [comment]
How about https://whatbrowser.org/ or http://outdatedbrowser.com/en

**Comment by melwoodard** [comment]
I'm a fan of whatbrowser. @bshyong do you need a more detailed design spec from me to get this rolling?

**Comment by bshyong** [comment]
@melwoodard I think I have enough to go on, thanks!
