### ISSUE TITLE
Refill status

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3568]
This is my fault because i should have made it clear from past iterations. `Refill requested` should not exist. `Refill status: refill in progress` implies that refill was requested. 

<img width="443" alt="screen shot 2016-10-27 at 12 52 13 pm" src="https://cloud.githubusercontent.com/assets/13420618/19777064/89827c72-9c44-11e6-8dc8-66c40193c3f5.png">

**Comment by U-DON** [comment]
@gnakm Should 'Refill requested' be hidden only for that status, or does it include others?

**Comment by webinista** [comment]
Also, to clarify: I thought I heard you say that the _Active_ status should never appear and that it did for some prescriptions. 

That can conceivably happen when `isRefillable` is `false`, but the refill status is `active`. I think that's an API issue. @ayaleloehr can you weigh in?

**Comment by gnakm** [comment]
Refill requested should never show up. The only time we should see active prescription status on View History page. 

Even if `isRefillable` is `false` but refill status is active, we shouldn't have to show active because all active medications should be on the active page.

**Comment by webinista** [comment]
OK I see the problem now. _Refill status: **Active**_ only shows up after a refill is requested, but before we reload a page with the updated status. I've mapped the `active` status to `refillinprocess` only when `isRefillable` is false. 

I'm not 100% sure whether that will fix the problem or just obscures it.

@ayaleloehr Is it possible to "reset" the data somehow so that the active prescriptions are all refillable again?

**Comment by ayaleloehr** [comment]
Request sent to MHV team to reset a bunch of prescriptions for our test user. They are usually on pretty early, so should be done in the AM.

**Comment by ayaleloehr** [comment]
6 of the prescriptions are active again now. Let me know when we need these reset again!
