### ISSUE TITLE
Find out where the shipping addresses are coming from

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3629]
Alex to ask Carnetta where the shipping addresses for Rx orders are coming from

**Comment by ayaleloehr** [comment]
Shipping address is from Veterans patient chart, also known as CPRS. That helpful @gnakm ? Not sure what we plan to do with this info, but good to know it. 

Also, new fun fact, not all prescriptions are actually shipped. There is an option for the doctor/provider to select "window pickup" as the patient's preference for prescription deliveries, in which case the Veteran will pick up the prescription at the hospital pharmacy instead of having it shipped to their house. Carnetta says this is probably less than .01% of prescriptions refilled on MHV this way, but that it does happen.

**Comment by gnakm** [comment]
Closing this because this doesn't effect us now especially since we took out mail in order title and kept disclaimer inclusive to all methods of medication delivery within our scope. Put questions for the future here: https://github.com/department-of-veterans-affairs/kudos-team/blob/master/Prescriptions/meeting-notes/2016-11-15-Carnetta-call.md
