### ISSUE TITLE
Rx error to show user when API returns 500?

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-website#3671]
Currently on Rx when our API returns a 500 error (`"{"errors":[{"title":"Internal Server Error","detail":"Internal Server Error","code":"500","status":"500"}]}"`), the active prescriptions page looks like the below.  I think we should show some sort of text there in this case. 

@gnakm and @emilyville Do you agree? What message should we should we show to the user when this occurs? 

<img width="1230" alt="screen shot 2016-11-01 at 7 55 23 pm" src="https://cloud.githubusercontent.com/assets/4719765/19911957/7426524a-a06d-11e6-9ea4-6285a5b69c13.png">

**Comment by gnakm** [comment]
@emilyville I'm looking at the [Vets.gov error doc](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Design/Error-messaging.md) and noticed that we don't have a 500 error for Rx. Instead of using the generic one for Vets.gov, could we do something similar to claims?

Rx 500 error from the vets.gov API

API Response from our API: "500 internal server error"
Message type: Application Level
UI response to user: **We couldn't retrieve your prescriptions. Please refresh this page or try again later.**

**Comment by gnakm** [comment]
@ayaleloehr Just checked in with @emilyville. 
Let's go with: We couldn't retrieve your prescriptions. Please refresh this page or try again later.

Alex - Who should I assign this to? 
Emily to add any edits to the original markdown.

**Comment by ayaleloehr** [comment]
Since I noticed this on the active page, assigning to @webinista .  

Change is that when the API returns a 500 error, we should show "We couldn't retrieve your prescriptions. Please refresh this page or try again later." instead of just leaving it blank on the screen as we currently are in the screenshot above.
