### ISSUE TITLE
Open facility detail page in new tab goes to 404 page

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/vets-website#3692]
From map pane, right click on one of the facility names and open in new tab, it shows a URL like `https://dev.vets.gov/facilities/facility/vha_358` in the location bar, but displays the "Sorry - we can't find that page' 404 response.

**Comment by bshyong** [comment]
@patrickvinograd Is there a devops change that we need to resolve this issue?  The reason is that a page with that URL doesn't exist. `https://dev.vets.gov/facilities/facility/vha_358`

If the request is redirected to ``https://dev.vets.gov/facilities/` which _does_ exist, the React app will pick up the parameters in the path and render correctly

**Comment by patrickvinograd** [comment]
Probably yes, there's some special-handling of react paths in our reverse proxy configuration.

**Comment by patrickvinograd** [comment]
I'll open a devops ticket.

**Comment by bshyong** [comment]
@patrickvinograd I just pushed a fix which might resolve the 404 issue. If everything is configured correctly on the devops side, this fix might resolve the issue

https://github.com/department-of-veterans-affairs/vets-website/pull/3698
