### ISSUE TITLE
[HOMEPAGE] Add hover state to popular buttons

### ISSUE THREAD

**Issue by angel** [department-of-veterans-affairs/vets-website#3808]
Let's make the border color the same blue as the cards when a Veteran hovers over that button. Can we also increase it to 2px so that it's more visible?

**Comment by bshyong** [comment]
@angel for these cards, what color did you mean the border color to be: the same color as the hover state, or non-hover state?
if it’s the same color (lighter), then hovering will make the card look bigger since the border color will be the same color as the background

If it's a different color, the card looks like this
<img width="513" alt="screen shot 2016-11-28 at 2 35 43 pm" src="https://cloud.githubusercontent.com/assets/303289/20688999/2352e53e-b578-11e6-8907-587249933c9d.png">

**Comment by angel** [comment]
@bshyong sorry for the confusion. My changes were meant for the "Popular on Vets.gov" boxes.

**Comment by jcmeloni** [comment]
@angel is this still an issue or did the referenced merged PR take care of what you wanted?
