### ISSUE TITLE
User messages for login and logout

### ISSUE THREAD

**Issue by crwallace** [department-of-veterans-affairs/vets-website#3840]
@melwoodard // @AnitraAppa -- Can we get your once over on these popup screens?

Would love to know what content we should show the user.

I user will see this quickly when they are logging in before we check to see if they are verified and right before we fully log them in and close out the login screen:
<img width="782" alt="screen shot 2016-11-08 at 5 49 06 pm" src="https://cloud.githubusercontent.com/assets/3453669/20120701/d5860904-a5db-11e6-8d35-4746f6b920ea.png">

This is what the user sees quickly before they are fully logged out. This one is placeholder text as an FYI: 
<img width="794" alt="screen shot 2016-11-08 at 5 48 53 pm" src="https://cloud.githubusercontent.com/assets/3453669/20120706/db99945a-a5db-11e6-8c21-5477034223af.png">

**Comment by melwoodard** [comment]
@gnakm where did we land on the loading indicator front? I think we can utilize that with some messaging for these screens.

**Comment by crwallace** [comment]
@melwoodard -- This screen is part of the ID.me login flow and they have loading indicator's as well so it might be confusing to have two different loading indicators.

**Comment by melwoodard** [comment]
Ah, got it. In that case, here's what I'd suggest:

**Sign in (left) -** since this appears inside the id.me popup window, it's confusing to see all the vets.gov website nav here. If it's possible, we should remove all of it and show a simple message.

**Sign out (right) -** we can mirror the phrasing for sign in for this state, but maintain all the site nav elements since it's shown in the context of vets.gov instead of in the id.me window.

<img width="854" alt="screen shot 2016-11-08 at 3 58 17 pm" src="https://cloud.githubusercontent.com/assets/4106356/20122438/7af5e176-a5cc-11e6-8f0d-30aac80aad9d.png">

**Comment by AnitraAppa** [comment]
+1 to @melwoodard's mocks, "Signing in to Vets.gov..." and "Signing out of Vets.gov..." LGTM

**Comment by gnakm** [comment]
@melwoodard We have a similar discussion happening here for [SM and Rx with the loader](https://github.com/department-of-veterans-affairs/vets-website/issues/4015)

**Comment by ayaleloehr** [comment]
I think changing this from "I am the logout" to something else prior to launch is a very good idea, so I'm sticking a high-priority tag here. If someone with more authority in this arena disagrees, feel free to remove.
