### ISSUE TITLE
Expired userToken in the middle of a session doesn't automatically redirect to login

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/vets-website#3843]
When your session expires, and you continue to make API requests with a stale userToken, the app will stop working, and there's no redirect the user to login. Only upon refresh does the login component render again.

I discovered this while working on Rx, but this would be true for any app that uses the userToken to make API requests. Depending on how the apps handle failed requests, it can be a confusing scenario for a user. In Rx's case, there will be a general error message telling the user to refresh or try again when data retrieval fails for any reason, so the user would probably refresh in that case. But it would be a less confusing experience to automatically redirect the user back to the login page.

**Comment by crwallace** [comment]
@U-DON -- I just spoke with @ayaleloehr about this and this is something that the rx app will have to listen for because there is no way for the profile app or the login app to listen inside of the rx app since they are disconnected react components. Maybe we can pass `handleLogin()` down to the rx app through the `<RequiredLoginView/>`, which will allow you to use it when you receive a 401 from the api.

**Comment by jcmeloni** [comment]
@U-DON Has this been satisfactorily handled or is there more action to take?

**Comment by U-DON** [comment]
There is more action to take, and both Rx and SM need to handle this case.
