### ISSUE TITLE
Distance not showing

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#3916]
Distance not showing on both results list and detail page. 

Current:
<img width="310" alt="screen shot 2016-11-10 at 2 32 45 pm" src="https://cloud.githubusercontent.com/assets/13420618/20191220/98b3bac6-a752-11e6-9789-2c60584747ba.png">

Reference:
<img width="310" alt="screen shot 2016-11-10 at 2 35 36 pm" src="https://cloud.githubusercontent.com/assets/13420618/20191328/f9349820-a752-11e6-864a-af21fa56057c.png">

**Comment by NatalieEMoore** [comment]
@ayaleloehr @patrickvinograd what is the feasibility of calculating this on the API side and passing to front end?

**Comment by patrickvinograd** [comment]
It's feasible but it makes for a poor API design - an API result is supposed to represent a facility or a list of facilities, but "distance from center" is not really an attribute of a facility, it's an attribute of the current map view. So putting it as a field in the facility object seems backwards to me. 

We could _possibly_ represent it in the `meta` section of the result, as a separate dict keyed by the facility id, since it's meta-information related to the current query bounding box.
