### ISSUE TITLE
do not require RAD

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4073]
see photo

**Comment by leannammiller** [comment]
![screen shot 2016-11-22 at 9 10 07 am](https://cloud.githubusercontent.com/assets/22749867/20526792/a734c226-b093-11e6-9e9c-f7351566a767.png)

**Comment by leannammiller** [comment]
(end of service period)

**Comment by cweber** [comment]
Applicants should be able to submit a current period of service without an end date.

Shortest distance to a solution is to just not make that field required.

*Will create another issue to check with Shay about the necessity of the end day field as a whole.

cc @akainic

**Comment by akainic** [comment]
@cweber so we're making this field not required for everyone, or just for those who indicate that it is a current active duty period (we can add a field or something for that)?

**Comment by cweber** [comment]
I think not required for anyone is fine and we double checked that with Shay. She didn't seem concerned about it getting skipped frequently. Since that's the simpler solution, let's get that up and then if we get a report that it's causing problems we can modify.

(In most cases VCEs use this data to verify existing data they already have in one of the databases. It's only hand entered if the data doesn't match.)

**Comment by jbalboni** [comment]
I think this is on hold until #4085 is done.

**Comment by cweber** [comment]
This seems separate to me. We just need to turn off the required nature of it. Any partial field rules would apply separately.

But note. I'll get on #4085

**Comment by jbalboni** [comment]
I'd like to know what all the partial date (and date range) rules are before we make this change, so that we have a solid overall picture of how our date validation should work.
