### ISSUE TITLE
add some wording surrounding Kickers

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4076]
We also need to add some wording surrounding Kickers. The 4 bullets below are directly from VONAPP and on the form. They have been “simplified” a bit too much in the Infor box on vets.gov. (We have been trying to get the chapter 30 relinquishment wording online –item 3) We need to make sure that the kicker bullet is on vets.gov as well.
 
VONAPP and the paper form:
 
Chapter 33 Election By electing Chapter 33, I acknowledge that I understand the following:

·  I may not receive more than a total of 48 months of benefits under two or more of the education programs listed on this application. 

·  If electing chapter 33 in lieu of chapter 30, my months of entitlement under chapter 33 will be limited to the number of months of entitlement remaining under chapter 30 on the effective date of my election.

·  I will not receive a Montgomery GI Bill (Active Duty-Chapter 30 or Selected Reserve-Chapter 1606) "Kicker" under the Post-9/11 GI Bill, unless I was eligible for the kicker at the time I applied and I relinquished that benefit for the Post 9/11 GI Bill-Chapter 33.

·  When choosing the effective date below, I understand that benefits for training under Chapter 33 are not payable prior to that date.

Vets.gov:
You may be eligible for more than 1 education benefit program.
You can only get payments from 1 program at a time.
You can’t get more than 48 months of benefits under any combination of VA education programs.

**Comment by cweber** [comment]
Molly, I can't find how we're dealing with bullet 3 below. Can you? These also look pretty good to me in terms of describing more clearly what they mean. If we can get 3. figured out, we should probably ask Shay more specifically what seems too simplified.

I'm wondering if part of the concern is that we've nested these bullets with relevant content (which I stand behind) rather than presenting a list upfront.

Chapter 33 Election By electing Chapter 33, I acknowledge that I understand the following:

1.  I may not receive more than a total of 48 months of benefits under two or more of the education programs listed on this application.
**You can’t get more than 48 months of benefits under any combination of VA education programs.**


2. If electing chapter 33 in lieu of chapter 30, my months of entitlement under chapter 33 will be limited to the number of months of entitlement remaining under chapter 30 on the effective date of my election.
_THIS IS IN THE LEGALESE UPDATE_
**If you choose to give up MGIB-AD, you'll get benefits only for the number of months you had left left under MGIB-AD.**

3. I will not receive a Montgomery GI Bill (Active Duty-Chapter 30 or Selected Reserve-Chapter 1606) "Kicker" under the Post-9/11 GI Bill, unless I was eligible for the kicker at the time I applied and I relinquished that benefit for the Post 9/11 GI Bill-Chapter 33.



4. When choosing the effective date below, I understand that benefits for training under Chapter 33 are not payable prior to that date.
**If you pick a future date, you can’t get benefits until then.**

**Comment by mollyblake** [comment]
@cweber Option? You chose to give up MGIB-SR, so you won't get your Active Duty kicker.

**Comment by cweber** [comment]
What was the argument against telling the applicant which benefit they would have to give up?

I think I suggested something to that effect and got 3 groans or mm-nos in response.

You chose to give up MGIB-SR, so you won't get your Active Duty kicker. To receive your Active Duty kicker, you would need to relinquish MGIB-AD.

Was it too leading and advice-ey?

**Comment by goldenmeanie** [comment]
Yes, I think the groan was about offering advice

**Comment by goldenmeanie** [comment]
> You can only transfer a kicker from a benefit that you are giving up. You chose to relinquish [benefit].

> You can only transfer a kicker from a benefit that you are giving up. You chose to relinquish [benefit], so this kicker will not apply.

**Comment by cweber** [comment]
@mollyblake Talking it through with Alex. My concern is that I want to explain the logic a little bit. The above almost feels like a reminder of something they already know.

@goldenmeanie's concern is that we shouldn't be too advicey. So this solution stays a little more vague, but explains the logic and then inserts the choice they've already made.

You can only transfer a kicker from a benefit that you relinquish. You chose to relinquish [MGIB-AD].

**Comment by mollyblake** [comment]
@cweber @goldenmeanie So if we explain it a bit -- that works. Can we still tell them what they did to make sure they get it?  

"You can only transfer a kicker from a benefit that you relinquish (give up). You chose to relinquish [MGIB-AD] so you won't get your Active Duty kicker."

**Comment by cweber** [comment]
Yay!

Language changed on the relinquishment page and added the kicker language for active and reserve kickers on http://localhost:3001/education/apply-for-education-benefits/application/military-history/contributions

Changes made in branch: edu-benefits-add-kicker-language

It needs some front end help, @akainic @alexose or @jbalboni.

The new messages under the Active Duty Kicker question and the Reserve Kicker question need to be displayed conditionally.

If, on benefit relinquishment, an applicant selects [MGIB-AD] and they indicate that they have a [Reserve Kicker] then we show the message.

And the opposite is true for the other:

If, on benefit relinquishment, an applicant selects [MGIB-SR] and they indicate that they have a [Active Duty Kicker] then we show the message.

**Comment by alexose** [comment]
I'll grab this one!

**Comment by alexose** [comment]
Changes committed to your branch:

https://github.com/department-of-veterans-affairs/vets-website/compare/edu-benefits-add-kicker-language

**Comment by cweber** [comment]
Closed with #4101
