### ISSUE TITLE
Question about security

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4081]
We heard from Shay Norton this morning that the education benefits call center asked the following question:

"How secure is the site? There are many concerns about the secure of the Veteran’s PII on the vets.gov website as they do not have to establish a username and password to get to or fill out the application."

Shay would like a response to provide to the call center and I know this isn't isolated to our team. We probably need a security engineer paired with a content person, but didn't want to do this at the team level. 

Could you please provide some guidance on prepared statements for this question program-wide?

**Comment by plusjeff** [comment]
@leannammiller : I'd be happy to talk to Shay if she'd like to chat more about it. Her question is pretty broad ("How secure is the site?") and I'd be happy to address any specific concerns that she has. 

In the meantime, here's a broad answer that might alleviate concerns:

In terms of the security of the form, all submissions between the education benefits web form and the Vets.gov servers are encrypted in transit via TLS and HTTPS (the same level of encryption that Amazon or nearly any other website uses to encrypt traffic). At this point in time, once the data arrives on the Vets.gov servers, there are no public endpoints for querying for the data, logged in or otherwise (only those individuals and systems that have access internally to the infrastructure via SSH keys _and_ system credentials can get to it).

**Comment by leannammiller** [comment]
@plusjeff Thanks. This looks great. This is for vets who have questions about this for the call center. @mollyblake or @AnitraAppa - Do you mind taking a look at this?

**Comment by mollyblake** [comment]
Hey @plusjeff is it correct to say that SSH keys are more secure than passwords?  I'm thinking about how to frame this answer ... thanks!

**Comment by plusjeff** [comment]
Sample take on the existing question "How secure is the site?" (in full transparency: mostly to appease, but would like to hone with @mollyblake if there are specific questions being asked to the call centers that we can word more specifically):

All data being sent to Vets.gov is encrypted between your computer and our systems. Once the data arrives, it is stored securely behind a series of firewalls and security mechanisms.

**Comment by plusjeff** [comment]
@leannammiller : Putting back in your camp. Let me know if you wind up getting a list of questions, and can work through responses with @mollyblake if so. cc @akainic

**Comment by leannammiller** [comment]
@plusjeff Thank you - catching Shay up now.
