### ISSUE TITLE
Figure out how to handle partial dates for education

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#4085]
Because there are no specific data requirements for the spool file for non-required fields, should we allow partial dates to be submitted? Currently only complete dates (having a month, day, and year) can be submitted. Partial dates will be stripped out and nothing will be submitting.

Tagging @jbalboni for awareness and to add further context.

**Comment by goldenmeanie** [comment]
This seems like a good thing to allow, but we could check with Shay about priority.

**Comment by cweber** [comment]
Updating to state why this is on Alex and I.

We need to go through all of the date fields in the form and make sure there is a clear UX decision about which fields can accept partial dates, whether we want to ask for full dates at all, etc.

**Comment by cweber** [comment]
**Date of birth**

- Required? **yes**
- Is entry of all parts required? **yes**
- Which pieces to display? **month/day/year**


**Effective date**

- Required? **yes**
- Is entry of all parts required? **yes**
- Which pieces to display? **month/day/year**


**Start service period**

- Required? **yes**
- Is entry of all parts required? **yes**
- Which pieces to display? **month/day/year**



**End service period**

- Required? **no**
- Is entry of all parts required?  **no**
- Which pieces to display? **month/day/year**



**Military Service Academy year of commission**

- Required? **no**
- Is entry of all parts required? **n/a**
- Which pieces to display? **year**



**ROTC year of commission**

- Required? **no**
- Is entry of all parts required? **n/a**
- Which pieces to display? **year**



**ROTC scholarship year**

- Required? **no**
- Is entry of all parts required? **n/a**
- Which pieces to display? t**year**



**DOD loan payment start date**

- Required? **yes**
- Is entry of all parts required? **yes**
- Which pieces to display? **month/day/year**



**DOD loan payment end date**

- Required? **yes**
- Is entry of all parts required? **yes**
- Which pieces to display? **month/day/year**



**Date of high school graduation**

- Required? **no**
- Is entry of all parts required? **no**
- Which pieces to display? **month / year**



**After highschool From **[currently**]

- Required? **No**
- Is entry of all parts required? **No**
- Which pieces to display? **month/day/year**
- ****** Ask Shay if we can treat these dates the same way we treat 'Date of high school graduation'



**After highschool To** [currently**]

- Required? **No**
- Is entry of all parts required? **No**
- Which pieces to display? **month/day/year**
- ****** Ask Shay if we can treat these dates the same way we treat 'Date of high school graduation'



**Date your training will begin**

- Required? **No**

- Is entry of all parts required? **No**

- Which pieces to display? **month/day/year**

- New validation rule: Trigger warning message when a veteran enters a training start date that occurs **before** their effective date.

  "Because you chose an effective date of mm/dd/yyyy, you won't receive your Post-9/11 GI Bill benefits for any training before then."

**Comment by cweber** [comment]
The two questions mentioned at the end have been emailed and are waiting on response. I'll update the content above once we have an answer.

**Comment by cweber** [comment]
Confirmed! All education history dates can now be month/day only.

**Comment by cweber** [comment]
This is ready for someone to pick up/assign or at least to review and ask me for more information if needed.

cc @markolson (not on currently on this issue, but this came up on #4197)

**Comment by jbalboni** [comment]
@markolson What should partial dates look like when sent to the backend? We could have different combinations of month, day, and year. I was thinking that it would make the most sense to have three possibilities:

`YYYY`
`YYYY-MM`
`YYYY-MM-DD`

And maybe `MM-DD`. Not sure if that's ever useful. The other combination is `YYYY-DD`, which doesn't seem helpful beyond the year.

**Comment by markolson** [comment]
The backend takes in whatever is sent, verbatim. The JSON schema currently requires YYYY-MM-DD, but if that's updated to allow different combinations, there's no further requirements.
