### ISSUE TITLE
Stuck in education section on live form

### ISSUE THREAD

**Issue by cweber** [department-of-veterans-affairs/vets-website#4100]
Testing out the live form for other reasons and I'm getting stuck on the education page.

I have filled in NO fields in education, but it keeps scrolling me to the top of the page when I hit continue.

**Comment by jbalboni** [comment]
The issue we found is that if you touch the year field on the graduation date, you get stuck.

This is happening because of the way we default the day field for month/year dates. Touching the year input updates the date's value from completely blank to having a 1 as the day. That causes some of our validation to see the date is incomplete.

**Comment by cweber** [comment]
This seems like it could be related to #4085

**Comment by jbalboni** [comment]
This should be fixed with #4102.
