### ISSUE TITLE
Audit education benefits for performance

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/vets-website#4115]
Get a sense of how fast the app is to initially load and be interactive.

Test various browsers (Chrome, Safari, IE11), devices (iPhone, Android device), and network speeds (Wifi, LTE, 3G).

**Comment by jbalboni** [comment]
Until we come up with vets.gov specific performance goals, the ones [advocated by Addy Osmani](https://gist.github.com/addyosmani/56bbf27857c1b73ab213286ae6bc6852) and other Google devs seem useful. That's a time to interactive number of <5s on 3G on "average hardware." Probably should shoot for 3-4s on WiFi at least. Average hardware is also hard to determine, but trying a range of devices should help us no matter what the average is.

**Comment by jbalboni** [comment]
I tested some of these throttled to Regular 3G and there's a big drop off; something like 3-4 more seconds.

**Comment by jbalboni** [comment]
Looking at the traces, the vast majority of the time is spent downloading and parsing the JS and CSS we ship. So we can do three things to address that.

1. Serve assets faster 
2. Ship less code
3. Defer loading some code until it's needed

This is an [analysis](https://jbalboni.github.io/vetsgovperf/report.html) of what's in the different app bundles.

### Serve assets faster

It would probably help a lot to have a CDN with edge node caching for vets.gov. But that's a bigger issue that we can't solve on our team right now.

### Ship less code

- We're shipping jQuery in our bundle, because it's used in some legacy code and some ajax calls in the login code. We should convert those to plain JS, or lazily load the legacy code separately.
- core-js is the babel-polyfill code, which we could shrink by removing the non-ES2015 polyfills that are included by default.
- We're already using as little of Lodash as possible, I think, by using the Webpack plugins.
- React is our biggest dependency and we can't shrink it. We could use something like [Preact](http://preactjs.com), though. A while back I tried this and it seemed to work with edu and disability benefits. But we'd have to rewrite a bunch of tests and talk about it with the team as a whole.
- CSS-wise, I think we're shipping way more than we need. We may want to ditch the common style file and create a common import that has the bare minimum for a React app.
- We're also serving a loading gif that is almost never visible, since the page is blank while parsing the JS/CSS. We should probably just put the new loading SVG inline in the static content template. We also might want to load the JS bundle with the `defer` attribute, so that users see something on the screen earlier (even if it's just a spinner).

### Defer loading some code until it's needed

The introduction page needs very little of what we're shipping to render; I would guess like 25kb of the 301kb of app specific code we have is needed. We could load in code by chapter, theoretically.

**Comment by alexose** [comment]
Thanks for doing this work, @jbalboni -- Load times are [super important](https://blog.kissmetrics.com/loading-time/).

It seems like each of those bullet points could be separated into its own issue, which we could triage by importance.  Removing jQuery and splitting out react seems like the two big ones.

@leannammiller, what's the best way to prioritize tech debt tickets?

**Comment by leannammiller** [comment]
it seems to me that only options 2 and 3 are in our control, and i can't weigh the bang-for-the-buck between the two. i defer to @jbalboni and @akainic.

**we can go back and do these unilaterally:** @akainic and @jbalboni maybe rank these in order of time-to-benefit?
2a. We're shipping jQuery in our bundle, because it's used in some legacy code and some ajax calls in the login code. We should convert those to plain JS, or lazily load the legacy code separately.
2b. core-js is the babel-polyfill code, which we could shrink by removing the non-ES2015 polyfills that are included by default.
2d. CSS-wise, I think we're shipping way more than we need. We may want to ditch the common style file and create a common import that has the bare minimum for a React app.
3. The introduction page needs very little of what we're shipping to render; I would guess like 25kb of the 301kb of app specific code we have is needed. We could load in code by chapter, theoretically.

**This one will probably require a chat with vanguard:** We're also serving a loading gif that is almost never visible, since the page is blank while parsing the JS/CSS. We should probably just put the new loading SVG inline in the static content template. We also might want to load the JS bundle with the defer attribute, so that users see something on the screen earlier (even if it's just a spinner).

**This one I'd like to talk about as a team and loop in Aubrey:** React is our biggest dependency and we can't shrink it. We could use something like Preact, though. A while back I tried this and it seemed to work with edu and disability benefits. But we'd have to rewrite a bunch of tests and talk about it with the team as a whole.

**Comment by jbalboni** [comment]
I would rank them as 

2a
2d
2b
3

3 is the most work, easily.

I don't think the loading gif one requires a talk with Vanguard; it would only affect our page. I think we should let them know when we make a change, though.

For the Preact one, I'd like to try to do everything else on our list before we talk about it.

**Comment by alexose** [comment]
> I do want to talk to the team as a whole about what the right metrics are, though.

The right answer likely involves a better understanding of our demographics than I have handy... i.e., what percentage of our audience is on 3G?  2G?  Dial-up?

Just as a strawman, I'd throw out the following targets for `domInteractive`:

| Page  | 2G | 3G | DSL | Cable
| -- | -- | -- | -- | -- |
| Home / Non-react | 8 | 5 | 4 | 2.5 |
| React application | 12 | 8 | 5 | 4 |

I made these up off the top of my head, so feel free to edit.

**Comment by jbalboni** [comment]
Yeah, it's hard to tell what mobile network speeds our audience would have. I don't know how we would even gather that info. I feel like we're going to have to settle for picking something like 3G as a baseline. The numbers are also dependent on how fast your device is, but that's easier (but not easy) to figure out. Other apps are also dependent on how fast api requests are, which we don't have complete control over.

I think we might want to pick more granular metrics that we cover what we can control and that add up to a reasonable experience.

So like:

1. Download critical assets: 1s on Cable, 3.5s on 3G
2. Parse JS: 150ms on Desktop, 750ms on mid-range Android
3. Render page (DOMContentLoaded event, basically): 150ms on Desktop, 750ms on mid-range Android

Which totals up to 5s on mid-range Android on 3G and 1.3s on desktop with cable, without an api call.

**Comment by ayaleloehr** [comment]
I posted this URL in an issue at some point a while back, but I find it really helpful so am posting here again as it might be relevant / helpful in prioritizing: https://developers.google.com/speed/pagespeed/insights/?url=www.vets.gov

**Comment by jbalboni** [comment]
@ayaleloehr That's helpful, thanks! The render blocking JS issue that comes up is related to something I mentioned above, loading our scripts with the `defer` attribute. It would be an improvement on the static content pages for sure and it might help on the React apps (unless it delays when the JS starts parsing).

**Comment by akainic** [comment]
Individual tickets have been created for the issues identified.

**Comment by jbalboni** [comment]
The next steps are in the Eng meeting notes above, and the tickets referenced. Closing this.
