### ISSUE TITLE
links to GI Bill Comparison Tool go to "Sorry--we can't find that page"

### ISSUE THREAD

**Issue by bethpotts** [department-of-veterans-affairs/vets-website#4124]
Couple examples of pages with a broken relative link to the GI Bill Comparison Tool:
https://vetsgov-pr-4098.herokuapp.com/education/gi-bill/
https://vetsgov-pr-4098.herokuapp.com/education/tools-programs/locate-a-school/

When it isn't a relative link, it seems to work, as on this page:
https://www.vets.gov/gi-bill-comparison-tool/

Even though this page is internal to vets.gov, should we make all links to this page full links?

**Comment by ayaleloehr** [comment]
Those relative links will only be broken on the heroku applications (they will work in staging/production), and they are broken on the heroku applications because GIBCT is not contained in the same code repository as vets-website. 

I think it's best practice to use relative links where we can, so my $.02 is we should continue using relative links and just know that ones to /gi-bill-comparison-tool won't work in heroku.

**Comment by dannychapman** [comment]
Agreed with @ayaleloehr - broken links on heroku are fine- these will work in production, so I would go with /gi-bill-comparison-tool/ for all GI bill tool links for now.

**Comment by jcmeloni** [comment]
@ayaleloehr @dannychapman @bethpotts Anything actionable remaining here?

**Comment by dannychapman** [comment]
@jcmeloni Nope, I think we can close this out.
