### ISSUE TITLE
Add ID.me FAQ link to profile and gate screens

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets-website#4190]
Adds a right-aligned sidebar on the profile page with a link the ID.me Vets.gov FAQ - https://vetsgov.id.me

Follows standard responsive behavior at 1-column breakpoint, with the sidebar content moving below the main column.

![profile-faq](https://cloud.githubusercontent.com/assets/4106356/20803561/7fd372a0-b7a4-11e6-8a81-cd3d1a92cf96.png)

The ID.me FAQ contains how-to's, troubleshooting and general questions about managing your ID.me account and the identity verification process, as well as information about ID.me and how to get in contact with them.

@AnitraAppa can I get your input on language for the call to action?

**Comment by melwoodard** [comment]
We should also add the FAQ link to the sign in gate screens. @AnitraAppa I'd love your input on content here as well.

Sign in gate:

<img width="1075" alt="screen shot 2016-12-01 at 9 14 48 am" src="https://cloud.githubusercontent.com/assets/4106356/20804161/aa4b6aa4-b7a6-11e6-82af-e0cd030a486f.png">


Verify gate:

<img width="1075" alt="screen shot 2016-12-01 at 9 11 53 am" src="https://cloud.githubusercontent.com/assets/4106356/20804082/5696f6a8-b7a6-11e6-9514-02ba53c72b9d.png">

**Comment by AnitraAppa** [comment]
For sure! Will add content feedback for the pages themselves to https://github.com/department-of-veterans-affairs/vets.gov-team/issues/485 as well. Recommending:

[Profile sidebar]
**Need help?**
To change your account information or fix other issues, check our [Frequently Asked Questions](https://vetsgov.id.me/hc/en-us). 

Notes:
- Use sentence case "Need help?" instead of title case "Need Help?" (VA style convention)
- Make link text as descriptive and actionable as possible, ideally within 5-8 words. Avoid using "learn more" or other vague link phrases that users tend to ignore.

**Comment by AnitraAppa** [comment]
Recommending for verify account page:
"For more information about identity verification, check our [Frequently Asked Questions (FAQ)](https://vetsgov.id.me/hc/en-us)." 

Notes:
- Since they haven't started the real flow yet, changed "Having trouble? Need help?" kind of messaging to "For more information"

**Comment by jcmeloni** [comment]
Removing identity label because this isn't about a user's identity, and removing id.me label because this isn't an id.me issue. Just a content update.

**Comment by melwoodard** [comment]
Thanks @AnitraAppa. I think your content for the verify screen makes sense, although the other use case is that the user arrives on this page, starts the ID proofing flow, fails out and closes that window and is back at this screen trying to figure out what to do next. Can the text also indicate something about troubleshooting?

**Comment by melwoodard** [comment]
Also, any edits to the Sign in screen?

**Comment by AnitraAppa** [comment]
@melwoodard - Sorry, missed this in my inbox on Friday! Will add today.

**Comment by AnitraAppa** [comment]
[Verify page]
"Need help verifying your identity? Check our Frequently Asked Questions (FAQ)."

Note: Changed this back, to Mel's point about users having trouble with flow returning to this page after fiddling with it. Small tweaks to original text.

[Sign in page]
# Sign in to Your Vets.gov Account
Vets.gov is a new VA website offering online services for Veterans.

To refill a prescription, send a secure message to your health care provider, or check the status of a disability claim, sign in to vets.gov. 

Notes:
@bethpotts flagged some edits for the "Sign in" screen generally on https://github.com/department-of-veterans-affairs/sunsets-team/issues/250), adding them here. @melwoodard let me know if I should add these to a different issue instead.
- To avoid saying "the VA" as a noun, changed line to "VA website" with "VA" as adj.
- Made "health care" two words. (I'm used to seeing it as one when used as an adj.)
- Lower-cased "vets.gov" when it doesn't start a sentence (I've been capitalizing it everywhere, will go back and check other issues.)

**Comment by melwoodard** [comment]
Oh, thanks! I like the updates for the sign in language. I was actually just talking about the content for the FAQ link on the sign in page though. I put in the mockup:

"Having trouble signing in or creating an account? See [Frequently Asked Questions (FAQ)](url)". 

Based on your updated content for the FAQ link on the verify page, would this work better?

"Need help signing in our creating an account? Check our [Frequently Asked Questions (FAQ)](url)"

**Comment by AnitraAppa** [comment]
@melwoodard - Sorry, tried to refresh this when I was kicked offline yesterday and lost my other edits! But yes, that's exactly what I was thinking for the FAQ line. Here's the rest of the changes added in:

# Sign In to Your Vets.gov Account

Vets.gov is a new VA website offering online services for Veterans.

To refill a prescription, send a secure message to your health care provider, or check the status of a disability claim, sign in to vets.gov.

Sign In | Create Account

Need help signing in or creating an account? Check our Frequently Asked Questions (FAQ).

Notes:
- Title case for top header and button text, sentence case for everything else
- "Create Account" instead of "Create an account"

**Comment by gnakm** [comment]
Just to review and make sure I am up to speed, these are the following issue effected by this:

- [ ] [Profile page](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/514#issuecomment-266569279)
- [ ] Sign in/Verification gates
- [ ] I[D.me Login](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/509#issuecomment-266580391) -- as we plan to add an FAQ/ help link in popup. 

Once all of these issues are sorta out, will close this issue.

**Comment by gnakm** [comment]
Closing this because these are being prioritized by core team!
