### ISSUE TITLE
Dropdown field needs better solution for long values (4)

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#4220]
Currently:
![](https://cloud.githubusercontent.com/assets/4106356/20846538/f9ef289c-b87e-11e6-8e19-ee716c579fb3.png)

Not sure what our options are here. Truncation is not my favorite, but we should avoid the overlapping of the text with the dropdown chevron.

**Comment by cvalarida** [comment]
@crwallace, I tracked down where the `<select>`s are getting their styling from, and it looks to be from the [web design standards repo](https://github.com/18F/web-design-standards/blob/staging/src/stylesheets/elements/_inputs.scss#L110). I asked @jbalboni if that would be the best place to fix it and he said to ask you, since we're using an older version and it'll take longer to get into the vets.gov codebase.

So I can find a home for the `padding-right: 3rem` in vets-website or I can make a PR for it on uswds and we can wait for the change here until we update the version vets-website is using now.

What're your thoughts?

**Comment by J-Quag** [comment]
@melwoodard  / @suzchap  Going to point this in your direction since Courtney is gone.

**Comment by suzchap** [comment]
@J-Quag Is this a site-wide issue or just in education?

**Comment by J-Quag** [comment]
@suzchap  I would need to look at HCA for drop downs, but its in all of our EDU forms I believe.

**Comment by suzchap** [comment]
@J-Quag ah, ok. @melwoodard can you have a look and make a recommendation? (adding Mel as an assignee)

**Comment by melwoodard** [comment]
I believe we use this dropdown site wide (with a couple exceptions like facility locator). I'd suggest submitting a PR to USWDS, since this affects a lot more sites than just vets.gov.

If it's not a big lift to roll out a temporary custom class (and later reverse it) I'd be inclined to do that until we transition to USWDS 1.0 - but I'd like input from @cvalarida on the lift, as well as from @tiffanybbrown-va on our approximate timeframe for the 1.0 update.
