### ISSUE TITLE
Headings are sometimes one tag and sometimes another

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/vets-website#4222]
Headings are not consistently marked up. In an ideal world, the form headline would be h1. But that is currently reserved for the logo. This is a placeholder for a larger discussion about site-wide patterns with regards to headlines.

All the tags!

**Comment by leannammiller** [comment]
I think this is something that @crwallace and team can be involved in.

**Comment by crwallace** [comment]
I think this will be addressed in the new template/redesign efforts.

**Comment by leannammiller** [comment]
@crwallace i'll keep this open until this is confirmed. do you mind updating when this is a solid yes?

thanks!

**Comment by webinista** [comment]
Related to department-of-veterans-affairs/vets.gov-team#576

**Comment by ayaleloehr** [comment]
@webinista was there an update to this based on work happening in other tickets?

**Comment by jcmeloni-usds** [comment]
IMHO I think this is subsumed by work and discussions following https://github.com/department-of-veterans-affairs/vets.gov-team/issues/576 and https://github.com/department-of-veterans-affairs/vets.gov-team/issues/760 and its related things.  I'd lean toward closing it because the purpose of the ticket was for discussions and that's happened a lot (driven by @melwoodard and @tiffanybbrown-va).  What do you all think?

**Comment by leannammiller** [comment]
love closing issues @jcmeloni-usds 

fine with me.

**Comment by leannammiller** [comment]
@goldenmeanie ?

**Comment by ayaleloehr** [comment]
I see two votes to close and issues can always be reopened, so I'm going to close. Reopen if you object.
