### ISSUE TITLE
Remove old loading spinner from hca and edu static pages

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/vets-website#4235]
We're using the old loading spinner for the spinner that shows up while the React app is booting up. We should use the new spinner and possibly inline it to make the page load quicker.

Related to #4115

**Comment by jbalboni** [comment]
@crwallace @alexose I'm curious if you two have any thoughts on this. The new spinner is a gif that's twice as large as the old spinner (60 kb vs 32 kb). It seems like unnecessary page weight for something that's not shown for very long and might not even be downloaded in time for it to be viewed. I also thought the new spinner was svg, which might be smaller, but apparently it isn't.

We could inline the gif in the static content page and eliminate an http request. Or we could drop the spinner entirely. Opinions?

I'm just talking about the spinner before React apps load, the spinner works fine for loading states inside the React apps.

**Comment by alexose** [comment]
I think turning it into an inline SVG is a clear and uncontroversial improvement-- That's probably the way to go.

(Personally, I don't mind dropping it, especially if we can reduce the average load time to the point where a spinner isn't even necessary)

**Comment by jbalboni** [comment]
A related issue is that since we don't use `defer` on our scripts, the scripts have to download before the page will show any content. So the spinner is visible in a pretty narrow window right now.

**Comment by leannammiller** [comment]
@cagedcrown - can you please provide an update?

**Comment by cagedcrown** [comment]
@leannammiller From my understanding about what @jbalboni said, the new spinner that we planned on using has a bigger size than the old one. 

![loading-state](https://cloud.githubusercontent.com/assets/6254227/22218096/795075a6-e173-11e6-99ab-536747637ce4.gif)
64kb

vs

![preloader-primary-darkest](https://cloud.githubusercontent.com/assets/6254227/22218122/8e114d1c-e173-11e6-97a7-2756bea4717d.gif)
33kb

We also don't currently have the spinner in .svg format, so we won't be able to inline it until it is created. An alternative method would be to just remove the spinner altogether, since it is only used in a few places.

**Comment by jbalboni** [comment]
I'm going to close this, we can come back to it at some point later if necessary.
