### ISSUE TITLE
Gray bars causing UI uglies under login

### ISSUE THREAD

**Issue by emilyville** [department-of-veterans-affairs/vets-website#4259]
Wondering if we're still relying on these buttons. If so, maybe we should take another look at how to treat them with the login

If not, maybe we can remove them?

![screen shot 2016-12-05 at 4 07 10 pm](https://cloud.githubusercontent.com/assets/1307774/20907875/c88ec666-bb05-11e6-929c-914be66b626e.png)

Tagging @melwoodard @maryannbrody, @dannychapman ... @suzchap ?

**Comment by melwoodard** [comment]
If we need to keep the gray bar, we have some consistency issues to deal with. The L2 for [/disability-benefits](https://www.vets.gov/disability-benefits/) shows the bar, while the L2 for [/education](https://www.vets.gov/education/) does not. If we remove the bar on disability benefits we'll need to surface a CTA to apply somewhere else, perhaps as its own card like education.

On a related note, there's an open PR (https://github.com/department-of-veterans-affairs/vets-website/pull/4194) to reduce some of the striped effect caused by the beta banner and login links, looks like this:

![image](https://cloud.githubusercontent.com/assets/4106356/20908016/b11e19b8-bb06-11e6-9056-33111659a3f9.png)

**Comment by dannychapman** [comment]
@melwoodard Perhaps we could surface a redesign of the search / sign in area too? I'd floated an idea for consolidating those three items onto one row. Something that would help withe the band issue a bit. That said, I'm all for losing the grey band, or at least pushing to the bottom / sidebar only.

**Comment by dannychapman** [comment]
Will add screenshots if helpful.

**Comment by suzchap** [comment]
I already recommended we get rid of the green button for disability-benefits so I'm totally good with this decision!

**Comment by melwoodard** [comment]
@dannychapman I'd like to see screenshots! I'd floated a similar consolidation idea [here](https://github.com/department-of-veterans-affairs/vets-website/issues/4028), but we punted on it because of some complexity with responsive behavior. We'll also have top-level navigation links in the near future to add to the mix.

To Danny's point, would a persisting button in the sidebar or above the footer be useful, or should we rely on people going back up the chain to find the apply page?

**Comment by melwoodard** [comment]
@goldenmeanie @cweber see conversation above - thoughts on whether to keep, remove or modify the "apply for [x]" grey bars?

**Comment by dannychapman** [comment]
Do we have any analytics on those buttons?

**Comment by emilyville** [comment]
I am not as interested in analytics, as in usability findings and people seem to look over these buttons in that spot as it looks like a global element rather than an in-page useful thing. I like the treatment that @cweber and @goldenmeanie used for education and I think that would be a better direction!

In addition - we tend to treat this button as bigger than the page (meaning per section) and then it has ended up linking to itself or something nonsensical.

**Comment by akainic** [comment]
For what it's worth, education got rid of the gray bar and replaced it with the sticky action box in the right margin: https://www.vets.gov/education/apply-for-education-benefits/. This might be a nice alternative to the gray bar where we want to keep the Apply button?

**Comment by cweber** [comment]
I'm 100% behind getting rid of it.

1. People look past it to the content of the page
2. It's another horizontal bar that we could get rid of to get to content faster
3. It over simplifies the idea of the action and where it should actually take people is complicated and should be different depending on where they are. (e.g. If you are in the Education section on a page for Transferring Benefits and you click that button which takes you to the education benefits application landing page, you will be confused.)

It's currently acting like an <aside> (hey look, a relevant thing!) rather than a primary action, but it's being treated visually and hierarchically like it's the primary action.

**Comment by cweber** [comment]
To Anne's point. We got rid of it on the main apply page, but it still lingers throughout the Education section as part of the section-wide template.

**Comment by emilyville** [comment]
Here's my suggestion after a quick huddle with Mel:

Short term (this week-ish):
- Remove all top instances of the button, if it's NOT elsewhere on the page move it to be at the bottom of the page. (Often it's on both currently)

Longer term (next few months): Remove all of the bottom ones and treat as the education form has done.

**Comment by dannychapman** [comment]
👍

**Comment by emilyville** [comment]
closing this issue and making the short term suggestion in a more succinct request here: https://github.com/department-of-veterans-affairs/vets-website/issues/4274
