### ISSUE TITLE
User endpoint hit twice on /profile

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/vets-website#4285]
It seems like two components on that 'page' are making the call to `/user` is this expected? Could we cache the first response on the client side?

`v0/sessions/new?level=1` is also called twice returning identical SAML `authenticate_via_get` urls so this could also be cached. Does this need to happen on every page? or ever if a user is logged in already?

**Comment by crwallace** [comment]
So this is a byproduct of the fact that each app is using a different store. 

The `<SignInProfileButton/>` gets loaded on every page and hits `v0/sessions/new?level=1` for the login url and stores it in `commonStore`.

The `/profile` endpoint also loads two main components: `<RequiredLoginView/>` and `<UserProfileApp/>`. The `<RequiredLoginView/>` hits `v0/sessions/new?level=1` for the login url and `/user` for profile information and stores it in local state because it is not connected to the `commonStore`. 

We currently can't connect `<RequiredLoginView/>` to the `commonStore` because it is a common component that wraps all apps, which all use their own store.

I think the answer to this and many duplicate api call questions can be resolved with us trying to get to a single store. It will also make common component libraries much easier over time. I know there will also be a danger of coupling but we will just have to be aware of that.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
