### ISSUE TITLE
Improving Form Building

### ISSUE THREAD

**Issue by leannammiller** [department-of-veterans-affairs/vets-website#4291]
what's the simplest implementation of a react form we can think of (for a developer) - 

given what we know a form should do, (ie validation, structure, conditional logic, chapters and pages, questions, etc.) what's the simplest form-specific implementation to create new ones. 

next steps: 
define what changes we'd need to make and do cost-benefit analysis and make a decision 

by end of day friday, have a sense of what our ideal form experience would be and what's needed to achieve that

**Comment by jbalboni** [comment]
These are some specific pain points off the top of my head that an ideal solution should cover:

- Boilerplate/brittle logic when specifying a component (e.g. passing down update actions, validation  logic/messages)
- Urls for form pages used in several places (uiState, routes file, some components, validation)
- Moving a form field involves multiple changes that are easy to forget

**Comment by aub** [comment]
Some use cases that the ideal solution would need to be able to solve:

* Dependencies between form elements, form sections, etc
* Custom validations
* Plugging default values into the form from some data source
* Custom design and copy for the page elements around the form
* Event-based sending of form data to the backend to enable partial saves, also loading that data in
* Specifying how the data is passed to the backend and what endpoint is used. I suspect the data format can be consistent across forms.
* Tricky things like allowing the form to collect multiple entries for a given element, like if you're giving your education history and can provide multiple schools.

I'm sure there are plenty of other things I'm missing here, but a good place to start with this exercise would be to collect all the top-level requirements like these for the new system, then when thinking about your ideal solution make sure that it can check them all off. For example, one might propose a purely configuration-based approach where the form is specified in a JSON file, but that probably wouldn't work given that we need custom logic for validations and dependencies. If you can add any more of these requirements you're aware of, that'd be a big help.

**Comment by aub** [comment]
I think it would also be worth taking some time to research whether there are existing solutions we could use or at least steal concepts from. I did a quick google search for React form builders, and it seems like there are some attempts at the full UI solution but they seem way too simplistic for our needs. I'd be pretty surprised to learn that nobody has attempted to make a set of reusable/customizable React components for form building though.

**Comment by leannammiller** [comment]
linked to jeff's proof of concept

**Comment by leannammiller** [comment]
Validation errors are hard to keep in sync with form and review language while they're embedded. Consider pulling them out into a localization file

**Comment by aub** [comment]
@leannammiller where's the proof of concept?

**Comment by jbalboni** [comment]
@aub There's a semi-related PR where we're looking at how to build multiple forms in one React app: #4320

**Comment by aub** [comment]
Got it, thanks @jbalboni I just gave it a review.

**Comment by jbalboni** [comment]
Interesting links:
https://github.com/mozilla-services/react-jsonschema-form
https://github.com/tannerlinsley/react-form?utm_source=reactnl&utm_medium=email
https://github.com/christianalfoni/formsy-react

**Comment by jbalboni** [comment]
List of steps for adding/removing a question: #4317

**Comment by jbalboni** [comment]
One incremental change could be to make the veteran object into more of a form config object:

Now each field looks like:

```
{
  value: 'Something',
  dirty: false
}
```

We could do something like:

```
{
  value: 'Something',
  dirty: false,
  label: 'SSN',
  someCustomTextForComponent: 'Something',
  required: true,
  fieldType: 'ssn',
  validator: (field, data) => {
    return [
      {
        valid: isValidCustomStuff(field.value),
        message: 'Blah'
      }
    ];
  }
```

You could keep important text in here, as well as the validation configuration. You could pass this to a React component and have it render based on the data. You could also have validation functions use it and then you wouldn't have to write field validations twice.

I would honestly rather have this configuration live in React components, but I don't see a good way of doing validation across routes/pages if we do that.

I am also leery of writing a big central config file because it would be nice if we could lazily load later parts of the form.

**Comment by jbalboni** [comment]
I've been thinking more about this and I think [redux-form](http://redux-form.com/6.3.1/) fits our requirements pretty well. I think we should look into using that or implementing some similar concepts. The main downside I see is that it will a little harder to unit test.

**Comment by aub** [comment]
@jbalboni so redux-form seems like it implements a lot of the plumbing for us, with hooks for handling dependencies and validations. Does that sound accurate? It looks pretty nifty.

I think we already have components for many of the field types, so how would we replace our existing components with the redux-form:

`<Field name="firstName" component="input" type="text"/>`

Would we make a component that descends from Field?

**Comment by jbalboni** [comment]
@aub Yep, that's accurate.

I'm still thinking about the best way to write input components using it. What we have now with components like `ErrorableTextInput` are components with inputs and labels, whereas the redux-form `Field` component is a wrapper for just the input field part. So we would need to build components like `ErrorableTextInput` that used `Field` in their implementation or update the existing components to use it.

I think there are downsides to both those approaches. If we update all our current input components to use redux-form, we have to update the other apps and force them to use redux-form. It's not a small library, so that's not great for apps that have one or two small forms. If we write a separate set of components, then we have two sets of form components which seems like a maintenance hassle.

I'm going to keep thinking about it and trying out some different approaches.

**Comment by leannammiller** [comment]
@leanna schedule follow up .5 hour

**Comment by jbalboni** [comment]
I'm testing out redux-form here: https://github.com/department-of-veterans-affairs/vets-website/compare/edu-forms-improve-jsb

**Comment by leannammiller** [comment]
Notes from Monday's meeting:

REDUX - having trouble with conditionals - feasible but not perfect solution

Reach out - Anne and Jeff
Clean up existing validations 
Move education benefits questions into their own components
Build out initial structure for all education forms in single app

**Comment by jbalboni** [comment]
I think we can close this for now. We should revisit it after the next edu form.

**Comment by jbalboni** [comment]
Things a config file approach should support:

- [ ] Multiple form pages 
- [ ] Conditional pages
- [ ] Conditional validation
- [ ] Conditional fields
- [ ] Custom fields
- [ ] Field arrays
- [ ] Validation on blur
- [ ] Review page
