### ISSUE TITLE
Sentence case consistency

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#4432]
Creating a ticket so we can keep track of sentence casing consistency throughout Vets.gov. 
@AnitraAppa Could you do a scrub of the site and list out areas where these tweaks need to be made?

**Comment by gnakm** [comment]
Just thought about this -- how should breadcrumbs be cased?

**Comment by ayaleloehr** [comment]
Pinging if this is something that still needs to happen or if it was completed with the plain language edit?  cc @rroueche

**Comment by rroueche** [comment]
I think we are in a pretty good place with this, but @gnakm lmk if you think we still need to do a scrub! Things probably aren't 100% perfect throughout the site, but are pretty close. I believe we decided to update discrepancies as we find them instead of spending time doing an audit.

For reference here is the guide on how to case things like page titles, buttons, breadcrumbs, etc: https://github.com/department-of-veterans-affairs/vets.gov-content-style-guide/blob/master/site-navigation.md

**Comment by gnakm** [comment]
@rroueche Sweet! We had mentioned this in passing a while ago but I think it's safe to close this. Feel free to reopen if anybody disagrees.
