### ISSUE TITLE
Prescription status sorting- Active Hold is not alphabetical

### ISSUE THREAD

**Issue by eli-lewis** [department-of-veterans-affairs/vets-website#4466]
Rx- Prescritption Refill->  View History-> Prescription Status sorting

Active hold status is not sorting alphabetically

![active hold sorting](https://cloud.githubusercontent.com/assets/23019174/21398687/357232be-c776-11e6-9a3b-cf1c34edf909.PNG)

**Comment by U-DON** [comment]
'Active - Hold' may be mapped to a different value in the API. This is the order that's returned by the API when we request to sort by the status. If we want it to look alphabetical, we'd have to change what the label should display as.

**Comment by eli-lewis** [comment]
@ayaleloehr this definitely "looks" weird.  I understand why but to the user this sorting doesn't make sense.  Thoughts?

**Comment by ayaleloehr** [comment]
Turning to @gnakm on this one.  It is just "hold" in the API, so that's why it's in that order. If we have to reorder them on the front end, it's going to screw up pagination I believe.

**Comment by gnakm** [comment]
`Active` was added in front of hold and suspended because this is request from pharmacy stakeholders. Reasons being that 1. both statuses are technically active and 2. when alphabetized, it will be on top/ most recent. This is on the most recent directive. From a UX perspective, I am in agreement with the pharma folks and believe this is ideal. In the front end, we show `Active - Hold` and `Active - Suspended` everywhere, so I think we should change the back end to have `Active -` as well. Also by doing this, I actually don't think it will mess up the pagination because the status of all active, in process, hold and suspended are technically active medication. It gets a little tricky because prescription statuses and refill statuses cross over but I think that's why the definition links are helpful.

**Comment by U-DON** [comment]
Pagination gets messed up if the change is only on the front-end, so if the API changes the statuses as well, it should be work out. But I don't know if those labels are coming from MHV or if we have any control over them. In addition to `hold` and `suspended`, there are other statuses that can be problematic for sorting because they're displayed differently than what they are:

`deleted` -> `Unknown`
`hold` -> `Active - Hold`
`nonVerified` -> `Unknown`
`providerHold` -> `Active - Hold`
`suspended` -> `Active - Suspended`
`refillinprocess` -> `In process`

**Comment by ayaleloehr** [comment]
@U-DON I agree that because of pagination this cannot be done on the front end. 

@gnakm do we want these other fields mapped everywhere as well or are some of those only mapped in certain places on the front end?  

@saneshark and @mphprogrammer what are your thoughts on having a mapping on the backend  for statuses (instead of on the front end where we currently do them).  Is that easy to implement given our current setup or would it take some refactoring? Good/bad idea?

**Comment by gnakm** [comment]
Another thought... not sure if this complicates anything, is to disable sort option for prescription status. Most important thing on this page is that it is defaulted by most recent submit date. Im more adamant to do that and leave back end and front end as is.

**Comment by U-DON** [comment]
Disabling sorting on status won't hard to implement, since we've just added the functionality to disable sorting on specific columns.

**Comment by bshyong** [comment]
So far we have the following two options from the discussion above:
- Disable sorting on Refill Status (front-end only fix)
- mapping for statuses on the backend (requires backend effort) TBD on how complicated this solution is

The first is a simple fix and I can implement it as a stop gap unless anybody is opposed to it

**Comment by gnakm** [comment]
I vote disable sorting on Refill Status (front-end only fix). I don't think this will really effect users experience and it would prevent a potential conversation about glossary with stakeholders.

**Comment by ayaleloehr** [comment]
Sounds good to me. Nice work getting to both a good and easy to implement solution quickly!
