### ISSUE TITLE
508 audit testing results

### ISSUE THREAD

**Issue by eli-lewis** [department-of-veterans-affairs/vets-website#4479]
Audit report notes from 508 testing on 12/21 with Reina and Reshma from 508 compliance office.  Note that this report does not include SM.  

Audit report on: https://www.staging.vets.gov
**Main Page**

- [ ] Navigation bar must be at the top

- [ ] Heading structure is not correct. Page needs to begin with H1 and goes all the way to H6. Content information should be tagged as headings. Section titles should be tagged as headings. 

- [ ] Screen reader reads definition lists. It has DT(definition term) and DL(definition list) tags. This is not correct link structure. 

- [ ] For footers you need to use proper tags. This would have bunch of links inside of a footer. 

- [ ] There is a link inside of a banner which could be confusing to a user. 

- [ ] Graphic needs to be tagged correctly 

- [ ] Help document is missing along with contact information. 

- [ ] U.S Department of Veterans Affairs need to read as a logo. 

**Healthcare Page:** 

- [ ] Same banner issue. VA.Vets.gov should not be a link. It should read as VA.Vets.gov logo. 

- [ ] Same problem with the list. Screen reader is reading definition list. 

- [ ] Need proper footer marker

**Refill Prescriptions:** 

- [ ] Heading starts off with H5 before H1. Incorrect heading structure. Tag should go from H1 to H6.

- [ ] In process (refill status) button is non-functional. Screen reader does not alert the user and user is also unable to exit out of the pop-up box.  Focus does not return back so it is confusing for the reader and for the user to get out of the pop-up

- [ ] There is a Sort by list. It is scripting issue. 

- [ ] View History:
- Scripting problem for the link “Next”. It just reads the link as a text.  
- Screen reader does not read the pop up box for “In process”

**Comment by ayaleloehr** [comment]
Many of these are cross-vets.gov things so going to tag @melwoodard and @crwallace for awareness. and @gnakm for the prescription specific things.  I propose we use this issue like a macro-issue for this topic, but anything that should actually be implemented should be created it's own ticket and better spec'ed out (if necessary). 

If any of these are too cryptic, just ask @eli-lewis or @gnakm as they were both with these users so can probably add more color.

**Comment by melwoodard** [comment]
Thanks! This is super helpful. The heading structure issue has been on my list, hopefully the core team can take some time to focus on 508 next month.

**Comment by gnakm** [comment]
Thanks for putting this together @eli-lewis I will make issues for team-kudos. 
@melwoodard We should go over header hierarchy together at one point. Will ping you at west coast hrs.

**Comment by gnakm** [comment]
**Refill Prescriptions:** 

- [ ] Heading starts off with H5 before H1. Incorrect heading structure. Tag should go from H1 to H6.
Will go over this with Mel.

- [x] In process (refill status) button is non-functional. Screen reader does not alert the user and user is also unable to exit out of the pop-up box.  Focus does not return back so it is confusing for the reader and for the user to get out of the pop-up
**Issue here:** #4492

- [x] There is a Sort by list. It is scripting issue. 
**This was fixed with new sort dropdown design. Screen reader picks it up** 👍 
<img width="598" alt="screen shot 2016-12-23 at 10 18 44 am" src="https://cloud.githubusercontent.com/assets/13420618/21456884/4372ea5a-c8f9-11e6-807f-0ef6fd2b7866.png">

- [x] View History:
- Scripting problem for the link “Next”. It just reads the link as a text.  
- Screen reader does not read the pop up box for “In process” 
**Issue here:** #4493

**Comment by ayaleloehr** [comment]
@gnakm is there anything more here for Ben or Eugene to implement or have these all been assigned out and this can be closed?

**Comment by gnakm** [comment]
On the health side, we're pretty set. @melwoodard I'll put the rest of the issues in a markdown so that core team can go over them.
