### ISSUE TITLE
508 issues around status definition pop up

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#4492]
At the 508 office, our tester used IE 11 and when she clicked on refill status: in process link, focus didn't return back and the screen reader did not alert the user that a pop-up came up. However, I just tried it with the mac screen reader on chrome and it worked. I wonder if this is a browser specific problem. 

How it looks and reads on mac:
<img width="1432" alt="screen shot 2016-12-23 at 10 06 15 am" src="https://cloud.githubusercontent.com/assets/13420618/21456655/c7959550-c8f7-11e6-9498-ed3f973ac864.png">

Also, user was not able to close out of the pop-up because the screen reader picked up on the content behind the overlay so she struggled to close out of the box. 

<img width="1440" alt="screen shot 2016-12-23 at 10 06 35 am" src="https://cloud.githubusercontent.com/assets/13420618/21456724/305dec5e-c8f8-11e6-9ac4-f2aac1507f20.png">

cc: @eli-lewis

**Comment by bshyong** [comment]
IE11! I really should buy a Windows PC so that it's easier to test our site on Internet Explorer.. I'm not sure if Browserstack or other tools allow us to simulate using a screen reader—I'll look to see if there is anything in the code that is obviously unsupported or would cause problems in IE11.

The problem with not being able to close out of the pop-up I can try testing on the Mac screen reader and dig into what the problem is.

**Comment by eli-lewis** [comment]
@bshyong there is a PC at VA that we can use for testing, i believe.  I won't be there this week but am sure we can get someone to test a couple things out if needed.

**Comment by ayaleloehr** [comment]
I will be there at least Tuesday and Wednesday. Please ping me directly if there is anything you want me to test out!

**Comment by jenny-h-l** [comment]
~19% of VA traffic is IE 11: https://analytics.usa.gov/veterans-affairs/
