### ISSUE TITLE
No User Feedback When Login Fails

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/vets-website#4512]
In the event that login fails, `vets-api` redirects the browser to:
```
https://www.vets.gov/auth/login/callback?auth=fail
```
**Expected Behavior** The page shows some kind of error screen or message
**Actual Behavior** The small ID.me login window closes but the main vets.gov page does nothing at all

Note: For reference, _successful_ login redirects to:
```
https://www.vets.gov/auth/login/callback?token=ABCD1234....
```

**Comment by crwallace** [comment]
@omgitsbillryan -- I am just digging into this and it looks like the expected behavior is happening based on the code that we have in place. 

Is there a possibility that something like this is happening?
```
https://www.vets.gov/auth/login/callback?auth=fail&token=ABCD
```
Because right now the error message will render if a `token=xxxx` is not passed.

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/js/auth/containers/AuthApp.jsx#L69

**Comment by omgitsbillryan** [comment]
From the logs, I can confirm that a redirect to:
```
https://www.vets.gov/auth/login/callback?auth=fail&token=ABCD
```
has never happened before.  It is always `?token=1234` or `?auth=fail` but _never_ both.

**Comment by jcmeloni** [comment]
Moved issue to vets.gov-team.
