### ISSUE TITLE
New top navi needs help on playbook page

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/vets-website#4875]
I believe the playbook page is the only page with a white header but this is what it looks like. My thought is that this page now needs the same header treatment as rest of site. Not sure if team is already aware of it but just incase noting it here! @angel @melwoodard for visual awareness. 

<img width="1042" alt="screen shot 2017-02-15 at 5 34 56 pm" src="https://cloud.githubusercontent.com/assets/13420618/22998812/8420b3f2-f3a6-11e6-853b-1ad05145f002.png">

**Comment by melwoodard** [comment]
@gnakm agreed - this should be updated to match the rest of the site.

**Comment by tiffanybbrown-va** [comment]
I think this needs some design work first. I can update the header, but that won't indicate that it's the Playbook.

**Comment by melwoodard** [comment]
@tiffanybbrown-va thanks, you bring up a good point. There's not a ton of value in carrying the top-level nav into the playbook, so rather than matching, what if we keep the distinct white background for Playbook, but remove all navigation elements except the logo? This seems truer to the spirit of where it stood originally before we started adding more nav:

<img width="1280" alt="screen shot 2017-02-16 at 3 22 10 pm" src="https://cloud.githubusercontent.com/assets/4106356/23046118/97f05480-f45c-11e6-9833-5295d63fc7f3.png">

**Comment by jcmeloni-usds** [comment]
Not moving to vets-team because an open PR should be closed imminently.
