### ISSUE TITLE
GI Bill CT: Outcomes section learn more links too large

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5222]
In the WIP version when the tool is shrunk to the smallest width the "Learn more" links are almost larger than then the outcome graphs themselves.

![image](https://cloud.githubusercontent.com/assets/4397508/24542242/e5c8ed2e-15c8-11e7-8a38-ef021eca2c70.png)

Seems like those links should adjust font accordingly as well.

@mphprogrammer @saneshark

**Comment by saneshark** [comment]
Validate that this one is not cross-browser issue.

**Comment by saneshark** [comment]
See also: https://github.com/department-of-veterans-affairs/vets-website/issues/5212

**Comment by U-DON** [comment]
Unable to reproduce this issue on Firefox, Chrome, or Safari.

**Comment by saintsoup52** [comment]
This is what I am seeing in IE 11

![image](https://cloud.githubusercontent.com/assets/4397508/24626771/5e5fbc86-1880-11e7-939d-6468433c8263.png)

**Comment by U-DON** [comment]
I see; I can get the same result in Firefox if I adjust the width of the screen to under 300px (like about 250px or so). But I'm not sure this is a realistic screen width for a user. This occurs because the SVG graph scales with the page, but the link is part of the regular HTML and matches the size of text in the rest of the document.

At 320px, the minimum screen width preset that I test with for the mobile experience (apparently the width of iPhone 5), it looks like this:
> <img width="305" alt="screen shot 2017-04-03 at 7 32 20 pm" src="https://cloud.githubusercontent.com/assets/1067024/24635890/74070e76-18a4-11e7-8892-068258e21eae.png">

@melwoodard Any thoughts on this?

**Comment by U-DON** [comment]
The small size of the text in the graph can be slightly improved if I remove the unnecessary margins from the sides of the graph (still at 320px screen width):
> <img width="306" alt="screen shot 2017-04-03 at 7 39 25 pm" src="https://cloud.githubusercontent.com/assets/1067024/24636044/6018d510-18a5-11e7-9c07-3742003a0d6e.png">

**Comment by melwoodard** [comment]
@U-DON you beat me to it - I was about to suggest the same thing. There's a 1em margin around the `.graph-component` div that isn't needed.

320px+ viewport width covers 99% of our traffic, so as long as the charts are readable at that scale we should be fine.
