### ISSUE TITLE
Spousal coverage monthly premium rates table

### ISSUE THREAD

**Issue by DanielleSoCompany** [department-of-veterans-affairs/vets-website#5265]
Hi @melwoodard and @rroueche. Here is another table that needs to be created for the Life Insurance section. It will go in the Family Servicemembers' Group Life Insurance (FSGLI) page: https://github.com/department-of-veterans-affairs/vets-website/blob/content/wip/life-insurance/content/pages/life-insurance/options-and-eligibility/fsgli.md.

Please see attached for table content, and see note within github page for placement. Thanks!
[Spousal Coverage Monthly Premium Rates Table.docx](https://github.com/department-of-veterans-affairs/vets-website/files/899984/Spousal.Coverage.Monthly.Premium.Rates.Table.docx)

**Comment by melwoodard** [comment]
@DanielleSoCompany this one is going to be a little tricky to implement, since standard markdown tables can't accommodate the multi-row table heading you have here with the Age of Spouse row above the age brackets:

![image](https://cloud.githubusercontent.com/assets/4106356/24726771/6534bed8-1a08-11e7-8f4c-81412583f481.png)

I can build out a custom table to suit it which will take a little more time, but I want to confirm with you first that those two tiers are necessary and can't be simplified into one somehow.

The number of columns in this table also isn't going to be friendly for mobile (you'll only be able to see the left 50%-ish of the table). If the content team is anticipating we'll have more data represented in a table format like this, it would be worthwhile for the front-end side to take some time to optimize the table experience to work better on mobile.

**Comment by DanielleSoCompany** [comment]
Hi @melwoodard. That makes sense. Let me look at it again with @bethpotts and try to simplify. I just did that for some tables in pensions and it worked nicely. Will get back to you soon with hopefully a simplified version of this!

**Comment by DanielleSoCompany** [comment]
Hi @melwoodard. Please see attached for new approach and let me know what you think. Thanks!

[Spousal Coverage Monthly Premium Rates Table Revised Approach.docx](https://github.com/department-of-veterans-affairs/vets-website/files/917242/Spousal.Coverage.Monthly.Premium.Rates.Table.Revised.Approach.docx)

**Comment by DanielleSoCompany** [comment]
Hi again, @melwoodard . Now that I have the table template, I can put this in. I'll leave notes for you re: the accordion links. Will start a separate issue for that, so I'm going to close this one for now. Thanks!
