### ISSUE TITLE
GI Bill: Missing Navigation Descriptions

### ISSUE THREAD

**Issue by raineystraus** [department-of-veterans-affairs/vets-website#530]
https://www.vets.gov/education/gi-bill/

Need second line of description for navigation list, e.g. Foreign Programs

**Comment by koconnor719** [comment]
@gnakm can you review this and see if it's still relevant w/ design team?

**Comment by gnakm** [comment]
@raineystraus @ss0ss Jumping in on this kind of late but I was wondering if this is something that should be closed because I don't know if we need a second line description for the navigation on this page? I know that the Conditions page under disability benefits has descriptions: https://www.vets.gov/disability-benefits/conditions/ Are we planning to have descriptions from 2nd level nav? Are we getting rid of descriptions or is it going to be case by case? Just curious.

**Comment by koconnor719** [comment]
Rainey is no longer on roject😀



Sent with Good (www.good.com)


-----Original Message-----

**Comment by rcarthur** [comment]
Great question, Gina.    My vote is for standardizing this one way or another.

**Comment by ss0ss** [comment]
@gnakm @dannychapman and I had some conversations on this a while back, before beta launch. I think we concluded to leave it as it is for now.

**Comment by gnakm** [comment]
If that's the case, I am going to close this issue. I think this will come up again on roadrunner so we could talk about it then. Let's sick with the "leave it as it is for now" conclusion.
