### ISSUE TITLE
Survivors and Dependents Assistance: Responsive table refinement

### ISSUE THREAD

**Issue by raineystraus** [department-of-veterans-affairs/vets-website#537]
The type gets too small at the smallest breakpoints. Need to refine pattern.

https://www.vets.gov/education/survivors-dependent-assistance/

**Comment by emilyville** [comment]
this does get comically small. assigning to you @webinista - I think we could make a patch for ourselves or / also ping USWDS because I can't imagine it's intentional.

**Comment by webinista** [comment]
Filed 18F/web-design-standards#1092 and will also fix in the meantime.

**Comment by webinista** [comment]
This is actually in `_va.scss`, lines 714-715. But there are a couple of problems I want to address first:

1. `/education/survivors-dependent-assistance` is in `/_education/gi-bill/survivors-dependent-assistance.md` in my local repo. Will that be the URL going forward?
2. I _think_ that whoever added the `table {font-size: .5em}` style was trying to shrink the font's size in order to make the table fit inside of the viewport most of the time. Increasing the font size would cause the table to overflow its container. That can be fixed by putting the table inside of a `div` with an `overflow:auto` style applied. But that does add some development / content team overhead.

![screen shot 2016-03-30 at 4 34 28 pm](https://cloud.githubusercontent.com/assets/354277/14161037/4cb36022-f695-11e5-94e4-07b12b36caa8.png)
