### ISSUE TITLE
GI Bill CT: Background error messages

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5487]
I was tracking the analytics on the GI Bill CT and I saw a number of error messages (see below). They don't appear to affect the user experience but it may be affecting how analytics are being tabulated.

![image](https://cloud.githubusercontent.com/assets/4397508/25751392/d50b5e06-3182-11e7-8f04-43df7ccd77c7.png)

**Comment by ayaleloehr** [comment]
These look CSP related, so deferring to @jkassemi

**Comment by leannammiller** [comment]
@jkassemi following up on this ticket.

**Comment by patrickvinograd** [comment]
Hi @saintsoup52, these console errors should affect neither user experience nor analytics. Content Security Policy (CSP) is a web standard that lets us prevent any third-party elements included on a vets.gov page from fetching un-permitted resources (e.g. possibly malicious scripts). While vets.gov does not have a great deal of third-party elements, CSP also helps protect users who may have inadvertently installed suspect browser toolbars and extensions. We explicitly whitelist the domains that we want to retrieve resources from, such as google analytics, youtube, uservoice, etc. 

The console errors you were seeing were due to some in-progress configuration work on our CSP policy. The site was configured in report-only mode, which reports CSP violations rather than actually blocking them, so any configuration errors would not affect users or analytics. In the meantime we have corrected any observed CSP configuration issues.
