### ISSUE TITLE
GI Bill CT: Analytics not tracking Additional Resources

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/vets-website#5488]
Because the new GI Bill CT links to two vets.gov websites in the additional resource box those links are no longer being tracked in the POE analytics.

Specifically, "Explore your career" and "Apply for education benefits".

Previously those links would trigger an outbound link event.

**Comment by robertfairhead** [comment]
I updated the Google Tag Manager config to treat anything outside of vets.gov/gi-bill-comparison-tool as an "outbound" link in order to catch links to other parts of vets.gov

Note: This breaks compatibility with our definition of "outbound" elsewhere so the outbound links stats in the GIBCT property will not match up with those in vets.gov all
