### ISSUE TITLE
Server website with HTTP Strict-Transport-Security

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/vets-website#589]
https://www.chromium.org/hsts

**Comment by konklone** [comment]
Yep, HSTS is a requirement of M-15-13. There's some accompanying documentation here: https://https.cio.gov/hsts/

The best outcome, and the one [recommended by OMB](https://https.cio.gov/guide/), is to add a policy to the root of the domain that includes each subdomain automatically, by adding an HSTS header to `https://vets.gov` that says the following:

```
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```

This means you don't have to worry about adding HSTS policies to each individual subdomain. It's also **much** easier to do this now, while you know that each subdomain on vets.gov supports HTTPS.

Adding that HTTP header to `https://vets.gov` is all it takes -- it's super easy to deploy on a technical level. Since it looks like `www.vets.gov` runs on nginx, you can add [this line in nginx](https://github.com/fisma-ready/nginx/blob/master/ssl/ssl.rules#L22) to turn it on:

```
add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload';
```

Just to note again -- the HSTS header has to be at the _root_ of the domain, at `https://vets.gov`, not at the `www` subdomain, for the policy to take effect.

**Comment by konklone** [comment]
Noting that since #601 was resolved (thank you!) this makes it a lot easier to address my issue here, which is to add an HSTS header to `https://vets.gov` with the following value:

```
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
```

**Comment by konklone** [comment]
Just a ping on this, as HSTS preloading vets.gov will declare the whole domain "done" and reduce compliance/configuration burden on the whole domain space in the long run.

**Comment by ayaleloehr** [comment]
cc @ShawnArnwine for prioritization and @knkski @jkassemi @joduinn for awareness.

**Comment by plusjeff** [comment]
Moved to devops repo
