### ISSUE TITLE
UserVoice Idea: Simplicity, transparency and accountability

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#592]
The biggest challenge to the VA website is funding direct answers to simple questions. For example, if I am sick today, but I'm not so ill that I need to go to the emergency room, what do I do? Does the VA have anything similar to "urgent care", where do I find it, and how do I access it? 

If I have a healthcare problem that I believe is not being adequately addressed, who do I go to to get help?  In my case, neither my primary care physician nor the  ever changing collection of specialists who are working on it seem to be able to answer basic questions like will I get better, how do we mitigate the effects of this illness, or how can I maximize the quality of my life? 

 If I have one appointment, and it is rescheduled for me, why am I not asked at the outset for the date and time that is convenient to meet? 

 If I have a compliment, question or complained about the care of it I have received at a community-based outpatient clinic, or special take care clinic, is it impossible to find out who is in charge so that I can let them know directly  about the quality of the care I have received?  In the military the chain of command is clearly known and transparently obvious to all. Perhaps that would be a good model for the VA to follow.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10662657-simplicity-transparency-and-accountability

**Comment by koconnor719** [comment]
marina, are you ok with this response:

Thank you for your feedback. Because vets.gov is an initial beta release, we do not yet have information on the site about healthcare. Please go to Va.gov for healthcare information at this time. Our design approach for healthcare information and services will be based on user feedback, including your comments, so we thank you for taking the time to provide us with feedback.

**Comment by koconnor719** [comment]
posted and closed.
