### ISSUE TITLE
UserVoice Idea: One site means one site

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#612]
I just received an email to get alerts/messages from the VA but I have to subscribe or "like" the VA on FB??  I don't want to check multiple sites for info - I just want one.  Will the same info be posted here?  And if I join/register on this site, will I get the same info?  One site recommendation really means one site.  Thank you.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10680396-one-site-means-one-site

**Comment by koconnor719** [comment]
Marina,

are you ok with this response: 

Thank you for your feedback. We are working to develop vets.gov as the one site for Veterans to access services and information they need. Because we are "developing in the open" and taking a Veteran focused and iterative approach to building vets.gov, we will have both VA.gov and vets.gov in operation while we do this.

**Comment by koconnor719** [comment]
posted and closed
