### ISSUE TITLE
User voice - facility locator

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#618]
facility locator problem

Can't select a location under facility locator page until the entire country's facilities upload on the map. Should select location first before that occurs. takes 5-10 seconds to load this way--frustrating and not user friendly.

**Comment by koconnor719** [comment]
marina and Bill, is this accurate on the load time? should this be the case?  pls. advise on response.

**Comment by jekrb** [comment]
I've made a branch where the data for the map is loaded into localstorage while visiting other pages (home page, etc..).  I'm not sure if this is an elegant solution, but it does drastically speed up the time in which the user can select a facility type by storing that data locally when they first visit the site rather than making an http request when they go to the facility locator.  If you want I can send a pull request for this.  However, I think a better idea would be to just allow the selection of type regardless if the data is available, and then once the data is loaded that filter will result in the map.  If that sounds like a better solution I honestly wouldn't mind undertaking the task.

**Comment by llimllib** [comment]
I just cut the size of the facilities file to about 20% of its previous size by setting s3 to serve it gzipped.

I have some ideas for how to cleverly serve partial location files to be more user-friendly. I will improve the responsiveness of the site before it gets downloaded in the meantime.

**Comment by llimllib** [comment]
(That 5x improvement just took effect right now, if you want to compare)

**Comment by koconnor719** [comment]
posted response and closed.

response:

Thank you for your feedback. Our team has made some adjustments and the Facility Locator performance should be better!  

vets.gov team
