### ISSUE TITLE
User voice - clarifying how VA assigns disability ratings

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#621]
Clarifying how VA assigns disability ratings

Under "Disability Benefits>Claims Process>How does VA assign disability ratings?", I do not believe the response answers the question in a clear enough manner. The response, "The amount of compensation depends upon the severity of your disability..." assumes that a service-connection will be/has been established. It does not clarify that in certain cases a Veteran will apply for disability, and may not have a service-connected disability in which case, VA will not assign a disability rating at all.

**Comment by koconnor719** [comment]
shaun, can you pls review this one and advise how you want me to respond:)  thanks. k

**Comment by ss0ss** [comment]
Understood - but this is semantics. You only get a rating if you have a service connected disability, even if it's 0%. This does assume that that there is service connection. I don't know @sjb912 you think this requires an edit like, "If VA determines a service connected disability, the amount of compensation depends upon the severity of that disability..." or something else along those lines. Or, we just ignore it.

**Comment by sjb912** [comment]
Folks will have lots of opinions about how much detail we should or shouldn't go into, usually skewed to his or her own specific case.  In this case, the statement the Veteran is objecting to is factually correct. We could go finer grained, as Shaun suggests -- nothing wrong with doing that, though I'd put that qualifier at the end instead of the beginning of the sentence. 

The amount of compensation depends upon the severity of your disability and whether VA finds it to be connected to your service.

**Comment by sjb912** [comment]
I'll go into GitHub and tweak it.

**Comment by koconnor719** [comment]
posted response:

Thank you for your feedback. We've modified the information on that page to reflect your feedback.

vets.gov team
