### ISSUE TITLE
UserVoice Idea: Mobile First - Security Always

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#637]
You know this but I'll add my voice to the comments:  please "bake in" security and mobility.  These can reinforce one another by offering easy multifactor authentication.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10683258-mobile-first-security-always

**Comment by koconnor719** [comment]
response: 

Thank you for your feedback. Veterans made it clear to us that mobile was an important requirement. Our design approach is mobile-first, and the the site is mobile responsive.  Vets.gov is hosted on a secure platform and will include secure authentication and authorization capabilities in 2016. We're still in the planning process for these capabilities.  Our goal is to provide Veterans with a single vets.gov secure account login that allows him or her to access all the services they need from the VA. Because we are developing in the open, we wanted to release vets.got as soon as possible and start getting Veteran feedback. Our goal is to release new content and functionality daily--or multiple times each day! We are planning to have a vets.gov account sign-on capability in the next few months.

vets.gov team

**Comment by koconnor719** [comment]
pls. confirm response is accurate on the authentication and authorization wording before i post:)

**Comment by koconnor719** [comment]
posted response and closed.
