### ISSUE TITLE
UserVoice Idea: Better UI

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#648]
Have more graphics

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10690737-better-ui

**Comment by koconnor719** [comment]
response:

Thank you for your feedback. We've heard this suggestion before! One of things that our research shows us that's specific to government sites is that uses want efficiency. They want to find information or complete a task quickly. To this end, our design team tried to keep vets.gov as clean and simple as possible. That's why we don't use graphics and images on the site.

vets.gov team

**Comment by koconnor719** [comment]
revised response:

Thank you for your feedback. We've heard this suggestion before! One of things that our research shows us that's specific to government sites is that uses want efficiency. They want to find information or complete a task quickly. To this end, our design team tried to keep vets.gov as clean and simple as possible. Generally, vets.gov avoids the use of imagery, icons and other visual embelishments. If an image is to be used, it should convey content that can not be adequately conveyed by text alone.

**Comment by koconnor719** [comment]
posted and closed
