### ISSUE TITLE
Comparison tool Data regeneration problem 012518

### ISSUE THREAD

**Issue by jmcneal65** [department-of-veterans-affairs/vets-website#7160]
the system is not generating the files properly. 
When uploading the file, the system is ingesting the file yet the system is not properly reading the file. If the system stalls in the mist of the generating/consolidating process, a required restarted of the process is increasing the data two to three folds. 
This is causing the number of school in the Comparison Tool to double or even triple the data. 
Requesting Digital Service to research: the cause of the system to stall during the consolidation phase? Why the data is being increase after the restart?

@leannammiller @mphprogrammer @patrickvinograd

**Comment by patrickvinograd** [comment]
@jmcneal65 I can probably figure it out by looking at the upload history, but can you give an idea of what new CSVs had been uploaded when the problem started occurring? In case it's something specific to the file contents.

**Comment by mphprogrammer** [comment]
Can you exactly recreate the steps you took? Which files you uploaded?

When the preview version of the data is being built (I am guessing a reason): The process is wrapped in a transaction, and because we can't lock the data rows (it prevents vets from using the tool) hitting the "back button" before the first build is complete and redoing the build will cause the exact same "new" version number to be generated resulting in a "doubling" of the data.

The question to me is why is the tool "stalling" when "generating/consolidating" (I guess this is the build preview process)?

**Comment by jmcneal65** [comment]
First, upload WEAMS and Complaint CSV files, Secondly, we generate a new preview version, which is where the problem seems to begin.

**Comment by jmcneal65** [comment]
Today (013018), we were able to upload the Complaint File to the dashboard, but when I tried to upload the WEAMS (x5) it kept giving me “this page cannot be displayed”.

**Comment by patrickvinograd** [comment]
I believe any issues uploading files are probably intermittent VA networking issues.

However, the process of generating preview versions (aka "consolidating" mentioned above) does appear to be getting slower over time. The way GIDS is implemented we store all previous versions of the institutions table so that table is growing over time and potentially slowing down the generation process. 

We could investigate/tweak database indexes, but a simpler solution would be to prune old versions of the institutions table. I know @mphprogrammer had some ideas about having historical revisions of the data at hand, but I don't know if those were just interesting ideas or actual product requirements. In any case we could export the old revisions for posterity's sake and then prune the database to improve runtime performance. We could leave the last (say) 5 revisions in place in  case a rollback is needed, but I don't see a reason why versions from early 2017 need to be available in the database.

**Comment by saintsoup52** [comment]
For what its worth... someone within VA needs to be tracking the final data sets of the GI Bill Comparison Tool for data retention purposes. They could be FOIA'ed and previous versions of the tool have been requested before.

**Comment by patrickvinograd** [comment]
That is helpful to know. We won't wipe the data unilaterally, but would be good to know if it is already being stored (e.g. in exported CSV form) by somebody on the EDU team. @jmcneal65 can you comment on whether you already have a process for that?

**Comment by jkassemi** [comment]
We've pruned the Institution records, and exported records to S3 for future FOIA requests. We tested with the latest WEAMS and complaints files, and encountered similar errors when attempting to generate the new preview version, but the processing completed in the background.

We'll evaluate options and performance in more detail, and lay out a plan to address these issues permanently at our next meeting. 

@jmcneal65, please let us know if this has resolved the issue for now. If so, this ticket can be closed. Thank you!
