### ISSUE TITLE
526 Military info view only

### ISSUE THREAD

**Issue by cehsu** [department-of-veterans-affairs/vets-website#7899]
@djmunoz1 has [indicated](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/10403#issuecomment-397723805) that we want to remove edit functionality from military service history (no content changes required).

# User story

As a user, I would like to be able to view my military history information.

# Acceptance criteria

- [ ] Military history is displayed in a view-only manner
- [ ] Complete/correct military history information is displayed
- [ ] Information is displayed consistently/properly formatted (using existing view logic)*

*Implementation detail

@goldenmeanie is any design work needed here? Or simply mimic how the other view-only pages look?

**Comment by cehsu** [comment]
@cvalarida @markgreenburg thanks for sharing any additional insights in the description here or adjusting the estimate, etc. We will likely need to update the milestone, for example.

**Comment by cvalarida** [comment]
I could have sworn I wrote this already...but I can't find it anywhere, so I guess I never did.

Anyhow, I'd add a couple things to the AC:
- [ ] The api is queried to fetch the latest military history
    - What's the URL for this? Is there an endpoint right now?
- [ ] An error message is shown if the call fails
    - Needs to be edited by @peggygannon 

Because most of the work is delegated to the `AsyncDisplayWidget`, we'll mostly be building the `viewComponent` and providing the error message. The estimate could probably be reduced to a 3.

Lastly, this ticket should probably be closed and re-written in the vets team repo for consistency. :wink:

**Comment by markgreenburg** [comment]
Closing - please see #11168 in team repo.
