### ISSUE TITLE
UserVoice Idea: links

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#825]
Possibly put a link on this website for myhealthevet.   Might want to add general information on how to register for VA Health Care and Eligibilities.  Add FAQ area.  I get a lot of calls about spouse or family members being able to use the VA for healthcare.  You might want to put some info on that on this webpage.  Otherwise a good start!

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10940256-links

**Comment by koconnor719** [comment]
posted response and closed.  

Thank you for your feedback. Because we are developing in the open, we've only launched a small portion of the rewritten and redesigned  content on vets.gov.  Right now we have information on disability and education benefits, but we will be adding additional information throughout the rest of 2015 and 2016 --as fast as we can. We plan to work on healthcare related information in early 2016, so please check back on the site often.  We'll hang on to your feedback and make sure we consider it when we start this work.  

Our team knows that language communicates our humanity. In the context of a website, it conjures up the people on the other side of that glowing screen. It engages, builds trust, and guides visitors through processes and information that can be stressful and confusing.

The primary headline on our home page reflects that: How can we help?

Vets.gov’s language is clear and direct, yet its tone is warm and quiet. We respect Veterans’ time, so we get to the point. And we avoid bureaucratese.

We don’t say utilize when use works just as well.

We avoid saying manifested, because started says it better.

We distill and simplify. We’re not selling programs and benefits, but rather helping Veterans and their families understand whether a benefit is right for them so they can make informed choices about how to proceed. Our goal is to give Veterans and their families the information they need to make important decisions confidently, easily—and done.

We plan to work on healthcare related information in early 2016, so please check back on the site often.  We'll hang on to your feedback and make sure we consider it when we start this work.  

vets.gov team
