### ISSUE TITLE
UserVoice Idea: include the CHOICE program

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#838]
links to the vet CHOICE..thank you that's all

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10953333-include-the-choice-program

**Comment by koconnor719** [comment]
posted response and closed.

Thank you for your feedback. We absolutely agree! We plan to feature the CHOICE program on vets.gov--we just haven't gotten to that yet. Because we are developing in the open, we are launching small portions of vets.gov, then getting Veteran feedback, then building out more of vets.gov based on that feedback.  This way we can ensure that everything we do is Veteran-driven. We plan to start working on healthcare related content and services in early 2016, so please check back on the site and continue to give us feedback.

vets.gov team
