### ISSUE TITLE
Vets.gov performs poorly on mobile environments

### ISSUE THREAD

**Issue by tevko** [department-of-veterans-affairs/vets-website#8391]
- **The environment you experienced the bug**: Mobile / fast 3G
- **The exact steps you took that triggered the bug**: Went to homepage, ran audit (attached)
- **The expected outcome**:  A faster site, removal of unused code, progressive web app capability, faster TTI, etc.
- **The actual outcome, including screen shot**: Site was slow to load, no serviceworker, no HTTP 2 support, not progressive web app capable, slow load and interactive time, 390KB of uncompressed javascript

<img width="1665" alt="screen shot 2018-09-12 at 10 32 58 am" src="https://user-images.githubusercontent.com/4431433/45432199-47658880-b677-11e8-835e-f7b6e734140b.png">
 

[www.vets.gov-20180912T101922.txt](https://github.com/department-of-veterans-affairs/vets-website/files/2375566/www.vets.gov-20180912T101922.txt)

**Comment by malchata** [comment]
In a time where [internet infrastructure in rural America is antiquated](https://www.technologyreview.com/s/603083/the-unacceptable-persistence-of-the-digital-divide/) (to put it nicely), I can think of nothing better within our grasp as developers than to improve mobile performance for a site to help vets get benefits. I'd be more than happy to partner up with @tevko to make this happen.

**Comment by slightlyoff** [comment]
See also: https://www.webpagetest.org/result/180912_6Q_5fd08e0ef64071de6f3cd266c36a3cac/

This can be reproduced using WebPageTest, selecting the `Mobile - Regular 3G` option: https://www.webpagetest.org/easy

A few key things jump out:

 * [Nearly 400K of script](https://www.webpagetest.org/result/180912_6Q_5fd08e0ef64071de6f3cd266c36a3cac/1/breakdown/)
 loads on this page, pushing back [Time-to-Interactive](https://developers.google.com/web/updates/2018/05/first-input-delay) by multiple seconds on a slow link and slow device. 
 * Contributing to that weight are many polyfills being sent to modern browsers which are not needed. Consider, perhaps, a solution like polyfill.io which can conditionally load them.
 * [Code-splitting](https://reactjs.org/docs/code-splitting.html) and route-based loading of dependencies would allow pages to avoid loading content they don't strictly need.
 * The gzip compression ratio on scripts is unusually low (reducing size by only half). Perhaps check configuration?
 * Connection setup time contributes to the overall slowness of the page, with many resources blocked on separate TLS connection setup. [HTTP/2 can help](https://http2.github.io/faq/#why-is-http2-multiplexed) with this.
 * Time-to-first-byte is pretty poor, indicating a lot of server "thinktime" for what is effectively static content. This should be one of the easier issues to fix.

**Comment by malchata** [comment]
> Code-splitting and route-based loading of dependencies would allow pages to avoid loading content they don't strictly need.

I have some ideas on addressing this. There may be some better configurations within `optimization.splitChunks` we can leverage to improve splitting.

I'd also like to see about differential serving/compilation to serve a lighter load comprised of ES6 modules with little to no polyfills for browsers that don't need them. I've been doing some research in this space.

**Comment by jbalboni** [comment]
Thanks for the feedback, everyone!

> Nearly 400K of script loads on this page, pushing back Time-to-Interactive by multiple seconds on a slow link and slow device.

Are you seeing this blocking interactivity on the the entire page or just the navigation menus? We had tried to set it up so that the rest of page was interactive while the menus were loading (not that that's a whole lot better). The reason for the React menus is convoluted and will take a while to unwind, but hopefully we can make improvements there.

@slightlyoff 

> Contributing to that weight are many polyfills being sent to modern browsers which are not needed. Consider, perhaps, a solution like polyfill.io which can conditionally load them.
Code-splitting and route-based loading of dependencies would allow pages to avoid loading content they don't strictly need.

I think we might have issues depending on something like polyfills.io, but I definitely think we can split the polyfills into a separate bundle and only load them when necessary. I did this on another site recently and am hoping to do that here, as well.

> The gzip compression ratio on scripts is unusually low (reducing size by only half). Perhaps check configuration?

I'll make an issue for our devops folks to look at this. I think we've talked about this and I don't remember why we left it there.

> Connection setup time contributes to the overall slowness of the page, with many resources blocked on separate TLS connection setup. HTTP/2 can help with this.

I'll put this on our list, too.

> Time-to-first-byte is pretty poor, indicating a lot of server "thinktime" for what is effectively static content. This should be one of the easier issues to fix.

This is sadly I think one of the harder ones to fix. The front end is comprised of static files being served by nginx. There is no server-side processing. I believe that slowness is related to issues with how we have to route things through the VA network.

@tevko / @malchata 

> Serviceworkers

We haven't had a chance to look into this, sadly, but it would definitely be a nice thing to leverage.

> I have some ideas on addressing this. There may be some better configurations within optimization.splitChunks we can leverage to improve splitting.

I would love to see some suggestions there. We don't do a lot of code splitting so far, but we could do a better job of this on content pages like the home page (content pages meaning pages that aren't React applications like the unauthenticated homepage).

**Comment by tevko** [comment]
Thanks for the prompt response @jbalboni ! We would love to help in any way we can. Are pull requests accepted? I'd love to get a better sense of how we can best help solve some of the outlined issues.

**Comment by jbalboni** [comment]
We can accept PRs, it's mostly just getting the time on our side to review and merge them, which I am not sure about yet. Digging into the repo and looking at our Webpack config and bundle contents and looking for red flags would be helpful, though. We've done a lot to reduce bundle sizes, but we're still not where we should be. I'll post an update in here when I get some more info about dedicating time to this.

**Comment by tevko** [comment]
Thanks @jbalboni  @jkassemi ! I'll produce docs and pull requests, feel free to use whichever ends up being helpful

**Comment by jkassemi** [comment]
👍, thanks @tevko!

**Comment by tevko** [comment]
@jbalboni @jkassemi I have some questions around building the site for production locally. Namely, after  setting `NODE_ENV=production` and running `npm run build -- --buildtype production`, where do I go to access the newly built environment. Will it mirror what I see on production? I ran the above commands after adding a setting to minify CSS and saw that the 2 main CSS files inside `/build/production/generated` were much larger than what was on `vets.gov` - any help would be much appreciated

**Comment by jbalboni** [comment]
@tevko That's the correct folder and it looks like the correct build command. What sizes are you seeing with and without your change? I can compare them to what I get locally.

**Comment by tevko** [comment]
@jbalboni How would I view the results of the build in my browser?

I'm seeing a 285kb style.[hash].css file after running on the build whereas it's about 60ish kb on prod

**Comment by jbalboni** [comment]
@tevko I think that's actually correct. The 60kb size in prod is gzipped and the result from the build process is not.

To view the site you can start a simple http server in the `build/production` folder to serve the files. Something like `php -S localhost:3001` or `python -m SimpleHTTPServer 3001`.

**Comment by tevko** [comment]
@jbalboni ahhh that makes sense. Can you confirm then that [this change](https://github.com/tevko/vets-website/commit/c8e0de52e7ac5c82fc276248f7ae44dff6a1eddd) would result in at least minimally smaller CSS sizes?

**Comment by tevko** [comment]
@jbalboni Excellent! Will open a PR then

**Comment by tevko** [comment]
@jbalboni have you seen any issues where after running `yarn install` dependencies won't be added? I've removed `node_modules` and reinstalled fresh about a hundred times now and get this error every time:

```
> vets-website@1.0.0 watch /Users/timevko/Desktop/dev/vets-website
> node script/build.js --watch

module.js:549
    throw err;
    ^

Error: Cannot find module 'metalsmith'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/timevko/Desktop/dev/vets-website/script/build.js:2:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vets-website@1.0.0 watch: `node script/build.js --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vets-website@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by jbalboni** [comment]
@tevko That looks a lot like there's a some config (NODE_ENV or something Yarn specific) that's set to production mode and isn't installing devDependencies.

**Comment by tevko** [comment]
@jbalboni I have some questions around [`splitChunks`](https://webpack.js.org/plugins/split-chunks-plugin/) and code splitting. Specifically, why are all vendors bundled together (L151 of webpack.config.js) and why is code splitting not enabled (which dynamically loads component resources as they're on demand)?

**Comment by jbalboni** [comment]
The vendor bundle contains the bundles that we know all of our apps use. They don't change much, so the hope was that we could cache that file over a longer period of time. This isn't really happening for other reasons, but it does at least mean that users who use different tools on the site can hopefully cache the file at least for the day. This was the strategy we picked back on Webpack 2 and it hasn't been significantly re-evaluated since moving to Webpack 4, with the newer splitChunks options. It's not all of our external dependencies, but it is most of the major ones. We probably want to let Webpack make some of these decisions instead of dictating that we have this particular bundle factoring, but we'll need to change how the script tags for each bundle are written to the pages to do so (not too hard, just some extra work). There's also another project going on right now that involves using some of this code on other VA sites that may restrict what we can do here, which has pushed that work down in priority some.

As for code splitting, we do in places explicitly split out code for certain features, but it's not very common for us because we don't have well-defined performance metrics and rules in place that force us to think about that as often as we should. We are actively working on the metrics part of that, at least.

**Comment by tevko** [comment]
Regarding the vendor bundles, I'm thinking the ideal practice would be to split them up and cache with a serviceworker once a users browser downloads them. This is because the user won't always need every single file, since I'm guessing they only visit a handful of routes per visit. The code splitting is an absolute necessity in terms of performance and I'm wondering if there are some simple areas where we can take a look at in terms of getting started.

Can we start by splitting up the vendor files in to individual script tags that get loaded in the footer with a `defer` attribute on them?

**Comment by malchata** [comment]
Is `html-webpack-plugin` used? If so, what you're describing should be somewhat achievable.

Sorry I've been off this. Been dealing with some life stuff.

**Comment by jbalboni** [comment]
Hey, I haven't forgotten about this, we have a big project going on that's sucking up all of my time.

We don't use `html-webpack-plugin`, but our current build process does something similar that we could augment, I believe.

That said, I'm not sure I understand the value of splitting up the vendor bundle. I may have mistyped something above, but that bundle contains the libraries that all of our apps use (React, etc). I believe all the code in there is used on every page currently (primarily for the menus and sign in functionality that's in the header of every page). I think we'd like to make most of that code not use React (or lazy load some of the stuff that does need React) so that we could cut down on the dependencies needed. But that's a little longer term and we have some odd constraints that we're currently thinking through.

**Comment by mchelen-gov** [comment]
I'm seeing render-blocking resources like:
```html
  <!-- CSS -->
  <link rel="stylesheet" data-entry-name="style.css" href="https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/style.c5ee6be980e4da2bdb95-1593539548642.css">
  <link rel="stylesheet" data-entry-name="static-pages.css" href="https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/static-pages.c93def881562d34531dc-1593539548642.css">
```
Can we distinguish critical CSS and inline it, then use `async` or `defer` for non-critical CSS per  https://web.dev/render-blocking-resources/ ?
