### ISSUE TITLE
UserVoice Idea: Life Events

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#869]
Create a life events center to help guide Veterans, Servicemembers, Family Members, and Caregivers to relevant content and resources based on their life events (ex. transitioning from service, having a child, moving, etc.) It could be similar to the USAA Advice Center: https://www.usaa.com/inet/ent_advice_center/EntAdviceCenter/AdviceCenter?1&wa_ref=pub_global_lifeevents_advice_main

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10998585-life-events

**Comment by sjb912** [comment]
Yes -- we've considered exactly this and would love to take this approach. It's how people think about their lives. As we migrate more information from other va sites, we'll be able to create the right content front end for this.

**Comment by koconnor719** [comment]
Posted response and closed (given this is our current UX approach):

Thank you for your feedback. This is a great sample page! Thanks for including it. Yes -- we've considered exactly this and are taking this approach to build vets.gov. It's how people think about their lives. As we migrate more information to vets.gov, we'll be able to create the right content and user experience for this. Right now, we have a small portion of the content that will eventually be on vets.got.  That's because we are designing in the open, and building the site based on Veteran and user feedback--like yours!  Please check back on vets.gov as we build out more content and services, and let us know what you think.

vets.gov team
