### ISSUE TITLE
UserVoice Idea: forum

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#870]
REQUEST: Place the Feedback Forum URL someplace on the home page where it will be more visible. It's not too visible in the lower right corner.
BENEFIT: More users will respond to this form.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/10998972-forum

**Comment by koconnor719** [comment]
I agree with this comment; the feedback forum link (is an improvement) is really small and all the way at bottom of page. Let's monitor other Veteran feedback on this, and consider making this link more prominent based on data. Propose response:

Thank you for your feedback. We just added this link to our feedback forum, based on Veteran feedback we received since we launched. We are going to monitor feedback over the next couple of weeks and see what users say. Then we'll revisit the placement of our feedback forum link.

vets.gov team

**Comment by koconnor719** [comment]
assigned to mary ann for user research; we've gotten several comments on improving the feedback forum. @maryannbrody @emilyville

**Comment by koconnor719** [comment]
posted and closed:

Thank you for your feedback. We conducted some research on this and have moved the feedback forum to a more prominent place on the homepage.  We also spelled out the link, replacing the lightbulb!  Hopefully this makes it easier for Veterans to provide feedback on vets.gov.

vets.gov
