### ISSUE TITLE
Servicemembers

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets-website#878]
noticing that we use both "Service Members" and "Servicemembers" on vets.gov.  are both acceptable or does this need to be changed.

**Comment by sjb912** [comment]
Thanks, Kelly. It's Servicemembers. It needs to be changed where it appears as two words. Do you know where you saw that?

**Comment by bethpotts** [comment]
I think I found which page it was (Survivors' and Dependents' Assistance), and I believe it happened when concurrence changes were added--edited text was overwritten. Good news is, it is fixed in staging and will go to the live site with the next push. Let me know if you see this anywhere else, Kelly, and I'll take care of it!

**Comment by koconnor719** [comment]
Thx Beth!!!



Sent with Good (www.good.com)


-----Original Message-----

**Comment by MarinaMartin** [comment]
Do we have special spellings like this in a reference-able list anywhere? That seems like a good thing for the playbook!

**Comment by koconnor719** [comment]
i'll close this issue since Beth fixed the original issue and add one for enhancement to playbook to add reference list; could also include things like capital "V" for Veteran, etc.
