### ISSUE TITLE
Is yellow (#fdb81e) the right color for highlighting info?

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#948]
USDS style guide puts yellow as a tertiary color with examples showing transient state.

I would have expected background callouts for persistent headers like "Education Benefits" and list item bullets in the footer to be a secondary color....

https://playbook.cio.gov/designstandards/visual-style/#colors

**Comment by awong-dev** [comment]
My attempted fix was be replace that background color with something from the secondary color palette...though nothing quite seem to look right...there's already enough blue-toned backgrounds on the page that another in that shade gets too busy w/o being differentiating enough for a header. Similarly, replicating the dark-blue background with white text is odd cause the banner background color is different from the content area :-/.

The problem with the yellow to me is the callout is extremely strong and forces attention onto the header which is often a non-actable portion of the page.  I would personally want attention focused more on the primary content/action area....but that just me trying to play a designer on televi^Wthe issue tracker.

Defer to your evaluation.

**Comment by emilyville** [comment]
Adding in @dannychapman since he might have more insight into this specifically!

In short, I think there are some user comments that call to attention to the problem you're addressing: we're calling a lot of attention to something that's not always interactive - see issue #722 .

My two cents: I personally 'like' the yellow for the further in breadcrumb pages (though another color might be just as effective) I think the problem might be the primary landing page when we ask a question "How can we help?" and maybe we *can* make that interactive, you know, so it helps.

**Comment by dannychapman** [comment]
Crazy thought, what if we turn this into an opportunity to do more. I'm thinking something with a simple animation. "How can we _____" (with the blank animating through different words)

**Comment by dannychapman** [comment]
I think the yellow works as a strong branding opportunity for us, while still keeping it inline with USDS. It's similar to gov.uk's use of a simple vertical line as their primary branding mark. Since we're not really about logos, photos or other traditional marketing techniques, the yellow is a simple way to set vets.gov apart.

**Comment by dannychapman** [comment]
That said, I do get the UX issue here. It needs to feel much more like a highlight and less like a button / box. See vox.com for an example.

**Comment by emilyville** [comment]
I am on the same page! I think making it like a thing that gets you to
where you want to go (shuffling through, and maybe eventually a super
guided search?) Would be awesome!

**Comment by emilyville** [comment]
I'm closing this because it's been consolidated into #1617

though I do love this thread very much, I think we can bring it into the homepage design fold and it will gain more traction.
