### ISSUE TITLE
Ensure pages are deleted from s3 when they are removed in a deploy.

### ISSUE THREAD

**Issue by awong-dev** [department-of-veterans-affairs/vets-website#957]
Per @llimllib: "currently old pages don’t get deleted i.e. version 1 has page a.html, then version 2 deletes it, a.html lives on in s3"

**Comment by dannychapman** [comment]
@awong-dev It would be great to get this fixed, as it causes quite a bit of confusion for the content team.

**Comment by awong-dev** [comment]
@dannychapman I have no clue how this works yet so I don't know how to fix it.  Tagging @plusjeff as this probably should be looked at as part of the devops fixit next week.

**Comment by plusjeff** [comment]
Thanks - will add it to the list!

**Comment by awong-dev** [comment]
@ayaleloehr hi hi.

**Comment by ayaleloehr** [comment]
and..... I have come to realize we still haven't done this. It looks like on each push (which happen on each merge to master), all the files that are supposed to be there get updated.  This means that any files that aren't updated should be deleted. 

We could use [Object Expiration](https://aws.amazon.com/blogs/aws/amazon-s3-object-expiration/), where we delete any files older than x days for example?  The HUGE danger with this is that if we don't merge anything to production for x days, then the entire site will be deleted. So that's not really a good plan, although we could set it up to run once to at least get rid of the old files?

I would prefer not to have to change the reverse proxy to have to point to a new bucket every time though, as that seems like more moving pieces than necessary (although maybe it's not...). Another idea would be to write a script on a cron job that looks at when index.html was last updated (as we know the site will always have an index.html on every push, right?) and delete any files more than like a day older than that?

cc @joduinn

**Comment by llimllib** [comment]
Shouldn't it be as simple as deleting all files in the s3 bucket with an mtime before the most recent deploy?

**Comment by webinista** [comment]
I'm not 100% up to speed on how we're deploying to S3. But if we're using the AWS CLI to deploy, it looks like we should be able to [pass a `--delete` flag](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html) to remove items that exist in the destination bucket, but not the source.

**Comment by plusjeff** [comment]
Done!

**Comment by joduinn** [comment]
Excellent - thank you @plusjeff ! This fixes a long-annoying resurfacing problem, so glad to finally have this off the annoyances list!!
