### ISSUE TITLE
UserVoice Idea: Why does it take the VA to pay out money owed to the veteran.

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#974]
http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11295936-why-does-it-take-the-va-to-pay-out-money-owed-to-t

**Comment by koconnor719** [comment]
posted response;

Thank you for your feedback.  I'm sorry but our team needs a little more information about this question in order to provide an answer.  Is this question specific to content or features on vets.gov?  If you can give us a little more information, we are happy to follow up on your comment. 

vets.gov team

**Comment by koconnor719** [comment]
closing this issue b/c no response since Dec. and if a response is posted another user voice issue will be opened.
