### ISSUE TITLE
UserVoice Idea: Please make this website clearer.

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#976]
Please make this website clearer and link it to other VA sites to find my DD 214. Also, it needs a "Logout" button.

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11303949-please-make-this-website-clearer

**Comment by koconnor719** [comment]
posted response and closed:'

Thank you for your feedback. The current vets.gov site does yet include a "login" feature.  It will in the coming months, and once we add this login feature we will add a "logout" feature as well.  We agree with your comment that it's important to have a clearly labeled login and logout feature on vets.gov--thank you! 

Because we are developing in the open, we have only built out a small portion of vets.gov so far.  We need Veteran feedback to drive the design and features as we build vets.gov in 2016. We will definitely provide easy to find links to your DD 214 and other forms and records that Veterans need.  We invite you to be part of our Veteran testing group. If you have 30 minutes to talk to to us about vets.gov, please contact our team at vavetsgov-feedback@va.gov.  Thank you for your feedback!

vets.gov team

**Comment by maryannbrody** [comment]
@koconnor719 - thank you!!! Just a reminder to please advertise it as "vets.gov feedback sessions" or something like that instead of "testing" which freaks people out and sounds more technical than it would be.
