### ISSUE TITLE
UserVoice Idea: Job Scam

### ISSUE THREAD

**Issue by MarinaMartin** [department-of-veterans-affairs/vets-website#996]
I think I may be dealing with a job scam emailed to me through the Va job portal

http://veterans.uservoice.com/forums/330333-vets-gov/suggestions/11328057-job-scam

**Comment by koconnor719** [comment]
related to VEC issue 487 (in VEC repo); 

posted response: 

Thank you for your feedback. It is unfortunate that anyone would try to take advantage of a Veteran. We have a blog post to help warn Veterans about protecting themselves from phishing attacks "Veterans Employment Center Website: False Claim of Breach" at http://www.blogs.va.gov/VAntage/23299/veterans-employment-center-website-false-claim-of-breach/ . We love your idea about linking to it from the VEC so that Veterans who are posting their resumes to various sites will know how to protect themselves and we will add that link right away.

**Comment by koconnor719** [comment]
closing this item since it is captured in VEC #487 and response has been posted.
